PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
INSERT INTO Players VALUES(1,1,'Hinaso1','',18,112,15,1,7,6,8,5,6,6,0,0,0,0,0,'','',0);
INSERT INTO Players VALUES(2,2,'@Gilgamesh2202','',15,83,6,7,6,6,6,8,8,8,0,0,0,0,0,'','',0);
INSERT INTO Players VALUES(3,3,'Gyro Zeppeli','',14,14,1,6,6,6,5,10,7,7,0,0,0,0,0,'','',0);
INSERT INTO Players VALUES(4,4,'Rat La Chi','',7,7,11,6,5,5,8,1,5,5,0,0,0,0,0,'','',0);
INSERT INTO Players VALUES(5,5,'Ar2di','',1,5,3,1,1,5,1,1,9,9,0,0,0,0,0,'','',0);
INSERT INTO Players VALUES(6,6,'Snaffy','',16,92,9,6,7,9,1,7,1,1,0,0,0,0,0,'','',0);
INSERT INTO Players VALUES(7,7,'KuSenpai','',10,10,12,9,6,1,8,4,2,2,0,0,0,0,0,'','',0);
INSERT INTO Players VALUES(8,8,'Ethan','',8,8,10,1,6,1,3,5,1,1,0,0,0,0,0,'','',0);
INSERT INTO Players VALUES(9,9,'Dian','',14,14,3,10,6,8,5,10,1,1,0,0,0,0,0,'','',0);
INSERT INTO Players VALUES(10,10,'Illyasviel Von Einzbern','',14,14,8,6,5,2,3,2,10,10,0,0,0,0,0,'','',0);
INSERT INTO Players VALUES(11,11,'wyug1234','',18,116,8,4,4,7,5,7,8,8,0,0,0,0,0,'','',0);
INSERT INTO Players VALUES(12,12,'Nagi','',17,110,13,6,6,6,4,4,10,10,0,0,0,0,0,'','',0);
INSERT INTO Players VALUES(13,13,'jcl2808','',2,12,5,6,9,6,6,7,7,7,0,0,0,0,0,'','',0);
INSERT INTO Players VALUES(14,14,'Seki','',19,117,12,4,8,10,5,4,7,7,0,0,0,0,0,'','',0);
INSERT INTO Players VALUES(15,15,'Lười (lazbu2501)','',10,10,14,8,8,4,10,7,9,9,0,0,0,0,0,'','',0);
INSERT INTO archetypes VALUES(1,'Warrior of Sunlight','Nhận Power "Sacred Fire" và "Fair Duel"','1,5','');
INSERT INTO archetypes VALUES(2,'Spy','Quay 1 Gia tộc để "lấy tình báo", nhận +1 all stat khi bắt đầu trận đánh với người đến từ Gia tộc đó.',2,'');
INSERT INTO archetypes VALUES(3,'Knight of Gods','Nhận +1 all Stats và Gear "Holy Symbol"','1,5','');
INSERT INTO archetypes VALUES(4,'Guardian of Demons','Nhận +4 vào stat thấp nhất và +3 vào stat cao nhất. Nhận "Demon''s Sin" Wheel.','1,5','');
INSERT INTO archetypes VALUES(5,'NPC ','-1 all stats và không thể có "Character Development". Bất kể những vòng quay sau có Char Dev cũng không được nhận.','3,4','');
INSERT INTO archetypes VALUES(6,'Slayer','Chọn 1 tộc để Slay. Khi đối đầu với tộc đó, nhận +2 Strength, +2 BIQ và +1 Martial Arts.','2,4','');
INSERT INTO archetypes VALUES(7,'Gigachad','Nhận +1 all stats khi đối đầu với tộc có thứ hạng cao hơn và -1 all stats khi đối đầu với tộc có thứ hạng thấp hơn trong vòng quay Race.','2,4','');
INSERT INTO archetypes VALUES(8,'Dark Magician','Nhận 2 Power và bạn thuộc về House "Dark Brotherhood". Không nhận vòng quay House nữa.','1,3','');
INSERT INTO archetypes VALUES(9,'Bloodclan Berserker','Nhận Quirk "Cruelty" và "Bloodthirsty" và bạn thuộc về House "Beast Clan". Không nhận vòng quay House nữa.','1,3','');
INSERT INTO archetypes VALUES(10,'Noble Swordsman',unistr('(1).Nếu vũ khí của bạn chỉ có 1 tag là "Magic", nhận thêm 1 Gear "Magic"\u000a(2).Nếu vũ khí của bạn chỉ có 1 tag là "Physical", nhận thêm 1 Gear "Physical"\u000a(3).Nếu vũ khí bạn có cả hai tag, nhận 2 Enchanted mà không phải quay vòng quay quyết định số lượng Enchant.'),'1,5','');
INSERT INTO archetypes VALUES(11,'Bard',unistr('Có 36% nhận được vòng quay "Instrument Weapon". Chắc chắn luôn sử dụng được tất cả vũ khí nhạc cụ.\u000aSkip vòng quay vũ khí thông thường.'),2,'');
INSERT INTO archetypes VALUES(12,'Hero Grave Keeper','Sau vòng đấu đầu tiên, nhận 1 gear ngẫu nhiên từ 1 người đã bị loại.',2,'');
INSERT INTO archetypes VALUES(13,'Dual Wielder','Nhận -3 Strength. Dùng được 2 vũ khí và chắc chắn nhận 2 vũ khí, tối đa 1 Unique Weapon.',2,'');
INSERT INTO archetypes VALUES(14,'Bookworm','Nhận +1 IQ và 1 Gear "Sổ tay"',2,'');
INSERT INTO archetypes VALUES(15,'Gambler','Mỗi round thắng trong combat, có 50% khả năng nhận nhận 2 điểm và 50% khả năng nhận 0 điểm.',2,'');
INSERT INTO archetypes VALUES(16,'Pacifist','Nhận +2 IQ và -4 Martial Arts.',2,'');
INSERT INTO archetypes VALUES(17,'Anti-Social','Nhận +5 all stats tại các vòng đấu PvE và -1 all stats khi đấu PvP.',2,'');
INSERT INTO archetypes VALUES(18,'Follower of the Two Fingers','Sau mỗi combat, giảm 1 IQ và 1 BIQ, cướp 1 Power từ 1 người chơi còn sống ngẫu nhiên.','1,8','');
INSERT INTO archetypes VALUES(19,'Devotee','Nhận +1 all stats khi combat với Demon, Vampire, Spirit, Orc, Skeleton và Goblin. Nhưng sẽ ngay lập tức thua khi đối đầu với God và Demi-God. (Hiệu ứng thua này mạnh hơn các hiệu ứng liên quan đến kết quả trận đấu khác).',2,'');
INSERT INTO archetypes VALUES(20,'Atheist','Nhận 1 điểm combat khi đối đầu với God và Demi-God.',2,'');
INSERT INTO archetypes VALUES(21,'X','Chỉ có duy nhất 1 người có thể làm X trong toàn bộ giải, khi lần đầu tiên có người quay ra "X", loại bỏ nó khỏi vòng quay Archetype. Khi người có archetype này nhận thất bại, sẽ loại bỏ archetype này từ người đó và chuyển nó sang cho người thắng. Khi bất kì ai nhận archetype "X", họ sẽ nhận vòng quay "Hero X", khi archetype này rời khỏi bất kì ai, người đó sẽ nhận -1 all stats.','0,3','');
INSERT INTO archetypes VALUES(22,'Glass Cannon','Bạn mặc định thua round "Durability", nhận +1 all stats.',2,'');
INSERT INTO archetypes VALUES(23,'Mid','Kết quả của toàn bộ vòng quay stats của bạn có giá trị là 5.',2,'');
INSERT INTO archetypes VALUES(24,'Time Traveller','Khi spin Base Stats, với mỗi chỉ số có điểm dưới hoặc bằng 3 sẽ spin lại 1 lần.',2,'');
INSERT INTO archetypes VALUES(25,'Zealot','Mỗi round combat thua, nhận +1 vào chỉ số thấp nhất (áp dụng sau combat).',2,'');
INSERT INTO archetypes VALUES(26,'Hand Fighter','Không thể nhận vũ khí. (Bypass toàn bộ hiệu ứng khác) Nhận +3 Strength và +2 Durability.',2,'');
INSERT INTO archetypes VALUES(27,'Lancer','Nhận vũ khí "Halberd", Nhận +2 Strength',2,'');
INSERT INTO archetypes VALUES(28,'Assassins','Nhận vũ khí "Hidden Blade", bỏ qua vòng quay Weapon trừ khi là nhận Unique Weapon.',2,'');
INSERT INTO archetypes VALUES(29,'Conquerer','Trong Combat: Khi bạn thắng round Speed, nhận +1 all stats trong phần còn lại của combat.',2,'');
INSERT INTO archetypes VALUES(30,'Trickster','Nhận "Trickster" wheel, kích hoạt trước mỗi combat và hết hiệu lực sau mỗi combat',2,'');
INSERT INTO archetypes VALUES(31,'Paladin','Nhận Power "Divine Smite", +1 MA',2,'');
INSERT INTO archetypes VALUES(32,'Summoner','Sau mỗi trận thắng, nhận 1 lần vòng quay Summon, không thể ra trùng Summon đã sở hữu. Sẽ không quay thêm nếu đã sở hữu tất cả các Summon.',2,'');
INSERT INTO archetypes VALUES(33,'Him','Nhận +2 all stats, đối thủ nhận 1 điểm ở cuối combat.',1,'');
INSERT INTO archetypes VALUES(34,'Wibu','Nhận "Wibu Wheel".',1,'');
INSERT INTO archetypes VALUES(35,'Perfectionist','Nhận +3 vào stat thấp nhất nếu bạn giành chiến thắng với cách biệt 4 điểm trở lên.',2,'');
INSERT INTO archetypes VALUES(36,'Hero of the Emirate','Nhận thêm Quirk số 36, Power số 36 ngay lập tức 🍀','3,6','');
INSERT INTO archetypes VALUES(37,'Edgelord','Khi kết thúc combat, so sánh điểm của hai bên, bên nào thấp điểm hơn sẽ nhận thêm 1 điểm.',2,'');
INSERT INTO archetypes VALUES(38,'Fisher','Nhận 1 Gear "Fishing Rod"',3,'');
INSERT INTO archetypes VALUES(39,'House''s Noble',unistr('Bạn cao quý, sinh ra từ dòng dõi lãnh đạo của Gia tộc.\u000aNhận 1 Legacy Gear'),2,'');
INSERT INTO archetypes VALUES(40,'Farmer','Nhận vòng quay "Farmer".',3,'');
INSERT INTO archetypes VALUES(41,'Loser','Toàn bộ Base Stat cao hơn 5 bị -2',2,'');
INSERT INTO archetypes VALUES(42,'Blacksmith','Nhận 2 Gear',3,'');
INSERT INTO archetypes VALUES(43,'Hunter','Nhận thêm 1 Round PvE',3,'');
INSERT INTO archetypes VALUES(44,'Thief','Cướp 1 Gear của 1 Player',3,'');
INSERT INTO archetypes VALUES(45,'Gambler Bloodline',unistr('Ở những vòng quay còn lại của quá trình tạo nhân vật, Có 50% không được quay vòng quay đó, Nếu là không nhận được vòng quay Stat, Stat đó mặc định là 1. \u000aÁp dụng lên cả những vòng quay phụ sinh ra từ Vòng quay chính'),'1,5','');
INSERT INTO archetypes VALUES(46,'Linh Mục','Nhận Power "Analysis Sins" và +1 IQ',3,'');
INSERT INTO archetypes VALUES(47,'Cha Xứ','Nhận Power "Cleaning Sins" và +1 BIQ',3,'');
INSERT INTO archetypes VALUES(48,'Quỷ Nhà Thờ','Trong Combat: Round Thứ 3(Dura) sẽ được +3',3,'');
INSERT INTO char_dev VALUES(1,'Armed to the Teeth','Nhận 3 Normal Gear ngẫu nhiên.','1,7','');
INSERT INTO char_dev VALUES(2,'Training Arc','Nhận +1 all stats.',2,'');
INSERT INTO char_dev VALUES(3,'In Love','Quay một player làm "Lover" và nhận +1 vào Stat mà người đó cao nhất.',2,'');
INSERT INTO char_dev VALUES(4,'No more Home','Bạn bị loại khỏi "House" của mình và mất tất cả Bonus từ đó.','1,2','');
INSERT INTO char_dev VALUES(5,'No more family','Nhận thêm 2 Power.','1,2','');
INSERT INTO char_dev VALUES(6,'Depression','Nhận -3 vào chỉ số cao nhất khi nhận Char Dev này.','2,4','');
INSERT INTO char_dev VALUES(7,'Seeking Wisdom','Nhận +4 IQ.','2,2','');
INSERT INTO char_dev VALUES(8,'Inversion','Đảo ngược tất cả base stat. (10<->1, 9<->2, 8<->3, 7<->4,6<->5,...)','0,9','');
INSERT INTO char_dev VALUES(9,'Isekai','Quay lại từ đầu ','0,9','');
INSERT INTO char_dev VALUES(10,'Final Reserves','Khi ở nhánh thua, +1 all stats. Khi đến vòng 16 người nhánh thua, loại bỏ hiệu ứng này và nhận 2 random Power.','1,6','');
INSERT INTO char_dev VALUES(11,'Lose Control','Mất tất cả Power. ','1,7','');
INSERT INTO char_dev VALUES(12,'Prime time','Nhận +2 all stats. Vô hiệu hóa khi xuống nhánh thua và chung kết.','1,5','');
INSERT INTO char_dev VALUES(13,'Fate''s Trick','Có 50% khả năng nhân đôi stat thấp nhất và 50% khả năng chia đôi stat cao nhất. (làm tròn lên)','3,3','');
INSERT INTO char_dev VALUES(14,'Old Age','Nhận +3 IQ và -1 mọi chỉ số còn lại.','2,8','');
INSERT INTO char_dev VALUES(15,'Creator''s Favor','"Đấng Sáng Tạo" tùy ý buff cho nhân vật. (Không thay đổi quá 2 chỉ số). (Sẽ có danh sách các hành động có thể thực hiện)','1,3','');
INSERT INTO char_dev VALUES(16,'Become Woke','Nhận -3 IQ, +1 Strength và +1 Durability. ',3,'');
INSERT INTO char_dev VALUES(17,'Demonic Pact','Hiến tế 1 base stat ngẫu nhiên (giảm xuống 0) để nhận 3 Power.','2,2','');
INSERT INTO char_dev VALUES(18,'Mentor','Nhận thêm 1 Power từ 1 Player ngẫu nhiên. (Mục tiêu được chọn phải còn sống và mục tiêu đó sẽ mất power được chọn)','2,8','');
INSERT INTO char_dev VALUES(19,'It is what it is','Mất hết toàn bộ vũ khí của mình. ','1,5','');
INSERT INTO char_dev VALUES(20,'Make love','Quay 1 wheel bao gồm toàn bộ player hiện tại để chọn ra người tình. Có khả năng tạo ra Race mới ở mùa sau.','1,8','');
INSERT INTO char_dev VALUES(21,'Pessimistic','Khi xuống nhánh thua, -1 all stats.','1,6','');
INSERT INTO char_dev VALUES(22,'Finality','Race của bạn tuyệt chủng trong mùa này. ','0,8','');
INSERT INTO char_dev VALUES(23,'Last Standing','Khi là người duy nhất còn lại của "Gia tộc" (House), +2 all stats.','1,3','');
INSERT INTO char_dev VALUES(24,'Furry',unistr('(1).Trong Combat: Nhận +1 all stats khi đấu với Werebeast\u000a(2).Nếu thua Werebeast, nhận -1 All Stats.'),'1,9','');
INSERT INTO char_dev VALUES(25,'Abused','Nhận -1 IQ, +3 Durability. ','3,1','');
INSERT INTO char_dev VALUES(26,'A Big Gift!','Nhận 1 random Legacy Gear.','1,4','');
INSERT INTO char_dev VALUES(27,'Become Vegetarian','Nhận -2 Durability.',4,'');
INSERT INTO char_dev VALUES(28,'Creator''s Limitation','"Đấng Sáng Tạo" tùy ý nerf cho nhân vật. (Không thay đổi quá 2 chỉ số). (Sẽ có danh sách các hành động có thể thực hiện)',2,'');
INSERT INTO char_dev VALUES(29,'Braindead','Nhận -4 IQ. ',3,'');
INSERT INTO char_dev VALUES(30,'Blessed by Chaos','Kéo base stat của chỉ số cao nhất xuống 1, sau đó nhận thêm 2 Character Development.',3,'');
INSERT INTO char_dev VALUES(31,'Lost an Arm','Nhận -4 Martial Arts ',3,'');
INSERT INTO char_dev VALUES(32,'Lost a Leg','Nhận -4 Speed ',3,'');
INSERT INTO char_dev VALUES(33,'Obtain a Cultivation Technique','Nhận +2 BIQ, +3 Martial Arts.','1,9','');
INSERT INTO char_dev VALUES(34,'Become King Slayer',unistr('(1).Nhận Archetype "Slayer". Nếu bạn đang là một "Slayer", chọn thêm 1 tộc nữa.\u000a(2).Trong Combat: Nếu đối thủ có Char Dev "King''s Landing", nhận +1 All Stats.'),1,'');
INSERT INTO char_dev VALUES(35,'King''s Landing',unistr('(1).Khi bạn bị loại, tất cả mọi người còn sống trong "Gia tộc" của bạn sẽ được nhận 1 Power.\u000a(2).Trong Combat: Nếu bạn không có Archetype "Devotee", Không thuộc race "God" hoặc "Demi God", nhận -2 điểm khởi đầu và -10 IQ'),'0,5','');
INSERT INTO char_dev VALUES(36,'True Heir of the Emirate',unistr('Nếu bạn có Archetype số 36, nhận +1 All Stats 🍀\u000aNếu bạn có Unique Weapon số 36, nhận +1 All Stats 🍀'),'3,6','');
INSERT INTO char_dev VALUES(37,'Become Hand of The King',unistr('(1).Nhận +3 IQ\u000a(2). Trong Combat: Nếu đối thủ có Char Dev "Become King Slayer", nhận +1 All Stats.'),1,'');
INSERT INTO char_dev VALUES(38,'Kungfu Training','Nhận +2 Durability và +2 Martial Arts','1,9','');
INSERT INTO char_dev VALUES(39,'Too Horny','Nhận +3 Strength và +2 Durability, nhưng Base IQ biến thành 0.','3,6','');
INSERT INTO char_dev VALUES(40,'Creator''s Reforge','Loại bỏ vũ khí hiện tại, Creator sẽ chọn 1 vũ khí Normal cho bạn, vũ khí này sẽ nhận 1 Enchantment do Creator chọn.','1,8','');
INSERT INTO char_dev VALUES(41,'Become Perfectionist','Nhận Archetype "Perfectionist".','2,4','');
INSERT INTO char_dev VALUES(42,'Too Edgy','Nhận Archetype "Edgelord".','2,4','');
INSERT INTO char_dev VALUES(43,'Overcome the Habits','Với mỗi Quirk bạn có trên người, +1 vào stat thấp nhất. (Tính theo chỉ số từ vòng quay stats gốc và chỉ có 1 chỉ số duy nhất được chọn)','1,8','');
INSERT INTO char_dev VALUES(44,'Nghe Bài thú tội','50% Nhận Char Dev "Braindead", 50% Nhận Char Dev "Seeking Wisdom"',3,'');
INSERT INTO char_dev VALUES(45,'Trở thành Linh Mục','Nhận Archetype "Linh Mục"',3,'');
INSERT INTO char_dev VALUES(46,'Trở Thành Cha Xứ','Nhận Archetype "Cha Xứ"',3,'');
INSERT INTO char_dev VALUES(47,'Trở thành Quỷ Nhà Thờ','Nhận Archetype "Quỷ Nhà Thờ"',3,'');
INSERT INTO enchants VALUES(1,'Powerful','Nhận thêm +1 vào Str','5,9');
INSERT INTO enchants VALUES(2,'Swifty','Nhận thêm +1 vào Spd','5,9');
INSERT INTO enchants VALUES(3,'Sturdy','Nhận thêm +1 vào Dura','5,9');
INSERT INTO enchants VALUES(4,'Arcana','Nhận thêm +1 vào IQ','5,9');
INSERT INTO enchants VALUES(5,'Fearsome','Nhận thêm +1 vào BIQ','5,9');
INSERT INTO enchants VALUES(6,'Flexible','Nhận thêm +1 vào MA','5,9');
INSERT INTO enchants VALUES(7,'Indestructible Flesh Attached Weapon','Vũ khí của bạn không thể bị phá hủy, không thể bị tước đoạt, không thể bị tháo rời, thay thế trừ khi bạn chết đi. Không một thứ gì có thể thay thế da thịt của bạn kể cả 12 đôi dép',7);
INSERT INTO enchants VALUES(8,'Trickery',unistr('Sau 2 lần combat, toàn bộ Gear Normal của bạn sẽ biến mất.\u000aNhận 2 Power ngẫu nhiên vào lúc đó.'),8);
INSERT INTO enchants VALUES(9,'Perfect','Nhận 1 lần Creator''s Favor, nhưng chỉ giới hạn trong phạm vi "Gear/Weapon"',8);
INSERT INTO enchants VALUES(10,'Hungry','Nhận thêm 1 trận đánh PvE sau khi nhận Enchant này.',8);
INSERT INTO enchants VALUES(11,'Chaos','Nhận -4 ở Stat bất kì để lấy 2 Power.',8);
INSERT INTO enchants VALUES(12,'Warlord',unistr('Nếu bạn chưa thể sử dụng vũ khí, Roll lại với tỉ lệ dùng được +15%.\u000aNếu đã có thể dùng được vũ khí, nhận thêm 1 Gear.'),8);
INSERT INTO enchants VALUES(13,'Valyrian Touched',unistr('Vô hiệu hóa nội tại của Quái PvE\u000aNhận Round PvE với "White Walker". Không Roll PvE wheel nữa nếu nhận được Enchant này trong lúc tạo nhân vật.'),8);
INSERT INTO enchants VALUES(14,'Melodic',unistr('Vũ khí của bạn sẽ phát ra nhạc Ngọt lúc chiến đấu và được tính là nhạc cụ. \u000aNếu 1 vũ khí có nhiều "Melodic Weapon" Enchant, tất cả tiếng nhạc phát ra đều sẽ là nhạc Indie. À và nhạc sẽ phát ra cùng lúc với dạng Remix.'),9);
INSERT INTO enchants VALUES(15,'All-Father Blesses','Nhận +1 all stats, nhận thêm 1 Archetype, 1 Quirk, 1 Power, 1 Char Dev và 1 round PvE','0,6');
INSERT INTO houses VALUES(1,'House Lannister','Hear Me Roar!','Nhận 2 Gear','','Người nhà Lannister khi tới vòng 16 người sẽ nhận thêm 2 Gear và nhận thêm 1 Enchant lên Weapon hiện có.');
INSERT INTO houses VALUES(2,'House Stark','''Winter is coming''.','Nhận 1 "Dire Wolf"','','Người nhà Stark khi tới vòng 16, Nhận thêm 1 lần Bonus từ "Dire Wolf" của bạn.');
INSERT INTO houses VALUES(3,'House Targaryen','Fire and Blood','Nhận 1 "Dragon''s Egg" có tên, khi tới vòng 16, "Dragon''s Egg" sẽ nở.','','Người nhà Targaryen khi tới vòng 8 sẽ nhận Char Dev "Lord of the Seven Kingdoms"');
INSERT INTO houses VALUES(4,'House Baratheon','Ours Is The Fury.',unistr('Nhận +1 Str, +1 BIQ, +1 MA\u000aBase Stat thấp nhất sẽ được +2'),'','Người nhà Baratheon khi tới vòng 16, Nhận +1 Spd, +1 IQ, +1 MA và Base Stat cao nhất sẽ được +2');
INSERT INTO houses VALUES(5,'House Marais','The family of executioners who presided over the Shaded Castle.','Nhận Archetype "Slayer" lên 2 tộc. (Nói cách khác là nhận 2 lần Slayer)','','Người nhà Marais khi tới vòng 16, Nhận 1 Unique Weapon và 1 Legacy Gear từ vòng quay hoặc người đã chết.');
INSERT INTO houses VALUES(6,'House Caria','A Moon Greatsword, bestowed by a Carian queen upon her spouse to honor long-standing tradition.','Nhận +1 IQ và 2 Power.','','Người nhà Caria khi tới vòng 16, nhận 3 Power');
INSERT INTO houses VALUES(7,'House Hoslow','The tale of House Hoslow is told in blood.',unistr('(1).Nhận Archetype "Dual Wielder"\u000a(2).Nhận trước 1 "Whip"'),'',unistr('Người nhà Hoslow khi tới vòng 16, nhận 2 Enchant lên 2 Weapon, mỗi Weapon được 1.\u000aNếu chỉ có 1 Weapon, nhận 2 Enchant lên Weapon đó.\u000aNếu không có vũ khí, nhận 2 Weapon.'));
INSERT INTO houses VALUES(8,'Golden Order','The Golden Order is founded on the principle that Marika is the one true god.',unistr('(1).Nhận 1 Power.\u000a(2).Nhận 1 Great Rune.'),'','Người của Golden Order khi tới vòng 16 nhận +1 vào 3 Stat bất kì và 1 Power.');
INSERT INTO houses VALUES(9,'Ashina Clan','It was a place where we, the Ashina people lived. Where the waters flowed, straight from the source',unistr('Nhận "Uchigatana" và bỏ qua việc nhận vũ khí Normal của vòng quay trong quá trình tạo nhân vật (Vẫn nhận nếu đó là vũ khí Unique)\u000aNhận 1 "Kiếm Phái Ashina"'),'','Người của Gia Tộc Ashina khi tới vòng 16 người sẽ nhận tiếp 1 "Kiếm Phái Ashina" không trùng với cái đầu tiên.');
INSERT INTO houses VALUES(10,'Beast Clan','Gangrenous bestial wretches. They have no claim to this land.','Bắt đầu trận đấu, đối thủ bị vô hiệu hóa 1 "Power" tạm thời và -2 vào stat mà bạn cao nhất.','',unistr('Người của Bộ Lạc Mãnh Thú khi tới vòng 16 người sẽ Roll ngẫu nhiên 3 Player đã bị loại và "Gia tăng" Stat của mình theo Base Stat cao nhất của họ với tỉ lệ:\u000a+2/+1/+1'));
INSERT INTO houses VALUES(11,'Coven Council','The Coven''s subversion seeks to tangle the land with its blasphemous twine. And should it succeed, the toad, the snake, and the spider will delight in the blackened dawn.',unistr('Nhận +2 IQ\u000aKhi Player đến từ Coven Council bị loại, 1 Player ngẫu nhiên không phải thuộc "Coven Council" sẽ bị Re-spin lại 1 chỉ số bất kì.'),'','Thành Viên của Hội Đồng Phù Thủy khi tới vòng 16 người sẽ Re-Spin lại 1 stat ngẫu nhiên của toàn bộ 15 người cùng nhánh (Thắng hoặc thua)');
INSERT INTO houses VALUES(12,'Dark Brotherhood','I told him you can''t stop the Dark Brotherhood. Never could.',unistr('Nhận Quirk "Lurker", nếu đã có sẽ nhận +2 Stat thấp nhất thay vào đó.\u000aKhi Dark Brotherhood thắng một trận đấu, nhận 1 Normal Gear.'),'','Người của Hội Anh Em Bóng Đêm khi tới vòng 16 người sẽ Loại bỏ toàn bộ Gear Normal của mình, với mỗi Gear vứt đi, +2 vào Stat thấp nhất.');
INSERT INTO houses VALUES(13,'College of Winterhold','You know, if you have the aptitude, you should join the Mage''s College in Winterhold.','Nhận 1 Power và 2 "Magic" Gear','','Học Viên của Trường Ma Pháp Winterhold khi tới vòng 16 người sẽ nhận 2 Power và 3 "Magic" Gear.');
INSERT INTO houses VALUES(14,'Dessendre Family',unistr('"For those who come after."\u000a"When one falls, we continue."'),unistr('Nhận Power "Artist"\u000a50% Nhận Clair, 50% Nhận Obscur'),'','Người của Gia Đình Dessendre khi đến vòng 16 sẽ nhận "Clair" hoặc "Obscur" tùy vào cái mà họ còn thiếu.');
INSERT INTO houses VALUES(15,'Painted World of Ariandel','The cold and gentle painted world of Ariandel.',unistr('Nhận 2 Round PvE là "Sir Vilhelm" và "Sister Friede"\u000aVới mỗi trận thua PvE, nhận +1 Dura và +1 BIQ'),'','Người của Bức Họa Ariandel khi tới vòng 16 sẽ lần nữa nhận 2 Round PvE là "Darkeater Midir" và "Slave Knight Gael."');
INSERT INTO houses VALUES(16,'Tracen Academy','Eclipse first, the rest nowhere',unistr('Học Viện chỉ nhận Uma.\u000aNhận ngẫu nhiên từ 1->3 Strength, 1->3 Speed và 1->3 Durability.'),'','Học viên của Học Viện Tracen tới vòng 16 sẽ được nhận ngẫu nhiên từ 1->3 Strength, 1->3 Speed và 1->2 Power.');
INSERT INTO players_archetypes VALUES(1,36);
INSERT INTO players_archetypes VALUES(2,36);
INSERT INTO players_archetypes VALUES(3,26);
INSERT INTO players_archetypes VALUES(4,5);
INSERT INTO players_archetypes VALUES(5,29);
INSERT INTO players_archetypes VALUES(6,16);
INSERT INTO players_archetypes VALUES(6,35);
INSERT INTO players_archetypes VALUES(7,27);
INSERT INTO players_archetypes VALUES(8,19);
INSERT INTO players_archetypes VALUES(9,44);
INSERT INTO players_archetypes VALUES(10,28);
INSERT INTO players_archetypes VALUES(11,36);
INSERT INTO players_archetypes VALUES(12,43);
INSERT INTO players_archetypes VALUES(13,24);
INSERT INTO players_archetypes VALUES(14,48);
INSERT INTO players_archetypes VALUES(15,25);
INSERT INTO player_char_dev VALUES(1,36);
INSERT INTO player_char_dev VALUES(2,36);
INSERT INTO player_char_dev VALUES(3,26);
INSERT INTO player_char_dev VALUES(4,0);
INSERT INTO player_char_dev VALUES(5,5);
INSERT INTO player_char_dev VALUES(6,5);
INSERT INTO player_char_dev VALUES(7,36);
INSERT INTO player_char_dev VALUES(8,20);
INSERT INTO player_char_dev VALUES(9,26);
INSERT INTO player_char_dev VALUES(10,22);
INSERT INTO player_char_dev VALUES(11,14);
INSERT INTO player_char_dev VALUES(12,38);
INSERT INTO player_char_dev VALUES(13,26);
INSERT INTO player_char_dev VALUES(13,24);
INSERT INTO player_char_dev VALUES(14,31);
INSERT INTO player_char_dev VALUES(15,8);
INSERT INTO powers VALUES(1,'Artist','Khi xuống nhánh thua, Stat lẻ của bạn được +1. (Tính theo chỉ số quay được từ đầu - Base Stats)','');
INSERT INTO powers VALUES(2,'Writer','Khi xuống nhánh thua, Stat chẵn của bạn được +1. (Tính theo chỉ số quay được từ đầu - Base Stats)','');
INSERT INTO powers VALUES(3,'Critical Strike',unistr('Với mỗi round thắng, bạn có 20% nhận thêm 1 điểm.\u000aThứ tự ưu tiên: Ashina Skill - Crit - Gambler'),'');
INSERT INTO powers VALUES(4,'Red Shift/LP1211-M','Trong combat: Nếu bạn thắng ít nhất 1 trong 3 round đầu tiên (Strength/Speed/Durability), nhận +1 IQ, +1 BIQ và +2 MA.','');
INSERT INTO powers VALUES(5,'Shooting for Victory','Trong combat: Nếu bạn thắng ít nhất 1 và thua ít nhất 1 trong 3 round đầu tiên (Strength/Speed/Durability), nhận +1 IQ, +1 BIQ và +2 MA.','');
INSERT INTO powers VALUES(6,'Let''s Pump Some Iron!','Trong combat: Nếu bạn thắng chính xác 1 trong 3 round đầu tiên (Strength/Speed/Durability), nhận +2 IQ, +2 BIQ và +2 MA.','');
INSERT INTO powers VALUES(7,'U=ma2','Trong combat: Nhận +5 Durability nếu bạn thua round Speed.','');
INSERT INTO powers VALUES(8,'Ice Liquefactors','Hóa lỏng băng ???','');
INSERT INTO powers VALUES(9,'Crimson Poison','Đối thủ -1 Durability, giảm thêm 1 với mỗi 2 Power sở hữu.','');
INSERT INTO powers VALUES(10,'Bloody Strike','Nhận -1 All Stats. Với mỗi Round thắng,+1 vào Stat đó (Áp dụng sau combat)','');
INSERT INTO powers VALUES(11,'Divine Smite','Nhận +1 Điểm nếu thắng ở Round MA. Xảy ra sau cùng, sau khi "Kiếm Phái Ashina".','');
INSERT INTO powers VALUES(12,'Fire Control','Có thể điều khiển được một ngọn lửa bật hoặc tắt. Ngoài ra không tác dụng ','');
INSERT INTO powers VALUES(13,'Thunder Orb','Đối thủ giảm 2 Durability.','');
INSERT INTO powers VALUES(14,'Water Breathing','Thở dưới nước.','');
INSERT INTO powers VALUES(15,'Golden Vow','Bản thân khởi đầu trận đấu với +1 điểm.','');
INSERT INTO powers VALUES(16,'Healing Factor','Nhận +1 Durability. Với mỗi 2 round thua trong 1 combat, nhận +1 Durability. (áp dụng sau combat)','x');
INSERT INTO powers VALUES(17,'Hunter''s Rewards','Sau khi thắng 1 combat PvP, nhận 2 phần thưởng PvP thay vì 1.','x');
INSERT INTO powers VALUES(18,'Mind Control','Nhận +1 all stats khi đối đầu với kẻ địch có IQ từ 5 trở xuống.','');
INSERT INTO powers VALUES(19,'Blood Manipulation','Nhận +1 strength khi đối đầu với tất cả kẻ địch trừ "Skeleton" và "Spirit".','');
INSERT INTO powers VALUES(20,'Sonic Scream','Đối thủ nhận -1 Durability.','');
INSERT INTO powers VALUES(21,'Drunken Boxing','Nhận -1 IQ, -1 Speed và +3 MA.','');
INSERT INTO powers VALUES(22,'Hey Ya!','Bạn được cổ vũ tinh thần .','x');
INSERT INTO powers VALUES(23,'Time Travel','Re-spin lại chỉ số thấp nhất 1 lần.','');
INSERT INTO powers VALUES(24,'Cursed','Re-spin lại chỉ số cao nhất 1 lần.','');
INSERT INTO powers VALUES(25,'Divine Lightning','Nhận +1 Strength, +1 Speed và +1 MA, tăng lên +2 nếu chiến đấu với Demon.','');
INSERT INTO powers VALUES(26,'Jogan','Mắt sáng, không bị cận','x');
INSERT INTO powers VALUES(27,'Fist Fighting','Nếu sở hữu vũ khí, mất đi nó. Nhận +2 MA.','');
INSERT INTO powers VALUES(28,'Evasion','Mỗi round thua trong combat, có khả năng nhận được 1 điểm (Wheel 20%)','');
INSERT INTO powers VALUES(29,'Enhanced Hearing','Nhận +2 MA, -1 all stats nếu đối thủ dùng nhạc cụ và -2 nếu đối thủ có Power liên quan tới âm thanh.','');
INSERT INTO powers VALUES(30,'Rampage','Sau mỗi trận thắng, có 25% khả năng nhận +1 all stats.','');
INSERT INTO powers VALUES(31,'Bloodlust','Sau mỗi trận thắng, nhận -1 IQ, -1 MA và +1 Strength, +1 Speed, +1 Durability.','');
INSERT INTO powers VALUES(32,'Rickrolling','Chắc không cần giải thích đâu nhỉ ','');
INSERT INTO powers VALUES(33,'Power Absorption','Sau mỗi trận thắng, hấp thụ 1 Power ngẫu nhiên của đối thủ.','');
INSERT INTO powers VALUES(34,'Hand Washing','Tay sạch ','');
INSERT INTO powers VALUES(35,'Power Negation','Trong Combat: Vô hiệu hóa 1 Power ngẫu nhiên của đối thủ.','');
INSERT INTO powers VALUES(36,'Stat Absorption','Sau mỗi trận thắng, +1 cho bản thân vào chỉ số mà đối thủ có cao nhất.','');
INSERT INTO powers VALUES(37,'Invulnerability','Nhận +2 Durability.','');
INSERT INTO powers VALUES(38,'Power Mimicry','Sao chép 1 Power ngẫu nhiên của đối thủ. (chỉ trong trận đấu đó)','');
INSERT INTO powers VALUES(39,'Mewing','Bye bye 🤫🧏‍♂','');
INSERT INTO powers VALUES(40,'Railroad Realm','Trong Combat: Bạn và đối thủ sẽ nghe tiếng xình xịch của những đoàn tàu xe lửa 🍀','');
INSERT INTO powers VALUES(41,'Possession',unistr('Chọn một stat ngẫu nhiên (trừ IQ). \u000aNếu IQ của bạn cao hơn đối thủ, hoán đổi stat được chọn với đối thủ nếu stat của bạn thấp hơn. Nếu IQ của bạn thấp hơn đối thủ thì ngược lại. (Hiệu lực vĩnh viễn)'),'');
INSERT INTO powers VALUES(42,'Overdrive','Nhận +2 MA, -2 Durability.','');
INSERT INTO powers VALUES(43,'Age Manipulation','Đối thủ +1 IQ, -1 mọi stat còn lại)','');
INSERT INTO powers VALUES(44,'Enlarging','Nhận +2 Strength, +2 Durability, -4 Speed.','');
INSERT INTO powers VALUES(45,'Shrinking','Nhận +4 Speed, -2 Strength, -2 Durability.','');
INSERT INTO powers VALUES(46,'Garlic Breath','Nhận +1 all stats nếu đối thủ là Vampire. ','');
INSERT INTO powers VALUES(47,'The Goat','Bạn là dê! ','');
INSERT INTO powers VALUES(48,'Fancy Feet','Nhận -1 Durability nhưng vô hiệu hóa vũ khí của đối phương.','');
INSERT INTO powers VALUES(49,'Weapon Enhancing','Thêm +1 vào mỗi buff tăng stat ở vũ khí, thêm -1 vào mỗi debuff giảm stat.','');
INSERT INTO powers VALUES(50,'Body Enhancing','Nhận +1 Strength, +1 Speed, +1 Durability.','');
INSERT INTO powers VALUES(51,'Clear Mind','Nhận +2 IQ.','');
INSERT INTO powers VALUES(52,'Petrification','Đối thủ nhận -3 Speed.','');
INSERT INTO powers VALUES(53,'Blowing Leaves','Thổi lá bay đi ','');
INSERT INTO powers VALUES(54,'Force Field','Đối thủ nhận -1 Speed, -1 MA.','');
INSERT INTO powers VALUES(55,'Anti-Magic Barrier','Trong combat: Vô hiệu hóa 2 Power của đối thủ, nhận -1 Durability.','');
INSERT INTO powers VALUES(56,'Black Magic','Trong combat: Đối thủ nhận -2 vào một stat ngẫu nhiên.','');
INSERT INTO powers VALUES(57,'The Great Storm','-2 Durability của Đối thủ','');
INSERT INTO powers VALUES(58,'Continental Super Storm','Nhận +2 Speed','');
INSERT INTO powers VALUES(59,'Sacred Fire','Nhận +1 all stats nếu đối thủ là Vampire hoặc Demon.','');
INSERT INTO powers VALUES(60,'Capybara','Capybara','');
INSERT INTO powers VALUES(61,'Tsunami Control','Nhận +2 Strength','');
INSERT INTO powers VALUES(62,'Rising tide','Nhận +1 MA','');
INSERT INTO powers VALUES(63,'Seismic',' Đối thủ -1 MA','');
INSERT INTO powers VALUES(64,'Earth-Shaking','Đất đá rung chuyển.','');
INSERT INTO powers VALUES(65,'Disarmament','Trong combat: Vô hiệu hóa vũ khí đối thủ ','');
INSERT INTO powers VALUES(66,'Night Vision','Có thể nhìn trong bóng tối. ','');
INSERT INTO powers VALUES(67,'Unstoppable','Miễn nhiễm với mọi debuff giảm stat từ đối thủ.','');
INSERT INTO powers VALUES(68,'Gotta go Fast','Bạn là Sonic ','');
INSERT INTO powers VALUES(69,'Fair Duel','Bạn và đối thủ miễn nhiễm với mọi hiệu ứng giảm stat từ nhau.','');
INSERT INTO powers VALUES(70,'Uno Reverse Card','Trong Combat: Mọi debuff giảm stat từ đối thủ sẽ chuyển sang áp dụng lên chính hắn.','');
INSERT INTO powers VALUES(71,'Burning Hand','Nhận +1 Strength. ','');
INSERT INTO powers VALUES(72,'Tick-tock','Cơ thể bạn phát ra tiếng của đồng hồ. ','');
INSERT INTO powers VALUES(73,'Frost Armor','Nhận +1 Durability.','');
INSERT INTO powers VALUES(74,'Acid-Throated','Cổ họng đầy Axit, khi thua trận khiến -2 Durability cho đối thủ.','');
INSERT INTO powers VALUES(75,'Lightning Enchant','Nhận +2 Speed','');
INSERT INTO powers VALUES(76,'Acid Breath','-1 Durability đối thủ.','');
INSERT INTO powers VALUES(77,'Poison Breath','-1 IQ của đối thủ.','');
INSERT INTO powers VALUES(78,'The Honored One','Giảm 1/2 Durability (làm tròn xuống), Nhận +3 MA.','');
INSERT INTO powers VALUES(79,'Chaos Enchantment','Nhận +1 Str và +1 MA khi trong nhánh thua.','');
INSERT INTO powers VALUES(80,'Dream Manipulation','Khi combat, đối phương -2 IQ và -1 Speed.','');
INSERT INTO powers VALUES(81,'Powerful Strike','Nếu có vũ khí, nhận +2 MA','');
INSERT INTO powers VALUES(82,'Fragrant','Thơm tho dễ chịu.','');
INSERT INTO powers VALUES(83,'Hidden Potential','Nhận thêm 1 "Character Development".','');
INSERT INTO powers VALUES(84,'Voidwalking','Nhận +2 Speed.','');
INSERT INTO powers VALUES(85,'Odin Blessing','Nhận "+2 Strength". Chuyển thành "+2 vào Stat cao nhất" khi thua trận.','');
INSERT INTO powers VALUES(86,'Misty Step Ahead','Ở round PvE khởi đầu với 1 điểm.','');
INSERT INTO powers VALUES(87,'Ballet Dancing','Múa dẻo 💃','');
INSERT INTO powers VALUES(88,'Luck Manipulation','Trong Combat: Từ vòng 64, trước mỗi trận combat, có 15% khả năng nhận +1 all stats và 5% khả năng nhận +2 all stats.','');
INSERT INTO powers VALUES(89,'Tree Bound','Bị -1 All Stat không phải Durability, +5 vào Durability','');
INSERT INTO powers VALUES(90,'Scrying','Trong Combat: Đối thủ có 10% bị -4 Stat mạnh nhất.','');
INSERT INTO powers VALUES(91,'Baldening','Khiến đối thủ bị rụng hết tóc. ','');
INSERT INTO powers VALUES(92,'Cold Breeze','Mát lạnh!','');
INSERT INTO powers VALUES(93,'Return to Sender','Sau Combat thua, -2 stat cao nhất của đối thủ. ','');
INSERT INTO powers VALUES(94,'Bucking Bronco','Round Martial Arts thắng và thắng trận sẽ nhận +1 Martial Arts. (Stack)','');
INSERT INTO powers VALUES(95,'Detect Thoughts','Trong Combat: Nếu bạn có IQ cao hơn đối thủ, BIQ của bạn sẽ được +2.','');
INSERT INTO powers VALUES(96,'Ritual of Blood','Nhận -4 Durability. Trong Combat: Đối phương nhận -1 all stats.','');
INSERT INTO powers VALUES(97,'Quirkful','Nhận Thêm 1 Power với mỗi Quirk bạn có khi quay ra Power này.','');
INSERT INTO powers VALUES(98,'Quirkless','Mất hết tất cả Quirk.','');
INSERT INTO powers VALUES(99,'Super Lucky',unistr('(1).Khi thua trận, bạn có 15% lật kèo và thắng trận đấu đó.\u000a(2).Nếu không chiến thắng trong vòng quay của hiệu ứng (1), bạn sẽ có thêm một cơ hội nữa với 10% lật kèo.\u000aThua nữa thì ggs.'),'x');
INSERT INTO powers VALUES(100,'Sybaurafarming',unistr('Tất cả Base Stat trên 5 sẽ biến thành 5\u000aVới mỗi Base Stat bị biến đối, nhận thêm 1 Quirk'),'');
INSERT INTO powers VALUES(101,'Arcana Blast','Đối thủ nhận -3 Durability.','');
INSERT INTO powers VALUES(102,'Blood Frenzy','Nhận -3 IQ và -3 BIQ, +2 all stat còn lại.','');
INSERT INTO powers VALUES(103,'Analysis Sins','Trong Combat: Khi đối đầu với Demon, Vampire, Spirit, Orc, Skeleton và Goblin, nhận +1 IQ và +1 Strength','');
INSERT INTO powers VALUES(104,'Cleaning Sins','Trong Combat: Khi đối đầu với Demon, Vampire, Spirit, Orc, Skeleton và Goblin, nhận +1 BIQ và +1 Dura','');
INSERT INTO powers VALUES(105,'Hydrate','Cơ thể bạn được cung cấp đủ nước. 💦💦💦','');
INSERT INTO powers VALUES(106,'Gourmand','Trong Combat: Nhận +4 Durability.','');
INSERT INTO powers VALUES(107,'Lone Wolf','Nhận +3 Speed, khi gặp người chơi cũng có Power này, bạn sẽ mất Power này vĩnh viễn.','');
INSERT INTO powers VALUES(108,'Swinging Maestro','Trong Combat: Nhận +4 Durability.','');
INSERT INTO powers VALUES(109,'The Coast is Clear!','Bạn nhìn rõ đối thủ!','');
INSERT INTO powers VALUES(110,'Prideful King','Trong Combat: Nếu bạn thua 3 round đầu tiên với khoảng cách dưới 3 điểm, bạn sẽ nhận +2 all stats trong phần còn lại của combat.','');
INSERT INTO powers VALUES(111,'Groundwork','Trong Combat: Nếu bạn có ít nhất 3 Power khác, nhận +2 Strength và +1 Speed.','');
INSERT INTO powers VALUES(112,'Dominator','Trong Combat: Nếu bạn thua ít nhất 2/3 round đầu tiên, đối phương nhận -1 all stats trong phần còn lại của combat.','');
INSERT INTO powers VALUES(113,'Quay tay ra bài','Sau khi combat với người có Char Dev "Nghe Bài thú tội", đối thủ nhận -2 IQ (Áp dụng sau combat)','');
INSERT INTO powers VALUES(114,'Ice Spike','Đối thủ nhận -2 Durability.','');
INSERT INTO powers VALUES(115,'Bash','Trong combat: Sau mỗi round thắng, đối thủ có 35% bị -3 vào chỉ số ở round kế tiếp.','');
INSERT INTO powers VALUES(116,'Devour','Sau khi chiến thắng 1 trận PvP ở NHÁNH THUA, cướp 1 Power từ người thua cuộc.','');
INSERT INTO pve_enemies VALUES(1,'White Walker',10,8,6,4,2,0,'Với một Round thắng, Stat tiếp theo của White Walker sẽ được +2','Nhận Archetype "Knight of Gods"','Mất hết toàn bộ Power','2,78');
INSERT INTO pve_enemies VALUES(2,'Sir Vilhelm',6,7,3,5,8,7,'0','Nhận Archetype "Devotee"','Không có gì xảy ra.','2,78');
INSERT INTO pve_enemies VALUES(3,'Sister Friede',5,9,4,7,9,6,'Với một Round thua, Stat tiếp theo của Sister Friede sẽ được +1','Nhận Archetype "Paladin"','Không có gì xảy ra.','2,78');
INSERT INTO pve_enemies VALUES(4,'Darkeater Midir',9,6,10,7,8,7,'Đối thủ nhận -3 Dura','Nhận vòng quay Dragon Sub-race và nhận hiệu ứng từ đó.','Không có gì xảy ra.','2,78');
INSERT INTO pve_enemies VALUES(5,'Slave Knight Gael',10,7,11,8,9,8,0,'Nhận Archetype "Gigachad"','Không có gì xảy ra.','2','78');
INSERT INTO pve_enemies VALUES(6,'Lesser Devils',5,5,5,4,4,4,0,'Nhận +1 Strength và +1 Durability.','Mất ngẫu nhiên 1 Power.','2,78');
INSERT INTO pve_enemies VALUES(7,'Pack of Wolves',5,5,4,4,5,1,'Critical Strike','Nhận power "Critical Strike". Nếu đã có power này, nhận +1 Vào Stat cao nhất','Nhận -1 Strength.','2,78');
INSERT INTO pve_enemies VALUES(8,'Elusive Elf',3,7,2,6,4,4,'Mỗi round thua trong combat, "Elusive Elf" có 20% nhận được 1 điểm','Nhận power "Evasion".','Nhận -1 Speed.','2,78');
INSERT INTO pve_enemies VALUES(9,'Treasure Goblin',1,9,9,5,1,1,'"Treasure Goblin" Khởi đầu với 1 điểm.','Nhận 1 PvP Rewards.','Không có gì xảy ra.','2,78');
INSERT INTO pve_enemies VALUES(10,'Red Buff',6,2,6,3,6,6,0,'Nhận +1 Strength và +1 Martial Arts.','Nhận -1 Martial Arts.','2,78');
INSERT INTO pve_enemies VALUES(11,'Blue Buff',6,2,6,3,6,6,0,'Nhận +1 IQ và +1 BIQ.','Nhận -1 IQ.','2,78');
INSERT INTO pve_enemies VALUES(12,'One-eyed Orge',7,3,7,3,7,3,0,'Nhận +2 Strength.','Nhận -1 Strength.','2,78');
INSERT INTO pve_enemies VALUES(13,'Mimic Tear','?','?','?','?','?','?','100% giống y hệt người đánh (bao gồm cả archetype, power, char dev...).','Nhận 1 Legacy Gear.','Không có gì xảy ra.','2,78');
INSERT INTO pve_enemies VALUES(14,'Jiangshi',5,5,5,5,5,5,0,'Mất 1 random power, sau đó nhận 2 random power.','Mất ngẫu nhiên 1 Power.','2,78');
INSERT INTO pve_enemies VALUES(15,'Ghouls',7,5,6,0,1,7,0,'Nhận Power "Blood Frenzy".','Nhận -2 stat cao nhất.','2,78');
INSERT INTO pve_enemies VALUES(16,'Odd Todd',1,3,9,5,7,7,0,'Nhận +1 các stat có chỉ số lẻ.','Không có gì xảy ra.','2,78');
INSERT INTO pve_enemies VALUES(17,'Even Steven',2,4,6,6,8,8,0,'Nhận +1 các stat có chỉ số chẵn.','Không có gì xảy ra.','2,78');
INSERT INTO pve_enemies VALUES(18,'Baron Nashor',10,1,10,10,10,1,0,'Nhận +2 all stats cho tới vòng 32.','Không có gì xảy ra.','2,78');
INSERT INTO pve_enemies VALUES(19,'Elden Beast',9,8,8,9,8,5,'"Elden Beast" Khởi đầu với 1 điểm.','Nhận power "Golden Vow" và 1 random Power.','Không có gì xảy ra.','2,78');
INSERT INTO pve_enemies VALUES(20,'Training Dummy',3,3,3,3,3,3,0,'Nhận +1 all stats nếu chiến thắng với cách biệt 6 điểm trở lên.','-1 all stats nếu không đạt đủ 4 điểm trở lên.','2,78');
INSERT INTO pve_enemies VALUES(21,'Trained Orc',6,4,6,3,6,5,0,'Nhận +1 Strength, +1 BIQ và +1 Durability.','Nhận -1 Speed.','2,78');
INSERT INTO pve_enemies VALUES(22,'Violet Vessel',14,14,14,14,14,14,'Người đối đầu với quái này sẽ thắng khi ghi được 2 điểm trở lên.','Nhận 2 random Normal Gear, 2 random Power và +2 vào 1 chỉ số ngẫu nhiên.','Không có gì xảy ra.','2,78');
INSERT INTO pve_enemies VALUES(23,'Skeleton Army',5,3,5,1,5,4,0,'Nhận 1 Summoning.','Mất ngẫu nhiên 1 Power.','2,78');
INSERT INTO pve_enemies VALUES(24,'Useless Slime',1,1,1,1,1,1,0,'Nhận 1 random Power','Nhận -5 All stats.','2,78');
INSERT INTO pve_enemies VALUES(25,'Pontiff Sulyvahn',6,6,6,6,9,9,0,unistr('Nhận Archetype "Dual Wielder" và 1 weapon để đủ 2 Weapon. \u000aNếu đã có sẵn Archetype này, nhận +1 All Stats'),'Không có gì xảy ra.','2,78');
INSERT INTO pve_enemies VALUES(26,'Lady Maria',7,8,5,7,8,9,0,'Nhận Power "Bloody Strike" và "Bloodlust".','Mất ngẫu nhiên 1 Power','2,78');
INSERT INTO pve_enemies VALUES(27,'Isshin the Sword Saint',7,8,7,8,9,7,0,'Nhận +1 all stats.','Không có gì xảy ra.','2,78');
INSERT INTO pve_enemies VALUES(28,'Tung Tung Tung Sahur',7,2,7,3,5,5,0,'Nhận +2 Strength và +1 Durability.','Nhận -1 IQ.','2,78');
INSERT INTO pve_enemies VALUES(29,'A Wild Werebeast',6,5,5,3,5,5,0,'Nhận Char Dev "Furry"','Không có gì xảy ra.','2,78');
INSERT INTO pve_enemies VALUES(30,'Odin, The All-Father',8,8,10,10,10,5,0,'Nhận ngẫu nhiên 2 Power.','Không có gì xảy ra.','2,78');
INSERT INTO pve_enemies VALUES(31,'Stellaron Hunter Kafka',6,6,6,8,8,8,'Đối thủ nhận -2 IQ và BIQ','Nhận Power Mind Control và Clear Mind','Không có gì xảy ra.','2,78');
INSERT INTO pve_enemies VALUES(32,'Hungry Hounds',7,6,4,2,4,4,0,'Nhận +1 Strength và +1 Martial Arts.','Nhận -1 Strength và -1 Martial Arts.','2,78');
INSERT INTO pve_enemies VALUES(33,'Cursed Mage',3,3,4,7,6,2,0,'Nhận +1 IQ.','Nhận -1 IQ.','2,78');
INSERT INTO pve_enemies VALUES(34,'Lothric Knight',6,4,5,3,5,4,0,'Nhận +1 Martial Arts','Nhận -1 Martial Arts','2,78');
INSERT INTO pve_enemies VALUES(35,'Mine-tide''s Son',4,4,5,3,5,9,0,'Nhận Power "Fist Fighting".','Nhận -1 Martial Arts.','2,78');
INSERT INTO pve_enemies VALUES(36,'Old Lineages of the Emirate',3,6,36,3,6,36,'Đối thủ bị -2 Speed và -2 BIQ',unistr('Nhận Char-Dev số 36\u000aNhận Archetype số 36'),'Không có gì xảy ra.','2,78');
INSERT INTO quirks VALUES(1,'Sợ Nắng',' Nhận -1 Dura','');
INSERT INTO quirks VALUES(2,'Sợ Chết','Sau khi combat, đối thủ bạn bị "Sợ Chết".','');
INSERT INTO quirks VALUES(3,'Fear the Powerless','Nếu bạn không có Power, bạn sẽ bị -1 All Stats.','');
INSERT INTO quirks VALUES(4,'Fearless','Trong combat: Khi đối đầu với Spirit và Demon, Nhận +1 vào BIQ','');
INSERT INTO quirks VALUES(5,'Anemic','Nhận -1 Strength.','');
INSERT INTO quirks VALUES(6,'High Finger Skill',unistr('Quay 1 player để làm "Lover"\u000aNhận +1 Speed.'),'');
INSERT INTO quirks VALUES(7,'Calm','Nhận +1 BIQ','');
INSERT INTO quirks VALUES(8,'Cay/Tri',unistr(' Nhận -1 IQ và -1 BIQ\u000aKhi thua trận, -1 IQ và -1 BIQ'),'');
INSERT INTO quirks VALUES(9,'Cute',unistr('Quay 1 player để làm "Lover". \u000aNhận +1 IQ'),'');
INSERT INTO quirks VALUES(10,'Hào Phóng','Cho đối thủ nhận +1 Điểm khi vào trận chiến. (Không kích Crit và Gambler hay "Ashina Skill")','');
INSERT INTO quirks VALUES(11,'Heavy Handed','Nhận +1 Str','');
INSERT INTO quirks VALUES(12,'Iron Stance','Nhận +1 Dura','');
INSERT INTO quirks VALUES(13,'Lurker',unistr('(1).Nhận +1 Speed\u000a(2).Nhận +1 Speed nếu có Archetype là "Spy"\u000a(3).Nhận +1 Speed nếu có Quirk là "Tracker"'),'');
INSERT INTO quirks VALUES(14,'Peacemaker','Khi đẩy tỉ số trận đấu đến Hòa phải quyết định bằng Tiebreak, nhận +1 All Stats sau trận đấu đó.','');
INSERT INTO quirks VALUES(15,'Nói nhiều',unistr('Lèm bà lèm bèm.\u000aNếu bạn có cả "Nói ít". Nhận Quirk "Tâm thần"'),'');
INSERT INTO quirks VALUES(16,'Nói ít',unistr('Nhận +1 Dura sau trận đấu với người "Nói nhiều"\u000aNếu bạn có cả "Nói nhiều". Nhận Quirk "Tâm thần"'),'');
INSERT INTO quirks VALUES(17,'Tâm Thần','Nhận -5 IQ, biến thành +5 IQ nếu có Archetype "Devotee"','');
INSERT INTO quirks VALUES(18,'Quan Trọng 1',unistr('Nhận +1 Str, +1 Spd\u000aNếu bạn đủ "Quan trọng", nhận thêm "Quote Nerd"'),'');
INSERT INTO quirks VALUES(19,'Quan Trọng 2',unistr('Nhận +1 IQ, +1 BIQ\u000aNếu bạn đủ "Quan trọng", nhận thêm "Quote Nerd"'),'');
INSERT INTO quirks VALUES(20,'Quan Trọng 3',unistr('Nhận +1 Dura, +1 MA\u000aNếu bạn đủ "Quan trọng", nhận thêm "Quote Nerd"'),'');
INSERT INTO quirks VALUES(21,'Quote Nerd','Với mỗi 5 điểm base IQ, nhận thêm 1 Power.','');
INSERT INTO quirks VALUES(22,'Ác Ý',unistr('(1).Trong combat: Đối thủ nhận -2 Dura trong trận đấu và nhận +2 IQ sau trận đấu.\u000a(2).Nếu đối thủ thua trận đấu và sắp sửa bị loại, họ nhận 1 gear "Văn Tế" rồi mới bị loại.'),'');
INSERT INTO quirks VALUES(23,'Focus','Nhận +1 IQ, +1 Dura','');
INSERT INTO quirks VALUES(24,'Grudgebearer','Khi xuống nhánh thua, Nhận +1 all stats','');
INSERT INTO quirks VALUES(25,'Weak-Kneed','Trong combat: Round chiến thắng đầu tiên sẽ không nhận được điểm.','');
INSERT INTO quirks VALUES(26,'Training Restricted','Nhận +1 all stats nhưng sẽ không có vòng đấu PvE.','');
INSERT INTO quirks VALUES(27,'Night owl','Bạn có 20% nhận -1 all Stat sau mỗi trận chiến.','');
INSERT INTO quirks VALUES(28,'Erudite','Nhận +3 IQ','');
INSERT INTO quirks VALUES(29,'Tracker',unistr('(1).Nhận +1 IQ\u000a(2).Nhận +1 IQ nếu có Archetype là "Spy"\u000a(3).Nhận +1 IQ nếu có Quirk là "Lurker"'),'');
INSERT INTO quirks VALUES(30,'Kleptomaniac','"Trộm" lấy 1 món Legacy Gear từ vòng quay (50%) hoặc player (50%).','');
INSERT INTO quirks VALUES(31,'Lazy','-1 Dura sau khi thắng trận.','');
INSERT INTO quirks VALUES(32,'Meta Gaming','3 Stat Cao nhất sẽ được +1, 3 Stat thấp nhất sẽ bị -1','');
INSERT INTO quirks VALUES(33,'Martyr','Khi bị loại, Quay 3 người chơi ngẫu nhiên để nhận +2 vào Stat thấp nhất.','');
INSERT INTO quirks VALUES(34,'Curmudgeon','Không thể nhận Gear hay Weapon, nhận 3 Power.','');
INSERT INTO quirks VALUES(35,'Fact Speaker','Khi thắng Round IQ, nhận +1 vào 2 stat bất kì sau trận đấu.','');
INSERT INTO quirks VALUES(36,'Thích ăn Rau ','Good 🍀','');
INSERT INTO quirks VALUES(37,'Không thích ăn Rau','Nhận -1 Str','');
INSERT INTO quirks VALUES(38,'Doomsayer','Đối thủ nhận -1 All stats trong trận đấu.','');
INSERT INTO quirks VALUES(39,'Trash Talk','Nếu BIQ của đối thủ dưới 4, nhận +5 vào IQ khi chiến đấu.','');
INSERT INTO quirks VALUES(40,'Fragile','Nhận -4 Dura','');
INSERT INTO quirks VALUES(41,'Raconteur','Trong combat: Round chiến thắng đầu tiên của bản thân sẽ không được nhận điểm mà khiến đối thủ bị -1 điểm.','');
INSERT INTO quirks VALUES(42,'Robust','Nhận +2 Str','');
INSERT INTO quirks VALUES(43,'Resilient','Nhận +2 Dura','');
INSERT INTO quirks VALUES(44,'Sanguine','Biến tất cả các Base Stat dưới 4 thành 4.','');
INSERT INTO quirks VALUES(45,'Steady','Nhận +2 MA','');
INSERT INTO quirks VALUES(46,'Unyielding','Khi thua round, Có 30% +1 vào Stat bất kì (Áp dụng sau Combat)','');
INSERT INTO quirks VALUES(47,'Soft','Trong combat: Khi thắng round, có 5% nhường lại điểm cho đối thủ.','');
INSERT INTO quirks VALUES(48,'Thực dụng','Khi thắng và loại 1 người chơi, lột hết Gear trên người họ để dùng.','');
INSERT INTO quirks VALUES(49,'Thích Liên Hoan Xác Thịt','80% Sẽ Make love với đối thủ sau trận đấu nếu thắng cuộc.','');
INSERT INTO quirks VALUES(50,'Vung tiền qua cửa','Sau khi thắng cuộc, vứt Normal Gear cũ trong người đi.','');
INSERT INTO quirks VALUES(51,'Nervous','Nhận +1 Speed, -1 BIQ','');
INSERT INTO quirks VALUES(52,'Bloodthirsty',unistr('Nhận +1 MA\u000aTrong combat: Mỗi Round thắng nhận thêm 1 điểm, Thua Round sẽ mất toàn bộ điểm đang có.'),'');
INSERT INTO quirks VALUES(53,'Relentless','Sau khi chiến thắng, Đối thủ sẽ bị -3 vào 1 stat ngẫu nhiên.','');
INSERT INTO quirks VALUES(54,'Tham ăn','Với mỗi 2 Base Dura, nhận -1 Speed','');
INSERT INTO quirks VALUES(55,'Beauty',unistr('Quay 1 player để làm "Lover". \u000aNhận +1 BIQ'),'');
INSERT INTO quirks VALUES(56,'Cruelty','Trong combat: Khi 1 round hòa, quyết định người nhận được 1 điểm bằng vòng quay 50/50 thay vì cả 2 không nhận được điểm.','');
INSERT INTO races VALUES(1,'Goblin','Goblin Horde','Không có ','6,5','');
INSERT INTO races VALUES(2,'Gnome','Không có ','Không có ','6,5','');
INSERT INTO races VALUES(3,'Human','Skin Color','Không có ','6,5','');
INSERT INTO races VALUES(4,'Dwarf','Dwarf''s Type','Không có ','6,5','');
INSERT INTO races VALUES(5,'Skeleton','Bone Lineage','Ở trong nhánh thua, nhận +4 Durability. ',5,'');
INSERT INTO races VALUES(6,'Troll','Troll''s Type','Không có ',5,'');
INSERT INTO races VALUES(7,'Orc','Không có ','Nhận +1 vào chỉ số thấp nhất khi thắng và -2 vào chỉ số cao nhất khi thua.',5,'');
INSERT INTO races VALUES(8,'Dryad','Không có ',unistr('Ở nhánh thắng. nhận +1 Durability sau mỗi trận.\u000aỞ nhánh thua, nhận -1 Durability sau mỗi trận.'),5,'');
INSERT INTO races VALUES(9,'Elf','Elf''s Type','Không có ',6,'');
INSERT INTO races VALUES(10,'Spirit','Không có ','Khi có bằng hoặc hơn 13 Spirit trong mùa, tất cả Spirit nhận +1 all stats. (Hiệu ứng này vẫn có hiệu lực ngay cả khi các spirit đó chết đi.)',5,'');
INSERT INTO races VALUES(11,'Uma','Uma Parents.','Người chơi thuộc về House "Tracen Academy" và không có vòng quay House.',6,'');
INSERT INTO races VALUES(12,'Werebeast','Beast''s Type','Không có ',5,'');
INSERT INTO races VALUES(13,'Vampire','Body Count','36% nhận vòng quay "Khẩu Vị Độc Đáo"',5,'');
INSERT INTO races VALUES(14,'Giant','Không có ',unistr('Nhận +5 IQ nếu sau vòng quay base stats IQ > Strength. (Và -5 Strength)\u000aNhận +5 Strength nếu sau vòng quay base stats Strength > IQ. (Và -5 IQ)\u000aNếu cả hai bằng nhau sau vòng quay base stats, nhận +3 Strength và IQ.'),5,'');
INSERT INTO races VALUES(15,'Dragon','Dragon''s Type','Không có ',5,'');
INSERT INTO races VALUES(16,'Angel','Angel Rank','Nhận Archetype "Pacifist" từ đầu (sẽ nhận thêm một Archetype nữa).',4,'');
INSERT INTO races VALUES(17,'Demi-God','God''s Gifts','Nhận +1 all stats khi đối đầu với Human và -1 all stats khi đối đầu với God.','3,5','');
INSERT INTO races VALUES(18,'Primordial Being','Elemental Wheel','Không có ','3,5','');
INSERT INTO races VALUES(19,'Demon','Sins Wheel','Không có ',3,'');
INSERT INTO races VALUES(20,'God','Which God? (12)','Không có ',3,'');
INSERT INTO Sub_race VALUES(1,1,'1 (Goblin)','Nhận Archetype "Him".',2);
INSERT INTO Sub_race VALUES(2,1,'36 (Goblin)','Nhận -1 All Stats',20);
INSERT INTO Sub_race VALUES(3,1,'1001 (Goblin)','Bro là 1 con Goblin ',40);
INSERT INTO Sub_race VALUES(4,1,'5000 (Goblin)','Nhận 1 Gear',20);
INSERT INTO Sub_race VALUES(5,1,'10000 (Goblin)','Nhận +1 Strength, +1 Durability và +1 Martial Arts.',10);
INSERT INTO Sub_race VALUES(6,1,'50000 (Goblin)','Nhận +2 Strength, +2 Durability và +1 Martial Arts',5);
INSERT INTO Sub_race VALUES(7,1,'50000+ (Goblin)','Nhận +1 all stats',3);
INSERT INTO Sub_race VALUES(8,3,'Trắng','Nhận -1 IQ, +1 BIQ',20);
INSERT INTO Sub_race VALUES(9,3,'Vàng ','Nhận +1 IQ.',40);
INSERT INTO Sub_race VALUES(10,3,'Đen','Nhận +1 Dura',40);
INSERT INTO Sub_race VALUES(11,4,'Lùn núi (Mountain)','Nhận +2 Strength.',25);
INSERT INTO Sub_race VALUES(12,4,'Lùn xám (Gray)','Nhận +2 Speed và +1 Durability.',20);
INSERT INTO Sub_race VALUES(13,4,'Cổ Lùn (Ancient)','Chắc chắn sử dụng được vũ khí đang có.',15);
INSERT INTO Sub_race VALUES(14,4,'Lùn thường','Chả có mẹ gì',40);
INSERT INTO Sub_race VALUES(15,5,'Goblin (Skeleton)','','6,5');
INSERT INTO Sub_race VALUES(16,5,'Gnome (Skeleton)','','6,5');
INSERT INTO Sub_race VALUES(17,5,'Human (Skeleton)','','6,5');
INSERT INTO Sub_race VALUES(18,5,'Dwarf (Skeleton)','','6,5');
INSERT INTO Sub_race VALUES(19,5,'Skeleton (Skeleton)','',5);
INSERT INTO Sub_race VALUES(20,5,'Troll (Skeleton)','',5);
INSERT INTO Sub_race VALUES(21,5,'Orc (Skeleton)','',5);
INSERT INTO Sub_race VALUES(22,5,'Dryad (Skeleton)','',5);
INSERT INTO Sub_race VALUES(23,5,'Elf (Skeleton)','',6);
INSERT INTO Sub_race VALUES(24,5,'Spirit (Skeleton)','',5);
INSERT INTO Sub_race VALUES(25,5,'Uma (Skeleton)','',6);
INSERT INTO Sub_race VALUES(26,5,'Werebeast (Skeleton)','',5);
INSERT INTO Sub_race VALUES(27,5,'Vampire (Skeleton)','',5);
INSERT INTO Sub_race VALUES(28,5,'Giant (Skeleton)','',5);
INSERT INTO Sub_race VALUES(29,5,'Dragon (Skeleton)','',5);
INSERT INTO Sub_race VALUES(30,5,'Angel (Skeleton)','',4);
INSERT INTO Sub_race VALUES(31,5,'Demi-God (Skeleton)','','3,5');
INSERT INTO Sub_race VALUES(32,5,'Primordial Being (Skeleton)','','3,5');
INSERT INTO Sub_race VALUES(33,5,'Demon (Skeleton)','',3);
INSERT INTO Sub_race VALUES(34,5,'God (Skeleton)','',3);
INSERT INTO Sub_race VALUES(35,6,'Regular Troll','Một con Troll thường ',42);
INSERT INTO Sub_race VALUES(36,6,'Ice Troll','Trong combat: Đối thủ -1 Spd',30);
INSERT INTO Sub_race VALUES(37,6,'Mountain Troll','Nhận +1 Dura',25);
INSERT INTO Sub_race VALUES(38,6,'Lich Troll','Nhận 1 Power của player đã chết sau mỗi trận đấu.',3);
INSERT INTO Sub_race VALUES(39,9,'High Elf','Nhận +2 Base IQ.',9);
INSERT INTO Sub_race VALUES(40,9,'Dark Elf','Nhận +2 Base BIQ.',8);
INSERT INTO Sub_race VALUES(41,9,'Wood Elf','Nhận 1 random Power và +1 BIQ',20);
INSERT INTO Sub_race VALUES(42,9,'Sea Elf','Nhận 1 random Power và +1 Dura',14);
INSERT INTO Sub_race VALUES(43,9,'Moon Elf','Nhận 1 random Power và Quay 1 "Lover"',14);
INSERT INTO Sub_race VALUES(44,9,'Sun Elf','Nhận 1 random Power và +1 MA',14);
INSERT INTO Sub_race VALUES(45,9,'Star Elf','Nhận 1 random Power và +1 Speed',14);
INSERT INTO Sub_race VALUES(46,9,'Lythari','Nhận +3 Base Speed và Quirk "Raconteur"',7);
INSERT INTO Sub_race VALUES(47,11,'Maruzensky','Nhận Power "Red Shift/LP1211-M".',4);
INSERT INTO Sub_race VALUES(48,11,'Mejiro Ryan','Nhận Power "Let''s Pump Some Iron!"',4);
INSERT INTO Sub_race VALUES(49,11,'Taiki Shuttle','Nhận Power "Shooting for Victory".',4);
INSERT INTO Sub_race VALUES(50,11,'Haru Urara','Nhận -2 all stats, nếu còn sống tới vòng 32 người, chuyển thành nhận +2 all stats.',4);
INSERT INTO Sub_race VALUES(51,11,'Oguri Cap','Nhận +1 Strength và +2 Speed.',6);
INSERT INTO Sub_race VALUES(52,11,'Gold Ship','Nhận Quirk "Traning Restricted", mỗi khi bắt đầu combat, có 50% nhận +1 all stats và 50% nhận -1 all stats. (Chỉ áp dụng trong combat đó)',6);
INSERT INTO Sub_race VALUES(53,11,'Symboli Rudolf','Sau khi bạn thắng 3 trận PvP đầu tiên, nhận +1 all stats.',6);
INSERT INTO Sub_race VALUES(54,11,'Silence Suzuka','Nhận +3 Speed.',6);
INSERT INTO Sub_race VALUES(55,11,'Mejiro McQueen','Nhận +3 Durability.',6);
INSERT INTO Sub_race VALUES(56,11,'Mihono Bourbon','Nhận +1 Strength và +2 Durability.',6);
INSERT INTO Sub_race VALUES(57,11,'Tokai Teio','Gấp đôi chỉ số Speed Base khi bạn sử dụng nhạc cụ làm vũ khí.',6);
INSERT INTO Sub_race VALUES(58,11,'Agnes Tachyon','Nhận Power "U=ma2"',6);
INSERT INTO Sub_race VALUES(59,11,'Nice Nature','Nếu cả hai bên đều có 3 điểm combat khi kết thúc giao tranh, bỏ qua Tie-Break và giành chiến thắng. (Hiệu ứng này mạnh hơn tất cả các hiệu ứng tie-breaker khác)',6);
INSERT INTO Sub_race VALUES(60,11,'Special Week','50% nhận Power "Gourmand" và 50% nhận Power "Hydrate".',6);
INSERT INTO Sub_race VALUES(61,11,'Rice Shower','Nhận +1 all stats ở nhánh thua, hiệu ứng này hết hiệu lực khi tới chung kết.',6);
INSERT INTO Sub_race VALUES(62,11,'Mayano Top Gun','Nhận +2 Durability và +1 BIQ.',6);
INSERT INTO Sub_race VALUES(63,11,'Biwa Hayahide','Nhận +2 IQ và +1 BIQ.',6);
INSERT INTO Sub_race VALUES(64,11,'El Condor Pasa','Nếu bạn có trên 7 điểm Durability, nhận +1 vào các chỉ số còn lại.',6);
INSERT INTO Sub_race VALUES(65,12,'Wereraven','Nhận +1 Base Speed và +1 Base BIQ.',12);
INSERT INTO Sub_race VALUES(66,12,'Werewolf','Nhận +1 Base Strength và +1 Base Martial Arts.',12);
INSERT INTO Sub_race VALUES(67,12,'Wererat','Nhận power "Crimson Poison".',12);
INSERT INTO Sub_race VALUES(68,12,'Wereboar','Nhận Quirk "Relentless"',12);
INSERT INTO Sub_race VALUES(69,12,'Werebear','Nhận +1 Base Strength, +1 Base Dura',12);
INSERT INTO Sub_race VALUES(70,12,'Werebat','Nhận Power "Bloody Strike"',12);
INSERT INTO Sub_race VALUES(71,12,'Werecapybara','Nhận Quirk "Cute"',12);
INSERT INTO Sub_race VALUES(72,12,'Weresheep','Nhận 1 Power',8);
INSERT INTO Sub_race VALUES(73,12,'Wereseal','Nhận 1 Char Dev',8);
INSERT INTO Sub_race VALUES(74,13,'1-2 (Vampire)','Nhận -1 all stats','2,5');
INSERT INTO Sub_race VALUES(75,13,'10+ (Vampire)','Mới nhú',5);
INSERT INTO Sub_race VALUES(76,13,'50+ (Vampire)','Nhóc',20);
INSERT INTO Sub_race VALUES(77,13,'500+ (Vampire)','Nhận +1 Speed, +1 IQ',25);
INSERT INTO Sub_race VALUES(78,13,'2000+ (Vampire)','Nhận +1 Speed, +1 IQ, +1 BIQ',25);
INSERT INTO Sub_race VALUES(79,13,'10000+ (Vampire)','Nhận +1 Speed, +1 IQ, +1 BIQ, +1 Dura',20);
INSERT INTO Sub_race VALUES(80,13,'50000+ (Vampire)','Nhận +1 all stats','2,5');
INSERT INTO Sub_race VALUES(81,15,'Crimson Dragon',' Nhận +1 Base IQ và +1 Base Durability.',9);
INSERT INTO Sub_race VALUES(82,15,'Stone Dragon','Nhận +2 Base Durability ',9);
INSERT INTO Sub_race VALUES(83,15,'Amethyst Dragon','Nhận -2 All Stats, nhận 5 Power',9);
INSERT INTO Sub_race VALUES(84,15,'Ancient Dragon','Nhận Power "Divine Smite"',9);
INSERT INTO Sub_race VALUES(85,15,'Undead Dragon','Nhận 1 Summon và +1 Dura',9);
INSERT INTO Sub_race VALUES(86,15,'Zephyrian Dragon','Nhận 1 Power và 1 Quirk',9);
INSERT INTO Sub_race VALUES(87,15,'Tideborn Dragon','Nhận +2 Strength',9);
INSERT INTO Sub_race VALUES(88,15,'Thunder Dragon','Nhận Power "Thunder Orb"',10);
INSERT INTO Sub_race VALUES(89,15,'Flame Dragon','Nhận 1 Power và +1 vào Stat thấp nhất',12);
INSERT INTO Sub_race VALUES(90,15,'Ice Dragon','Nhận +1 Char Dev và +1 vào Stat thấp nhất',10);
INSERT INTO Sub_race VALUES(91,15,'Chaos Dragon','Nhận 3 Quirk',5);
INSERT INTO Sub_race VALUES(92,16,'Angels','Không có gì đặc biệt ',49);
INSERT INTO Sub_race VALUES(93,16,'Archangels','Nhận +1 Speed và +1 Martial Arts.',18);
INSERT INTO Sub_race VALUES(94,16,'Principalities','Sau mỗi combat, +2 Vào stat thấp nhất.',8);
INSERT INTO Sub_race VALUES(95,16,'Powers','Nhận Archetype "Paladin", +1 MA',7);
INSERT INTO Sub_race VALUES(96,16,'Virtues','3 Stat cao nhất của bạn sẽ không thể bị Debuff',6);
INSERT INTO Sub_race VALUES(97,16,'Dominions','Nhận 2 Power.',5);
INSERT INTO Sub_race VALUES(98,16,'Ophanim','Nhận +1 all stats.',4);
INSERT INTO Sub_race VALUES(99,16,'Cherubim','Nhận +2 all stats.',3);
INSERT INTO Sub_race VALUES(100,17,'Cursed Sword','-1 All Stat',30);
INSERT INTO Sub_race VALUES(101,17,'War','Nhận +2 Strength',7);
INSERT INTO Sub_race VALUES(102,17,'Love','Nhận Quirk "Beauty"',7);
INSERT INTO Sub_race VALUES(103,17,'Time','Nhận +2 Spd',7);
INSERT INTO Sub_race VALUES(104,17,'Fortune','Giàu',7);
INSERT INTO Sub_race VALUES(105,17,'Secret Evil','Nhận +1 Stat cao nhất và thấp nhất khi chiến đấu',7);
INSERT INTO Sub_race VALUES(106,17,'Knowledge','Nhận +2 IQ',7);
INSERT INTO Sub_race VALUES(107,17,'Arts and Magic','Nhận 1 Power và +1 IQ',7);
INSERT INTO Sub_race VALUES(108,17,'Wilderness and Sea','Nhận 1 lần Summon Wheel',7);
INSERT INTO Sub_race VALUES(109,17,'Creation','Nhận 1 Creator''s Favor ',7);
INSERT INTO Sub_race VALUES(110,17,'Moon','Nhận Archetype "Pacifist" từ đầu (sẽ nhận thêm một Archetype nữa).',7);
INSERT INTO Sub_race VALUES(111,18,'Air','Nhận Power "Blowing Leaves", Nhận +2 Speed',25);
INSERT INTO Sub_race VALUES(112,18,'Water','Nhận Power "Water Breathing", Nhận +2 BIQ',25);
INSERT INTO Sub_race VALUES(113,18,'Fire','Nhận Power "Fire Control", Nhận +2 MA',25);
INSERT INTO Sub_race VALUES(114,18,'Earth','Nhận Power "Earth-Shaking", Nhận +2 Str',25);
INSERT INTO Sub_race VALUES(115,19,'Lucifer','Nhận -2 Stat cao nhất khi thắng',14);
INSERT INTO Sub_race VALUES(116,19,'Beelzebub','Nhận Quirk "Tham Ăn" và -2 Speed',14);
INSERT INTO Sub_race VALUES(117,19,'Leviathan','Quay 1 "Gia tộc" -1 All Stats sau khi combat với người đến từ "Gia tộc" đó.',14);
INSERT INTO Sub_race VALUES(118,19,'Behemoth','Nhận Quirk "Cay/Tri" và -2 IQ',14);
INSERT INTO Sub_race VALUES(119,19,'Mammon','Nhận Archetype "Gambler Bloodline".',14);
INSERT INTO Sub_race VALUES(120,19,'Belphegor','Nhận Quirk "Lazy" và -2 Dura',14);
INSERT INTO Sub_race VALUES(121,19,'Asmodeus',unistr('(1).Nhận Quirk "High Finger Skill", "Cute", "Beauty",  "Thích Liên Hoan Xác Thịt" và Quay thêm 1 "Lover" \u000a(2).Với mỗi "Lover", nhận -1 Dura và -1 BIQ'),14);
INSERT INTO Sub_race VALUES(122,19,'Sinful King','Cả 7 tội lỗi ập vào người',2);
INSERT INTO Sub_race VALUES(123,20,'Zeus',unistr('Nhận 3 random Power.\u000aSau mỗi combat, nhận char dev "Make Love".'),'11,11');
INSERT INTO Sub_race VALUES(124,20,'Hera',unistr('(1).Trong combat: Nhận +2 all stats nếu đối thủ thuộc race mà Zeus đã "Make Love". \u000a(2).Khi giải đấu còn dưới hoặc bằng 32 người, nếu Zeus không xuất hiện trong mùa hoặc đã chết, nhận char dev "No more family".'),'11,11');
INSERT INTO Sub_race VALUES(125,20,'Poseidon','Nhận 2 random Power và +2 Speed.','11,11');
INSERT INTO Sub_race VALUES(126,20,'Demeter','Nhận 3 random Power và 1 Char Dev.','11,11');
INSERT INTO Sub_race VALUES(127,20,'Apollo','Nhận Power "Divine Smite" và "Healing Factor".','11,11');
INSERT INTO Sub_race VALUES(128,20,'Artemis','Nhận Power "Hunter''s Rewards". ','11,11');
INSERT INTO Sub_race VALUES(129,20,'Ares','Nhận 2 random Power. Sau mỗi combat thắng, nhận 1 random Power.','11,11');
INSERT INTO Sub_race VALUES(130,20,'Athena','Nhận +3 IQ và +4 BIQ.','11,11');
INSERT INTO Sub_race VALUES(131,20,'Hephaestus',unistr('(1).Chắc chắn dùng được vũ khí\u000a(2).Chắc chắn có Unique Weapon ở Vòng Quay Weapon, nếu không còn bất kì Unique weapon nào, nhận +2 all stats và nhận 1 random Normal Weapon.'),'11,11');
INSERT INTO Sub_race VALUES(132,20,'Aphrodite',' Sau mỗi combat, Hút 2 điểm ở chỉ số cao nhất của đối phương.','11,11');
INSERT INTO Sub_race VALUES(133,20,'Hermes','Mặc định thắng Round Speed.','11,11');
INSERT INTO Sub_race VALUES(134,20,'Hestia','Nhận 1 Power. Sau mỗi combat (tính cả PvP và PvE), nhận thêm 1 Power và +1 Stat bất kì.','11,11');
INSERT INTO weapons VALUES(1,'Banana Peel','Physical',0,unistr('Trong Combat:\u000aNhận -1 all stats nếu có IQ thấp hơn đối phương.\u000aNhận +1 all stats nếu có IQ cao hơn đối phương.'),100,'');
INSERT INTO weapons VALUES(2,'Broken Straight Sword','Physical',0,'Nhận -1 all stats.',50,'');
INSERT INTO weapons VALUES(3,'Ukulele','Physical/Magic',0,'Đối thủ nhận -1 IQ và -1 BIQ.',75,'');
INSERT INTO weapons VALUES(4,'Uchigatana','Physical',0,'Nhận +2 BIQ và +1 Martial Arts.',85,'');
INSERT INTO weapons VALUES(5,'Kunai','Physical',0,'Nhận +2 Speed.',99,'');
INSERT INTO weapons VALUES(6,'Drums','Physical/Magic',0,'Sau mỗi trận thắng PvP, nhận thêm 1 "phần thưởng combat".',33,'');
INSERT INTO weapons VALUES(7,'Magical Staff','Magic',0,'Nhận +3 IQ.',66,'');
INSERT INTO weapons VALUES(8,'Glass Bottle','Physical',0,'Nhận +2 all stats, sau 1 combat sẽ loại bỏ vũ khí này khỏi người chơi.',15,'');
INSERT INTO weapons VALUES(9,'Wooden Sword','Physical',0,'Nhận +1 Strength.',100,'');
INSERT INTO weapons VALUES(10,'Cursed Pennywort','Physical/Magic',0,'Mỗi lần thi đấu PvP có 36% khả năng vô hiệu hóa 3 power ngẫu nhiên của kẻ địch.',36,'');
INSERT INTO weapons VALUES(11,'Slingshot','Physical',0,'Nhận +1 Strength và +1 BIQ.',70,'');
INSERT INTO weapons VALUES(12,'B.F Sword','Physical',0,'Nhận +3 Strength.',66,'');
INSERT INTO weapons VALUES(13,'Long Bow','Physical',0,'Nhận +2 BIQ.',90,'');
INSERT INTO weapons VALUES(14,'Hidden Blade','Physical',0,unistr('Nhận +1 Speed và Power "Critical Strike".\u000aNếu có Archetype "Assassins", chắc chắn sử dụng được vũ khí này.'),55,'');
INSERT INTO weapons VALUES(15,'Summoning Scroll','Magic',0,unistr('Trong Combat: triệu hồi 1 Summon tạm thời từ "Summon Wheel". \u000aSummon đấy biến mất sau trận đấu'),60,'');
INSERT INTO weapons VALUES(16,'Nunchuck','Physical',0,'Nhận +3 Martial Arts.',66,'');
INSERT INTO weapons VALUES(17,'Grimoire','Magic',0,'Nhận +1 IQ.',100,'');
INSERT INTO weapons VALUES(18,'Whip','Physical',0,unistr('Nhận +1 Speed và +1 MA.\u000aLuôn sử dụng được nếu người dùng thuộc nhà "Hoslow"'),40,'');
INSERT INTO weapons VALUES(19,'Halberd','Physical',0,unistr('(1).Nếu có trên 7 Strength, tăng tỉ lệ dùng được vũ khí này lên thêm 25%\u000a(2).Khi thắng round Str, nhận +1 BIQ, +1MA (Áp dụng sau Combat)'),60,'');
INSERT INTO weapons VALUES(20,'Saxophone','Physical',0,'Nhận +1 IQ và +1 BIQ.',60,'');
INSERT INTO weapons VALUES(21,'Infinity Edge','Physical',1,unistr('(1).Nhận +2 Strength và Power "Critical Strike".\u000a(2).Mỗi khi Crit, nhận thêm 1 điểm.'),66,'');
INSERT INTO weapons VALUES(22,'Blade of Chaos','Physical',1,unistr('(1).Nhận +3 Strength và +3 Martial Arts, \u000a(2).Trong Combat: Gấp đôi 2 chỉ số nhận thêm này nếu đối thủ là "God."'),75,'');
INSERT INTO weapons VALUES(23,'River of Blood','Physical',1,'Nhận +2 Speed, +2 BIQ và +1 Martial Arts.',80,'');
INSERT INTO weapons VALUES(24,'Staff of Moses','Magic',1,'Sau mỗi combat, nhận 1 power ngẫu nhiên.',70,'');
INSERT INTO weapons VALUES(25,'Staff of Homa','Physical',1,'Nhận +1 all stats.',80,'');
INSERT INTO weapons VALUES(26,'Frostmourne','Physical/Magic',1,'Sau mỗi combat thắng, nhận +1 vào 1 stats ngẫu nhiên và nhận thêm 1 power mà đối thủ có.',50,'');
INSERT INTO weapons VALUES(27,'Death''s Scythe','Magic',1,'Trong combat: đối thủ nhận -1 all stats.',65,'');
INSERT INTO weapons VALUES(28,'Excalibur','Physical',1,'Nhận +7 Strength.',70,'');
INSERT INTO weapons VALUES(29,'Yamato Blade','Physical',1,'Nhận +4 Speed và +2 Martial Arts.',80,'');
INSERT INTO weapons VALUES(30,'Moonlight Greatsword','Physical/Magic',1,'Nhận +3 Durability và +2 Martial Arts.',90,'');
INSERT INTO weapons VALUES(31,'Divine Rapier','Physical',1,unistr('(1).Nhận +2 all stats. \u000a(2).Khi thua trận người sở hữu sẽ mất vũ khí này.'),90,'');
INSERT INTO weapons VALUES(32,'Bloodthrist Dagger','Physical',1,'Nhận Power "Critical Strike" và tăng thêm 16% tỉ lệ crit.',72,'');
INSERT INTO weapons VALUES(33,'Ruyi Jingu Bang','Physical/Magic',1,'Ngay trước khi bắt đầu combat, nhận +1 all stats với mỗi 3 power sở hữu. Hiệu ứng này chỉ có hiệu lực trong combat đó.',72,'');
INSERT INTO weapons VALUES(34,'Playful Cloud','Physical',1,'Trong Combat: Bạn luôn chiến thắng vòng "Martial Arts".',80,'');
INSERT INTO weapons VALUES(35,'Necronomicon','Magic',1,'Nhận +3 IQ và 3 BIQ.',66,'');
INSERT INTO weapons VALUES(36,'Death''s Web Wand','Magic',1,'Sau mỗi combat, nhận +1 all stats và mất vĩnh viễn 1 Power.',90,'');
INSERT INTO weapons VALUES(37,'Forbidden Tome','Magic',1,'Sau mỗi combat chiến thắng, nhận ngẫu nhiên 1 "Forbidden Power".',88,'');
INSERT INTO weapons VALUES(38,'Shadow Killer','Physical',1,'Nhận +3 Speed và Power "Evasion".',90,'');
INSERT INTO weapons VALUES(39,'Great Highland Bagpipe','Physical/Magic',1,unistr('(1).Nhận +1 all stats. \u000a(2).Trong Combat: Nếu người sở hữu có nhiều power hơn đối thủ, nhận +1 all stats.'),77,'');
INSERT INTO weapons VALUES(40,'Yoriichi''s Black Nichirin','Physical',1,'Trong Combat: Bạn mặc định thắng tộc Demon.',100,'');
INSERT INTO weapons VALUES(41,'Sarastro''s Flute','Magic',1,'Trong Combat: Đối thủ nhận -1 all stats với mỗi 3 power mà họ có.',70,'');
INSERT INTO weapons VALUES(42,'Two Dragons Sword','Physical',1,'Nhận +2 Strength, +2 BIQ và 2 Power ngẫu nhiên.',80,'');
INSERT INTO weapons VALUES(43,'Lusat''s Glintstone Staff','Physical',1,unistr('(1).Nhận +4 IQ. \u000a(2).Sau combat mà bạn thắng round IQ, nhận 1 Power.'),90,'');
INSERT INTO weapons VALUES(44,'Instruments of the Sirens','Magic',1,unistr('(1).Trong Combat: Đối thủ nhận -1 all stats. \u000a(2).Sau mỗi trận combat, nhận +1 vào 1 chỉ số ngẫu nhiên.'),70,'');
INSERT INTO weapons VALUES(45,'Chastiefol','Physical',1,'Trong Combat: Nhận +2 cho bản thân vào 2 chỉ số thấp nhất của đối phương',88,'');
INSERT INTO weapons VALUES(46,'Desolator','Physical',1,'Trong Combat: Nhận +3 Strength, đối phương nhận -3 Durability.',70,'');
INSERT INTO weapons VALUES(47,'Diamond Sword','Physical',1,'Nhận +4 Strength và +1 Speed.',100,'');
INSERT INTO weapons VALUES(48,'Aghanim''s Scepter','Magic',1,unistr('Với mỗi hiệu ứng enchant trên vũ khí này, nhận +1 all stats. (Tối đa 2)\u000aNếu có đủ 2 enchantments, nhận ngẫu nhiên 2 Power.'),100,'');
INSERT INTO weapons VALUES(49,'Galeforce','Physical',1,'Round đầu tiên thua trong combat đối phương sẽ không nhận điểm và không thể kích hoạt các hiệu ứng (ví dụ: Crit)',80,'');
INSERT INTO weapons VALUES(50,'Battlefury','Physical',1,'Trong Combat: Khi thắng một Round và Round trước đó bạn cũng thắng, nhận thêm 1 điểm',88,'');
INSERT INTO weapons VALUES(51,'Dawnbreaker','Physical',1,'Sau mỗi combat, với mỗi 2 round chiến thắng, nhận +2 vào 1 chỉ số ngẫu nhiên.',95,'');
INSERT INTO weapons VALUES(52,'Moonveil','Physical/Magic',1,unistr('Nhận +1 điểm combat nếu chủ sở hữu có IQ cao hơn đối phương.\u000aNhận thêm +1 điểm combat nếu chủ sở hữu có nhiều Power hơn đối phương.'),100,'');
INSERT INTO weapons VALUES(53,'Misericorde','Physical',1,'Mỗi khi thua 1 round combat, có khả 10% khả năng chủ sở hữu nhận được điểm thay vì đối thủ.',90,'');
INSERT INTO weapons VALUES(54,'Andúril','Physical',1,unistr('Nhận Summon Wheel sau mỗi combat.\u000aKhi combat với Demon, +1 điểm khởi đầu với mỗi Summon hiện có.'),80,'');
INSERT INTO weapons VALUES(55,'Needle','Physical',1,unistr('Nhận +2 Speed.\u000aRound Speed và MA sẽ cho thêm 1 điểm nếu thắng.'),80,'');
INSERT INTO weapons VALUES(56,'12 đôi dép 🍀','Physical',1,unistr('(1). Khi thua combat, nhận +3 và +6 vào 2 stat bất kì.\u000a(2).Chuyển sang đối thủ sau trận chiến nếu thua combat. Trước đó, loại bỏ vũ khí hiện tại của đối thủ.'),100,'');
CREATE TABLE IF NOT EXISTS "gears" (
	"id"	INTEGER,
	"name"	VARCHAR(255) NOT NULL DEFAULT '',
	"effect"	VARCHAR(255) NOT NULL DEFAULT '',
	"type"	VARCHAR(255) NOT NULL DEFAULT '',
	"is_special"	TINYINT NOT NULL DEFAULT 0,
	"note"	TEXT NOT NULL DEFAULT '',
	"usage_percentage"	INTEGER NOT NULL DEFAULT '',
	PRIMARY KEY("id")
);
INSERT INTO gears VALUES(1,'Fishing Rod','Sau 1 trận PvE, nhận 1 PvP Reward.','Physical',0,'',80);
INSERT INTO gears VALUES(2,'Sổ tay','Khi thua IQ, nhận +1 IQ (Áp dụng sau combat)','Physical',0,'',80);
INSERT INTO gears VALUES(3,'Văn tế',unistr('Nhận -1 All Stats.\u000aKhi bạn bị loại mà có Văn Tế trong người, Re-spin lại stat cao nhất của một người còn sống ngẫu nhiên.'),'Physical/Magic',0,'',100);
INSERT INTO gears VALUES(4,'Silver Steed','Nhận +2 Speed.','Physical',0,'',100);
INSERT INTO gears VALUES(5,'Wooden Shield','Nhận +1 Durability.','Physical',0,'',99);
INSERT INTO gears VALUES(6,'Wizard Hat','Nhận +1 IQ.','Magic',0,'',70);
INSERT INTO gears VALUES(7,'Love Letter','Nếu bạn có "Lover", nhận +1 all stats, còn không thì vô dụng.','Physical/Magic',0,'',100);
INSERT INTO gears VALUES(8,'Holy Symbol','Khi combat với Demon, Vampire, Spirit, Orc, Skeleton và Goblin, đối thủ bị -1 all Stats.','Magic',0,'',60);
INSERT INTO gears VALUES(9,'Fingerthing','Nhận 1 Quirk.','Physical/Magic',0,'',90);
INSERT INTO gears VALUES(10,'Healing Flasks','Nhận +2 vào Stat thấp nhất khi ở nhánh thua','Physical/Magic',0,'',100);
INSERT INTO gears VALUES(11,'Leather Jacket','Nhận +2 Durability.','Physical',0,'',100);
INSERT INTO gears VALUES(12,'Baguette',unistr('Ngon\u000aNếu đủ bộ công cụ nấu ăn, nhận +1 all stats (12,13,14)'),'Physical',0,'',100);
INSERT INTO gears VALUES(13,'Frying Pan',unistr('Nấu\u000aNếu đủ bộ công cụ nấu ăn, nhận +1 all stats (12,13,14)'),'Physical',0,'',100);
INSERT INTO gears VALUES(14,'Spatula',unistr('Xào\u000aNếu đủ bộ công cụ nấu ăn, nhận +1 all stats (12,13,14)'),'Physical',0,'',100);
INSERT INTO gears VALUES(15,'Gold Pine Resin','Nhận +2 BIQ','Physical/Magic',0,'',80);
INSERT INTO gears VALUES(16,'Knight''s Armor','Nhận -2 Speed, +2 Dura và +1 Strength','Physical',0,'',90);
INSERT INTO gears VALUES(17,'Cursed Charm','Nhận -1 Speed','Magic',0,'',70);
INSERT INTO gears VALUES(18,'Goggles with Microscope',unistr('Sau mỗi lần nhận PvP Reward, so sánh giữa Quirk và Power và áp dụng hiệu ứng sau:\u000a(1). Nếu Quirk nhiều hơn Power, mất 1 Quirk ngẫu nhiên để nhận 1 Power ngẫu nhiên.\u000a(2). Nếu Power nhiều hơn Quirk, mất 1 Power ngẫu nhiên để nhận 1 Quirk ngẫu nhiên.\u000a(3). Nếu cả hai bằng nhau, mất đi "Goggles with Microscope"'),'Physical/Magic',0,'',80);
INSERT INTO gears VALUES(19,'Swift Boots','Nhận +1 Speed.','Physical',0,'',90);
INSERT INTO gears VALUES(20,'Kuro''s Charm','Nhận +1 All Stat, phá hủy sau trận thắng đầu tiên.','Physical/Magic',0,'',90);
INSERT INTO gears VALUES(21,'Buckler','Nhận +1 Strength, +1 Dura','Physical',0,'',99);
INSERT INTO gears VALUES(22,'Soap','Thơm','Physical',0,'',100);
INSERT INTO gears VALUES(23,'Magical Scroll','Nhận +1 IQ và +1 BIQ','Magic',0,'',80);
INSERT INTO gears VALUES(24,'Ba hoa trắng','Khi ở nhánh thua, -2 all Stats','Magic',0,'',90);
INSERT INTO gears VALUES(25,'Khung hình thờ',unistr('Khi thua trận, chuyển Gear này cho người thắng.\u000aVới mỗi "Khung hình thờ", nhận -1 vào stats cao nhất.'),'Magic',0,'',80);
INSERT INTO gears VALUES(26,'Xương sống lưỡi','Khi vào vòng 32 người, Mất đi "Xương sống lưỡi" để nhận 1 Power','Physical/Magic',0,'',90);
INSERT INTO gears VALUES(27,'Thuốc tráng dương','Nhận +2 Str và +2 Dura','Physical',0,'',70);
INSERT INTO gears VALUES(28,'Đồng tiền vàng.','Khi thua trận, mất đi "Đồng tiền vàng" để mua 1 Gear không phải "Đồng tiền vàng"','Physical',0,'',100);
INSERT INTO gears VALUES(29,'Cuộn khăn giấy',unistr('Nếu không có "Lover", nhận +1 Dura.\u000aNếu có "Lover", nhận +1 Speed'),'Physical',0,'',69);
INSERT INTO gears VALUES(30,'Academie Ring','Nhận +1 IQ','Magic',0,'',70);
INSERT INTO gears VALUES(31,'Dark Lanthorn','Phát sáng trong đêm tối','Physical/Magic',0,'',100);
INSERT INTO gears VALUES(32,'Lover''s Glover','Nhận 1 "Lover"','Physical',0,'',90);
INSERT INTO gears VALUES(33,'Storage Room Key','Creator tặng bạn 1 Gear khác.','Physical',0,'',100);
INSERT INTO gears VALUES(34,'Foreclosure Notice','Nếu đến vòng số 32 và bạn không kiếm đủ 8 điểm. Toàn bộ Gear và Weapon của bạn sẽ biến mất và nhận Char Dev "No More Home" và "No more Family".','Physical',0,'',100);
INSERT INTO gears VALUES(35,unistr('Cursed Coin\u000d'),'Trong Combat: Trước trận đấu, quay một vòng quay 50/50 gồm 2 player để xem ai sẽ là người bị -1 All Stats.','Physical/Magic',0,'',100);
INSERT INTO gears VALUES(36,unistr('Empty Stein\u000d'),'Một cái cốc rỗng.','Physical',0,'',100);
INSERT INTO gears VALUES(37,'The Ancient Ladder: A Journey to the Fullness of Sin with Demon',unistr('Gấp đôi hiệu ứng Sin nếu là Demon.\u000aNhận +1 MA, +1 IQ, +1 Speed'),'Physical/Magic',1,'',100);
INSERT INTO gears VALUES(38,'God of Love''s Cooking Recipe',unistr('Nhận ngẫu nhiên 1 Power của 1 người chơi đã bị loại khi vào vòng 64/16.\u000a-1 Dura với mỗi lần kích hoạt.'),'Magic',1,'',100);
INSERT INTO gears VALUES(39,'The Angel''s Finger Bone',unistr('Đảo ngược tất cả base stat.\u000aSau đó nhận +2 IQ và 1 Power.'),'Magic',1,'',100);
INSERT INTO gears VALUES(40,'The Tamer Straight Sword',unistr('Nhận 1 Summon.\u000aĐánh cắp 1 Power ngẫu nhiên của đối thủ sau khi chiến thắng đối thủ đó.'),'Physical/Magic',1,'',100);
INSERT INTO gears VALUES(41,'Soul Sucker','Đối thủ bị Re-spin Stat cao nhất sau trận đấu (Bất kể mình thắng hay thua)','Magic',1,'',100);
INSERT INTO gears VALUES(42,'Leaf that got Blowed',unistr('Nhận Power "Blowing Leaves".\u000aKháng tất cả các loại debuff giảm chỉ số từ đối phương.'),'Physical/Magic',1,'',100);
INSERT INTO gears VALUES(43,'Dart for the Dwarf Heir','Đối thủ bị -1 all stats và thêm -1 vào Stat cao nhất khi vào trận.','Physical',1,'',100);
INSERT INTO gears VALUES(44,'King Gnome''s Banana',unistr('Nhận -2 all stats nếu có IQ thấp hơn đối phương.\u000aNhận +2 all stats nếu có IQ cao hơn đối phương.'),'Physical',1,'',100);
INSERT INTO gears VALUES(45,'Human NPC''s Axe',unistr('Nhận 1 Power.\u000aNhận +1 vào stat cao nhất.\u000aNhận +2 all stat khi bạn là NPC'),'Physical',1,'',100);
INSERT INTO gears VALUES(46,'Ragnarok''s Cobra','Người sở hữu con rắn này giết 1 vị thần ngẫu nhiên sau khi quay đủ player và tính đó là 1 trận thắng, sau đó tự động thua ở vòng 64 (1 lần)','Physical/Magic',1,'',100);
INSERT INTO gears VALUES(47,'God of War''s Entry Ticket',unistr('Biến Base Strength thành 10.\u000a"Make love" với 1 tộc.\u000aNhận +2 stat thấp nhất khi đối đầu với Demi God/God.'),'Physical',1,'',100);
INSERT INTO gears VALUES(48,'The First Dragon Scale',unistr('Nhận +4 vào Stat thấp nhất.\u000a+1 all Stat khi đối đầu với chủng tộc thấp kém hơn.'),'Physical',1,'',100);
INSERT INTO gears VALUES(49,'Artist''s Easel',unistr('Bạn có thêm Power"Artist"\u000aNhận thêm 1 Power và 1 Quirk.'),'Magic',1,'',100);
INSERT INTO gears VALUES(50,'Writer''s Quill',unistr('Bạn có thêm Power "Writer"\u000aNhận thêm 1 Char Dev, 1 Archetype'),'Magic',1,'',100);
INSERT INTO gears VALUES(51,'IT''s Abacus',unistr('Base Stat lẻ của bạn sẽ được +1, rồi cộng toàn bộ Base Stat lại, chia 6 và sau đó biến tất cả Base Stats của bạn thành kết quả đó. Làm tròn theo quy ước, 0.5 sẽ làm tròn lên. \u000aChỉ xảy ra 1 lần ngay sau khi nhận.'),'Magic',1,'',100);
INSERT INTO gears VALUES(52,'Creator''s Cat Ring','Nhận Creator''s Favor 1-3 lần.','Magic',1,'',100);
INSERT INTO gears VALUES(53,'The Dice of the Dead','Nhận Archetype "Gambler". Mặc định thắng tất cả các trận đấu khi đối đầu với những người chơi có Archetype này. (Hiệu ứng này yếu hơn tất cả các hiệu ứng tự động thắng khác).','Magic',1,'',100);
INSERT INTO gears VALUES(54,'Brain of the Rot',unistr('Nhận các Power sau đây: \u000a+ Water Breathing\u000a+ Rickrolling\u000a+ Hand Washing\u000a+ Mewing\u000a+ The Goat\u000a+ Blowing Leaves\u000a+ Capybara\u000a+ Night Vision\u000a+ Gotta go Fast\u000a+ Tick-tock\u000a+ Fragrant\u000a+ Ballet Dancing\u000a+ Baldening\u000a+ Cold Breeze\u000a+ Hydrate\u000a+ The Coast is Clear!'),'Magic',1,'',100);
INSERT INTO gears VALUES(55,'Wooden Sword of the Mighty Goblin','Đảo ngược tất cả base stat và dẫn dắt một bầy 1001 con Goblin','Magic',1,'',100);
INSERT INTO gears VALUES(56,'Heart of the Shaggy Void','Đi tìm 1 "Lover", Biến Base Stat cao nhất và thấp nhất thành 3 sau đó nhận +1 All Stats','Magic',1,'',100);
INSERT INTO gears VALUES(57,'Spirit of the Wheel',unistr('Trận đầu tiên của bạn khi biết kết quả sẽ khiến 3 người ngẫu nhiên "Isekai", 2 trận tiếp theo của bạn sẽ thua.\u000a"Người ta đã đồn, Linh hồn của Vòng Quay không bao giờ hứng thú với chiến thắng, nó muốn tìm ra người nắm lấy Vinh Kwan"'),'Magic',1,'',100);
INSERT INTO gears VALUES(58,'Pebbles of the Stoic Demon','Khi đối đầu với "Human", nhận -1 all Stat sau khi kết thúc trận đấu (Áp dụng sau Combat.)','Magic',1,'',100);
CREATE TABLE IF NOT EXISTS "players_power" (
	"player_id"	INTEGER NOT NULL,
	"power_id"	INTEGER NOT NULL,
	PRIMARY KEY("player_id","power_id")
);
INSERT INTO players_power VALUES(1,14);
INSERT INTO players_power VALUES(2,69);
INSERT INTO players_power VALUES(2,95);
INSERT INTO players_power VALUES(2,40);
INSERT INTO players_power VALUES(2,96);
INSERT INTO players_power VALUES(2,48);
INSERT INTO players_power VALUES(2,10);
INSERT INTO players_power VALUES(2,79);
INSERT INTO players_power VALUES(2,14);
INSERT INTO players_power VALUES(2,11);
INSERT INTO players_power VALUES(3,1);
INSERT INTO players_power VALUES(3,18);
INSERT INTO players_power VALUES(4,52);
INSERT INTO players_power VALUES(4,33);
INSERT INTO players_power VALUES(5,67);
INSERT INTO players_power VALUES(5,30);
INSERT INTO players_power VALUES(5,11);
INSERT INTO players_power VALUES(6,107);
INSERT INTO players_power VALUES(6,97);
INSERT INTO players_power VALUES(6,80);
INSERT INTO players_power VALUES(7,31);
INSERT INTO players_power VALUES(7,114);
INSERT INTO players_power VALUES(7,2);
INSERT INTO players_power VALUES(7,11);
INSERT INTO players_power VALUES(9,92);
INSERT INTO players_power VALUES(9,61);
INSERT INTO players_power VALUES(10,3);
INSERT INTO players_power VALUES(10,50);
INSERT INTO players_power VALUES(10,46);
INSERT INTO players_power VALUES(10,71);
INSERT INTO players_power VALUES(10,9);
INSERT INTO players_power VALUES(10,59);
INSERT INTO players_power VALUES(11,10);
INSERT INTO players_power VALUES(11,40);
INSERT INTO players_power VALUES(11,57);
INSERT INTO players_power VALUES(11,84);
INSERT INTO players_power VALUES(12,5);
INSERT INTO players_power VALUES(12,4);
INSERT INTO players_power VALUES(12,21);
INSERT INTO players_power VALUES(13,109);
INSERT INTO players_power VALUES(13,14);
INSERT INTO players_power VALUES(13,32);
INSERT INTO players_power VALUES(13,34);
INSERT INTO players_power VALUES(13,39);
INSERT INTO players_power VALUES(13,47);
INSERT INTO players_power VALUES(13,53);
INSERT INTO players_power VALUES(13,60);
INSERT INTO players_power VALUES(13,66);
INSERT INTO players_power VALUES(13,68);
INSERT INTO players_power VALUES(13,72);
INSERT INTO players_power VALUES(13,82);
INSERT INTO players_power VALUES(13,87);
INSERT INTO players_power VALUES(13,91);
INSERT INTO players_power VALUES(13,92);
INSERT INTO players_power VALUES(13,105);
INSERT INTO players_power VALUES(13,67);
INSERT INTO players_power VALUES(13,71);
INSERT INTO players_power VALUES(14,55);
INSERT INTO players_power VALUES(14,87);
INSERT INTO players_power VALUES(15,57);
INSERT INTO players_power VALUES(15,42);
INSERT INTO players_power VALUES(15,75);
INSERT INTO players_power VALUES(15,66);
CREATE TABLE IF NOT EXISTS "players_quirks" (
	"player_id"	INTEGER NOT NULL,
	"quirk_id"	INTEGER NOT NULL,
	"is_usable"	INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY("player_id","quirk_id")
);
INSERT INTO players_quirks VALUES(1,7);
INSERT INTO players_quirks VALUES(2,24);
INSERT INTO players_quirks VALUES(3,26);
INSERT INTO players_quirks VALUES(3,50);
INSERT INTO players_quirks VALUES(4,25);
INSERT INTO players_quirks VALUES(4,26);
INSERT INTO players_quirks VALUES(5,41);
INSERT INTO players_quirks VALUES(6,56);
INSERT INTO players_quirks VALUES(7,13);
INSERT INTO players_quirks VALUES(7,24);
INSERT INTO players_quirks VALUES(8,19);
INSERT INTO players_quirks VALUES(9,6);
INSERT INTO players_quirks VALUES(10,56);
INSERT INTO players_quirks VALUES(11,36);
INSERT INTO players_quirks VALUES(11,44);
INSERT INTO players_quirks VALUES(12,25);
INSERT INTO players_quirks VALUES(12,30);
INSERT INTO players_quirks VALUES(13,22);
INSERT INTO players_quirks VALUES(13,46);
INSERT INTO players_quirks VALUES(14,13);
INSERT INTO players_quirks VALUES(14,16);
INSERT INTO players_quirks VALUES(14,35);
INSERT INTO players_quirks VALUES(14,51);
INSERT INTO players_quirks VALUES(15,1);
INSERT INTO players_quirks VALUES(15,11);
INSERT INTO players_quirks VALUES(15,49);
CREATE TABLE IF NOT EXISTS "players_gears" (
	"player_id"	INTEGER NOT NULL,
	"gear_id"	INTEGER NOT NULL,
	"is_usable"	INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY("player_id","gear_id")
);
INSERT INTO players_gears VALUES(1,22,1);
INSERT INTO players_gears VALUES(1,12,1);
INSERT INTO players_gears VALUES(1,26,1);
INSERT INTO players_gears VALUES(2,29,1);
INSERT INTO players_gears VALUES(2,4,1);
INSERT INTO players_gears VALUES(2,10,1);
INSERT INTO players_gears VALUES(2,19,1);
INSERT INTO players_gears VALUES(3,3,1);
INSERT INTO players_gears VALUES(3,17,1);
INSERT INTO players_gears VALUES(3,8,0);
INSERT INTO players_gears VALUES(3,29,1);
INSERT INTO players_gears VALUES(3,16,1);
INSERT INTO players_gears VALUES(3,49,1);
INSERT INTO players_gears VALUES(5,8,0);
INSERT INTO players_gears VALUES(5,28,1);
INSERT INTO players_gears VALUES(5,48,1);
INSERT INTO players_gears VALUES(6,6,1);
INSERT INTO players_gears VALUES(6,18,1);
INSERT INTO players_gears VALUES(6,58,1);
INSERT INTO players_gears VALUES(9,35,1);
INSERT INTO players_gears VALUES(9,27,1);
INSERT INTO players_gears VALUES(9,34,1);
INSERT INTO players_gears VALUES(9,19,1);
INSERT INTO players_gears VALUES(10,23,1);
INSERT INTO players_gears VALUES(11,5,1);
INSERT INTO players_gears VALUES(11,34,1);
INSERT INTO players_gears VALUES(11,3,1);
INSERT INTO players_gears VALUES(11,16,1);
INSERT INTO players_gears VALUES(12,1,0);
INSERT INTO players_gears VALUES(12,44,1);
INSERT INTO players_gears VALUES(12,55,1);
INSERT INTO players_gears VALUES(13,30,1);
INSERT INTO players_gears VALUES(13,10,1);
INSERT INTO players_gears VALUES(13,1,1);
INSERT INTO players_gears VALUES(13,54,1);
INSERT INTO players_gears VALUES(14,8,0);
INSERT INTO players_gears VALUES(14,36,1);
INSERT INTO players_gears VALUES(14,5,1);
CREATE TABLE IF NOT EXISTS "players_weapons" (
	"player_id"	INTEGER NOT NULL,
	"weapon_id"	INTEGER NOT NULL,
	"is_useable"	TINYINT NOT NULL DEFAULT 0,
	PRIMARY KEY("player_id","weapon_id")
);
INSERT INTO players_weapons VALUES(2,13,1);
INSERT INTO players_weapons VALUES(3,17,1);
INSERT INTO players_weapons VALUES(5,41,0);
INSERT INTO players_weapons VALUES(6,1,1);
INSERT INTO players_weapons VALUES(7,19,0);
INSERT INTO players_weapons VALUES(9,17,1);
INSERT INTO players_weapons VALUES(10,14,1);
INSERT INTO players_weapons VALUES(11,52,1);
INSERT INTO players_weapons VALUES(12,25,1);
INSERT INTO players_weapons VALUES(13,50,1);
INSERT INTO players_weapons VALUES(14,2,1);
INSERT INTO players_weapons VALUES(15,19,0);
CREATE TABLE IF NOT EXISTS "weapons_enchants" (
	"player_id"	INTEGER NOT NULL,
	"weapon_id"	INTEGER NOT NULL,
	"enchant_id"	INTEGER NOT NULL,
	PRIMARY KEY("weapon_id","enchant_id","player_id")
);
INSERT INTO weapons_enchants VALUES(2,1,'NULL');
INSERT INTO weapons_enchants VALUES(6,2,14);
INSERT INTO weapons_enchants VALUES(6,2,9);
INSERT INTO weapons_enchants VALUES(6,3,9);
INSERT INTO weapons_enchants VALUES(8,4,'NULL');
INSERT INTO weapons_enchants VALUES(9,5,13);
INSERT INTO weapons_enchants VALUES(9,5,1);
INSERT INTO weapons_enchants VALUES(10,6,'NULL');
INSERT INTO weapons_enchants VALUES(11,7,12);
INSERT INTO weapons_enchants VALUES(12,8,'NULL');
INSERT INTO weapons_enchants VALUES(13,9,8);
INSERT INTO weapons_enchants VALUES(13,9,9);
INSERT INTO weapons_enchants VALUES(14,10,14);
INSERT INTO weapons_enchants VALUES(15,11,'NULL');
INSERT INTO sqlite_sequence VALUES('archetypes',48);
INSERT INTO sqlite_sequence VALUES('char_dev',48);
INSERT INTO sqlite_sequence VALUES('enchants',21);
INSERT INTO sqlite_sequence VALUES('houses',16);
INSERT INTO sqlite_sequence VALUES('quirks',56);
INSERT INTO sqlite_sequence VALUES('powers',116);
INSERT INTO sqlite_sequence VALUES('races',21);
INSERT INTO sqlite_sequence VALUES('weapons',67);
INSERT INTO sqlite_sequence VALUES('pve_enemies',36);
INSERT INTO sqlite_sequence VALUES('Sub_race',139);
INSERT INTO sqlite_sequence VALUES('Players',18);
COMMIT;
