// ArchetypeConfig.ts
import { WheelStep } from "@/Common/Types/Types";

export const archetypeWheel: WheelStep = {
  key: "archetype",
  title: "Archetype",
  sections: [
    { id: "1", name: "Warrior of Sunlight", weight: 1.5, color: "#FFD700" },
    { id: "2", name: "Spy", weight: 2, color: "#AAAAAA" },
    { id: "3", name: "Knight of Gods", weight: 1.5, color: "#EEE8AA" },
    { id: "4", name: "Guardian of Demons", weight: 1.5, color: "#8B0000" },
    { id: "5", name: "NPC 💀", weight: 3.4, color: "#444444" },
    { id: "6", name: "Slayer", weight: 2.4, color: "#800000" },
    { id: "7", name: "Gigachad", weight: 2.4, color: "#00CED1" },
    { id: "8", name: "Dark Magician", weight: 1.3, color: "#4B0082" },
    { id: "9", name: "Bloodclan Berserker", weight: 1.3, color: "#B22222" },
    { id: "10", name: "Noble Swordsman", weight: 1.5, color: "#708090" },
    { id: "11", name: "Bard", weight: 2, color: "#DA70D6" },
    { id: "12", name: "Hero Grave Keeper", weight: 2, color: "#2E8B57" },
    { id: "13", name: "Dual Wielder", weight: 2, color: "#BC8F8F" },
    { id: "14", name: "Bookworm", weight: 2, color: "#8B4513" },
    { id: "15", name: "Gambler", weight: 2, color: "#FFDAB9" },
    { id: "16", name: "Pacifist", weight: 2, color: "#98FB98" },
    { id: "17", name: "Anti-Social", weight: 2, color: "#696969" },
    {
      id: "18",
      name: "Follower of the Two Fingers",
      weight: 1.8,
      color: "#D2B48C",
    },
    { id: "19", name: "Devotee", weight: 2, color: "#800080" },
    { id: "20", name: "Atheist", weight: 2, color: "#C0C0C0" },
    { id: "21", name: "X", weight: 0.3, color: "#000000" },
    { id: "22", name: "Glass Cannon", weight: 2, color: "#FF6347" },
    { id: "23", name: "Mid", weight: 2, color: "#4682B4" },
    { id: "24", name: "Time Traveller", weight: 2, color: "#00BFFF" },
    { id: "25", name: "Zealot", weight: 2, color: "#DC143C" },
    { id: "26", name: "Hand Fighter", weight: 2, color: "#A0522D" },
    { id: "27", name: "Lancer", weight: 2, color: "#B8860B" },
    { id: "28", name: "Assassins", weight: 2, color: "#2F4F4F" },
    { id: "29", name: "Conquerer", weight: 2, color: "#CD5C5C" },
    { id: "30", name: "Trickster", weight: 2, color: "#FF4500" },
    { id: "31", name: "Paladin", weight: 2, color: "#DAA520" },
    { id: "32", name: "Summoner", weight: 2, color: "#9370DB" },
    { id: "33", name: "Him", weight: 1, color: "#1E90FF" },
    { id: "34", name: "Wibu", weight: 1, color: "#FF69B4" },
    { id: "35", name: "Perfectionist", weight: 2, color: "#00FF7F" },
    { id: "36", name: "Hero of the Emirate", weight: 3.6, color: "#FFD700" },
    { id: "37", name: "Edgelord", weight: 2, color: "#483D8B" },
    { id: "38", name: "Fisher", weight: 3, color: "#4682B4" },
    { id: "39", name: "House's Noble", weight: 2, color: "#BDB76B" },
    { id: "40", name: "Farmer", weight: 3, color: "#228B22" },
    { id: "41", name: "Loser", weight: 2, color: "#A9A9A9" },
    { id: "42", name: "Blacksmith", weight: 3, color: "#708090" },
    { id: "43", name: "Hunter", weight: 3, color: "#6B8E23" },
    { id: "44", name: "Thief", weight: 3, color: "#8B0000" },
    { id: "45", name: "Gambler Bloodline", weight: 1.5, color: "#8B008B" },
    { id: "46", name: "Linh Mục", weight: 3, color: "#F5DEB3" },
    { id: "47", name: "Cha Xứ", weight: 3, color: "#EEE8AA" },
    { id: "48", name: "Quỷ Nhà Thờ", weight: 3, color: "#800000" },
  ],
};
    