import { WheelStep } from "../Types/Types";

export const charDevWheel: WheelStep = {
  key: "char-dev",
  title: "Char Dev",
  sections: [
    {
      id: "01",
      name: "Armed to the Teeth",
      weight: 1.7,
      color: "#D4AF37",
      description: "Nhận 3 Normal Gear ngẫu nhiên.",
    },
    {
      id: "02",
      name: "Training Arc",
      weight: 2,
      color: "#B47D35",
      description: "Nhận +1 all stats.",
    },
    {
      id: "03",
      name: "In Love",
      weight: 2,
      color: "#7A1F1F",
      description:
        "Quay một player làm 'Lover' và nhận +1 vào Stat mà người đó cao nhất.",
    },
    {
      id: "04",
      name: "No more Home",
      weight: 1.2,
      color: "#3D6B3D",
      description:
        "Bạn bị loại khỏi 'House' của mình và mất tất cả Bonus từ đó.",
    },
    {
      id: "05",
      name: "No more family",
      weight: 1.2,
      color: "#AAAAAA",
      description: "Nhận thêm 2 Power.",
    },
    {
      id: "06",
      name: "Depression",
      weight: 2.4,
      color: "#4F772D",
      description: "Nhận -3 vào chỉ số cao nhất khi nhận Char Dev này.",
    },
    {
      id: "07",
      name: "Seeking Wisdom",
      weight: 2.2,
      color: "#38761D",
      description: "Nhận +4 IQ.",
    },
    {
      id: "08",
      name: "Inversion",
      weight: 0.9,
      color: "#228B22",
      description: "Đảo ngược tất cả base stat.",
    },
    {
      id: "09",
      name: "Isekai",
      weight: 0.9,
      color: "#2F7EBB",
      description: "Quay lại từ đầu 💀",
    },
    {
      id: "10",
      name: "Final Reserves",
      weight: 1.6,
      color: "#7F7FFF",
      description:
        "Khi ở nhánh thua, +1 all stats. Khi đến vòng 16 người nhánh thua, loại bỏ hiệu ứng này và nhận 2 random Power.",
    },
    {
      id: "11",
      name: "Lose Control",
      weight: 1.7,
      color: "#CC66CC",
      description: "Mất tất cả Power. 💀",
    },
    {
      id: "12",
      name: "Prime time",
      weight: 1.5,
      color: "#8B4513",
      description:
        "Nhận +2 all stats. Vô hiệu hóa khi xuống nhánh thua và chung kết.",
    },
    {
      id: "13",
      name: "Fate's Trick",
      weight: 3.3,
      color: "#660000",
      description:
        "Có 50% khả năng nhân đôi stat thấp nhất và 50% khả năng chia đôi stat cao nhất.",
    },
    {
      id: "14",
      name: "Old Age",
      weight: 2.8,
      color: "#999933",
      description: "Nhận +3 IQ và -1 mọi chỉ số còn lại.",
    },
    {
      id: "15",
      name: "Creator's Favor",
      weight: 1.3,
      color: "#FFD700",
      description:
        "'Đấng Sáng Tạo' tùy ý buff cho nhân vật. (Không thay đổi quá 2 chỉ số).",
    },
    {
      id: "16",
      name: "Become Woke",
      weight: 3,
      color: "#FF8C00",
      description: "Nhận -3 IQ, +1 Strength và +1 Durability.",
    },
    {
      id: "17",
      name: "Demonic Pact",
      weight: 2.2,
      color: "#8A2BE2",
      description: "Hiến tế 1 base stat ngẫu nhiên để nhận 3 Power.",
    },
    {
      id: "18",
      name: "Mentor",
      weight: 2.8,
      color: "#8B0000",
      description: "Nhận thêm 1 Power từ 1 Player ngẫu nhiên.",
    },
    {
      id: "19",
      name: "It is what it is",
      weight: 1.5,
      color: "#FFFFFF",
      description: "Mất hết toàn bộ vũ khí của mình. 💀",
    },
    {
      id: "20",
      name: "Make love",
      weight: 1.8,
      color: "#7A1F1F",
      description:
        "Quay 1 wheel bao gồm toàn bộ player hiện tại để chọn ra người tình.",
    },
    {
      id: "21",
      name: "Pessimistic",
      weight: 1.6,
      color: "#3D6B3D",
      description: "Khi xuống nhánh thua, -1 all stats.",
    },
    {
      id: "22",
      name: "Finality",
      weight: 0.8,
      color: "#AAAAAA",
      description: "Race của bạn tuyệt chủng trong mùa này. 💀",
    },
    {
      id: "23",
      name: "Last Standing",
      weight: 1.3,
      color: "#4F772D",
      description:
        "Khi là người duy nhất còn lại của 'Gia tộc' (House), +2 all stats.",
    },
    {
      id: "24",
      name: "Furry",
      weight: 1.9,
      color: "#38761D",
      description:
        "(1).Trong Combat: Nhận +1 all stats khi đấu với Werebeast\n(2).Nếu thua Werebeast, nhận -1 All Stats.",
    },
    {
      id: "25",
      name: "Abused",
      weight: 3.1,
      color: "#228B22",
      description: "Nhận -1 IQ, +3 Durability.",
    },
    {
      id: "26",
      name: "A Big Gift!",
      weight: 1.4,
      color: "#2F7EBB",
      description: "Nhận 1 random Legacy Gear.",
    },
    {
      id: "27",
      name: "Become Vegetarian",
      weight: 4,
      color: "#7F7FFF",
      description: "Nhận -2 Durability.",
    },
    {
      id: "28",
      name: "Creator's Limitation",
      weight: 2,
      color: "#CC66CC",
      description:
        "'Đấng Sáng Tạo' tùy ý nerf cho nhân vật. (Không thay đổi quá 2 chỉ số).",
    },
    {
      id: "29",
      name: "Braindead",
      weight: 3,
      color: "#8B4513",
      description: "Nhận -4 IQ. 💀",
    },
    {
      id: "30",
      name: "Blessed by Chaos",
      weight: 3,
      color: "#660000",
      description:
        "Kéo base stat của chỉ số cao nhất xuống 1, sau đó nhận thêm 2 Character Development.",
    },
    {
      id: "31",
      name: "Lost an Arm",
      weight: 3,
      color: "#999933",
      description: "Nhận -4 Martial Arts 💀",
    },
    {
      id: "32",
      name: "Lost a Leg",
      weight: 3,
      color: "#FFD700",
      description: "Nhận -4 Speed 💀",
    },
    {
      id: "33",
      name: "Obtain a Cultivation Technique",
      weight: 1.9,
      color: "#FF8C00",
      description: "Nhận +2 BIQ, +3 Martial Arts.",
    },
    {
      id: "34",
      name: "Become King Slayer",
      weight: 1,
      color: "#8A2BE2",
      description:
        "(1).Nhận Archetype 'Slayer'. Nếu bạn đang là một 'Slayer', chọn thêm 1 tộc nữa.\n(2).Trong Combat: Nếu đối thủ có Char Dev 'King's Landing', nhận +1 All Stats.",
    },
    {
      id: "35",
      name: "King's Landing",
      weight: 0.5,
      color: "#8B0000",
      description:
        "(1).Khi bạn bị loại, tất cả mọi người còn sống trong 'Gia tộc' của bạn sẽ được nhận 1 Power.\n(2).Trong Combat: Nếu bạn không có Archetype 'Devotee', Không thuộc race 'God' hoặc 'Demi God', nhận -2 điểm khởi đầu và -10 IQ.",
    },
    {
      id: "36",
      name: "True Heir of the Emirate",
      weight: 3.6,
      color: "#FFFFFF",
      description:
        "Nếu bạn có Archetype số 36, nhận +1 All Stats 🍀\nNếu bạn có Unique Weapon số 36, nhận +1 All Stats 🍀",
    },
    {
      id: "37",
      name: "Become Hand of The King",
      weight: 1,
      color: "#D4AF37",
      description:
        "(1).Nhận +3 IQ\n(2). Trong Combat: Nếu đối thủ có Char Dev 'Become King Slayer', nhận +1 All Stats.",
    },
    {
      id: "38",
      name: "Kungfu Training",
      weight: 1.9,
      color: "#B47D35",
      description: "Nhận +2 Durability và +2 Martial Arts",
    },
    {
      id: "39",
      name: "Too Horny",
      weight: 3.6,
      color: "#7A1F1F",
      description:
        "Nhận +3 Strength và +2 Durability, nhưng Base IQ biến thành 0.",
    },
    {
      id: "40",
      name: "Creator's Reforge",
      weight: 1.8,
      color: "#3D6B3D",
      description:
        "Loại bỏ vũ khí hiện tại, Creator sẽ chọn 1 vũ khí Normal cho bạn, vũ khí này sẽ nhận 1 Enchantment do Creator chọn.",
    },
    {
      id: "41",
      name: "Become Perfectionist",
      weight: 2.4,
      color: "#AAAAAA",
      description: "Nhận Archetype 'Perfectionist'.",
    },
    {
      id: "42",
      name: "Too Edgy",
      weight: 2.4,
      color: "#4F772D",
      description: "Nhận Archetype 'Edgelord'.",
    },
    {
      id: "43",
      name: "Overcome the Habits",
      weight: 1.8,
      color: "#38761D",
      description: "Với mỗi Quirk bạn có trên người, +1 vào stat thấp nhất.",
    },
    {
      id: "44",
      name: "Nghe Bài thú tội",
      weight: 3,
      color: "#228B22",
      description:
        "50% Nhận Char Dev 'Braindead', 50% Nhận Char Dev 'Seeking Wisdom'.",
    },
    {
      id: "45",
      name: "Trở thành Linh Mục",
      weight: 3,
      color: "#2F7EBB",
      description: "Nhận Archetype 'Linh Mục'.",
    },
    {
      id: "46",
      name: "Trở Thành Cha Xứ",
      weight: 3,
      color: "#7F7FFF",
      description: "Nhận Archetype 'Cha Xứ'.",
    },
    {
      id: "47",
      name: "Trở thành Quỷ Nhà Thờ",
      weight: 3,
      color: "#CC66CC",
      description: "Nhận Archetype 'Quỷ Nhà Thờ'.",
    },
  ],
};
