import { WheelStep } from "../Types/Types.ts";

export const playerWheel: WheelStep = {
  key: "player",
  title: "Player",
  sections: [
    { id: "01", name: "Hinaso1", weight: 1, color: "#7A1F1F", description: "" },
    {
      id: "02",
      name: "Gilgamesh2202",
      weight: 1,
      color: "#B47D35",
      description: "",
    },
    {
      id: "03",
      name: "Gyro Zeppeli",
      weight: 1,
      color: "#C2B678",
      description: "",
    },
    {
      id: "04",
      name: "Rat La Chi",
      weight: 1,
      color: "#3D6B3D",
      description: "",
    },
    { id: "05", name: "Ar2di", weight: 1, color: "#AAAAAA", description:    "" },
    { id: "06", name: "Snaffy", weight: 1, color: "#4F772D", description: "" },
    {
      id: "07",
      name: "KuSenpai",
      weight: 1,
      color: "#38761D",
      description: "",
    },
    { id: "08", name: "Ethan", weight: 1, color: "#228B22", description: "" },
    { id: "09", name: "Dian", weight: 1, color: "#2F7EBB", description: "" },
    { id: "10", name: "Illya", weight: 1, color: "#7F7FFF", description: "" },
    {
      id: "11",
      name: "wyug1234",
      weight: 1,
      color: "#9B1D64",
      description: "",
    },
    { id: "12", name: "Nagi", weight: 1, color: "#D97706", description: "" },
    { id: "13", name: "jcl2808", weight: 1, color: "#16A085", description: "" },
    { id: "14", name: "Seki", weight: 1, color: "#8E44AD", description: "" },
    { id: "15", name: "Lười", weight: 1, color: "#C0392B", description: "" },
    {
      id: "16",
      name: "AtarashiKTRS",
      weight: 1,
      color: "#2980B9",
      description: "",
    },
    { id: "17", name: "Syren", weight: 1, color: "#27AE60", description: "" },
    {
      id: "18",
      name: "HuyHa-im5hj",
      weight: 1,
      color: "#F1C40F",
      description: "",
    },
    {
      id: "19",
      name: "Đừng Nhờn với 36",
      weight: 1,
      color: "#E74C3C",
      description: "",
    },
    { id: "20", name: "lambeii", weight: 1, color: "#8D5524", description: "" },
    {
      id: "21",
      name: "asthewinterdawn",
      weight: 1,
      color: "#2ECC71",
      description: "",
    },
    {
      id: "22",
      name: "vi_talsigns",
      weight: 1,
      color: "#3498DB",
      description: "",
    },
    { id: "23", name: "Ginkka", weight: 1, color: "#E67E22", description: "" },
    {
      id: "24",
      name: "Cá Đuối Lào Cai",
      weight: 1,
      color: "#1ABC9C",
      description: "",
    },
    { id: "25", name: "pui19", weight: 1, color: "#9B59B6", description: "" },
    {
      id: "26",
      name: "Daovienhoagia",
      weight: 1,
      color: "#34495E",
      description: "",
    },
    { id: "27", name: "euoid", weight: 1, color: "#F39C12", description: "" },
    {
      id: "28",
      name: "quang03022",
      weight: 1,
      color: "#D35400",
      description: "",
    },
    {
      id: "29",
      name: "Cloudian",
      weight: 1,
      color: "#7D3C98",
      description: "",
    },
    {
      id: "30",
      name: "Cá giả Chó",
      weight: 1,
      color: "#148F77",
      description: "",
    },
    {
      id: "31",
      name: "lukeatatat",
      weight: 1,
      color: "#7A1F1F",
      description: "",
    },
    { id: "32", name: "dtc", weight: 1, color: "#B47D35", description: "" },
    {
      id: "33",
      name: "lunacy6545",
      weight: 1,
      color: "#C2B678",
      description: "",
    },
    {
      id: "34",
      name: "Korokiri",
      weight: 1,
      color: "#3D6B3D",
      description: "",
    },
    {
      id: "35",
      name: "majinlord666",
      weight: 1,
      color: "#AAAAAA",
      description: "",
    },
    { id: "36", name: "Vinh", weight: 1, color: "#4F772D", description: "" },
    {
      id: "37",
      name: "Chocon-pn2fi",
      weight: 1,
      color: "#38761D",
      description: "",
    },
    {
      id: "38",
      name: "paranoia1431",
      weight: 1,
      color: "#228B22",
      description: "",
    },
    { id: "39", name: ".huy._", weight: 1, color: "#2F7EBB", description: "" },
    { id: "40", name: "zed9179", weight: 1, color: "#7F7FFF", description: "" },
    {
      id: "41",
      name: "trthesloth",
      weight: 1,
      color: "#9B1D64",
      description: "",
    },
    {
      id: "42",
      name: "Nice Nature",
      weight: 1,
      color: "#D97706",
      description: "",
    },
    { id: "43", name: "ltl.jr", weight: 1, color: "#16A085", description: "" },
    {
      id: "44",
      name: ".ilovepony",
      weight: 1,
      color: "#8E44AD",
      description: "",
    },
    {
      id: "45",
      name: "phuongan1704",
      weight: 1,
      color: "#C0392B",
      description: "",
    },
    { id: "46", name: "JoeC", weight: 1, color: "#2980B9", description: "" },
    {
      id: "47",
      name: "yamakunson",
      weight: 1,
      color: "#27AE60",
      description: "",
    },
    {
      id: "48",
      name: "_fallen_yue",
      weight: 1,
      color: "#F1C40F",
      description: "",
    },
    {
      id: "49",
      name: "yunashigemura4303",
      weight: 1,
      color: "#E74C3C",
      description: "",
    },
    { id: "50", name: "huymei", weight: 1, color: "#8D5524", description: "" },
    { id: "51", name: "watevr0", weight: 1, color: "#2ECC71", description: "" },
    {
      id: "52",
      name: "mihate07",
      weight: 1,
      color: "#3498DB",
      description: "",
    },
    {
      id: "53",
      name: "viet3657",
      weight: 1,
      color: "#E67E22",
      description: "",
    },
    {
      id: "54",
      name: "seems_18",
      weight: 1,
      color: "#1ABC9C",
      description: "",
    },
    {
      id: "55",
      name: "namthuan5890",
      weight: 1,
      color: "#9B59B6",
      description: "",
    },
    {
      id: "56",
      name: "_yeetusmymeatus",
      weight: 1,
      color: "#34495E",
      description: "",
    },
    { id: "57", name: "npc867", weight: 1, color: "#F39C12", description: "" },
    {
      id: "58",
      name: "johnnywalkaways",
      weight: 1,
      color: "#D35400",
      description: "",
    },
    {
      id: "59",
      name: "duckiee2369",
      weight: 1,
      color: "#7D3C98",
      description: "",
    },
    { id: "60", name: "Cheesed", weight: 1, color: "#148F77", description: "" },
    {
      id: "61",
      name: "blaster007",
      weight: 1,
      color: "#7A1F1F",
      description: "",
    },
    { id: "62", name: "Cảo", weight: 1, color: "#B47D35", description: "" },
    {
      id: "63",
      name: "Anh Thầy Bói",
      weight: 1,
      color: "#C2B678",
      description: "",
    },
    {
      id: "64",
      name: "milanneeee",
      weight: 1,
      color: "#3D6B3D",
      description: "",
    },
    { id: "65", name: "Panđa", weight: 1, color: "#AAAAAA", description: "" },
    { id: "66", name: "666", weight: 1, color: "#4F772D", description: "" },
    {
      id: "67",
      name: "schweinzz",
      weight: 1,
      color: "#38761D",
      description: "",
    },
    {
      id: "68",
      name: "Ngũ hổ vồ xôi",
      weight: 1,
      color: "#228B22",
      description: "",
    },
    {
      id: "69",
      name: "duongquaqua",
      weight: 1,
      color: "#2F7EBB",
      description: "",
    },
    {
      id: "70",
      name: "KennyS1mple",
      weight: 1,
      color: "#7F7FFF",
      description: "",
    },
    { id: "71", name: "GiCi", weight: 1, color: "#9B1D64", description: "" },
    {
      id: "72",
      name: "Lovepcdolls",
      weight: 1,
      color: "#D97706",
      description: "",
    },
    { id: "73", name: "Em Minh", weight: 1, color: "#16A085", description: "" },
    { id: "74", name: "mYami", weight: 1, color: "#8E44AD", description: "" },
    {
      id: "75",
      name: "Perorodzilla Lunatic",
      weight: 1,
      color: "#C0392B",
      description: "",
    },
    { id: "76", name: "Zackie", weight: 1, color: "#2980B9", description: "" },
    { id: "77", name: "Sizaky", weight: 1, color: "#27AE60", description: "" },
    { id: "78", name: "Zannsa", weight: 1, color: "#F1C40F", description: "" },
    {
      id: "79",
      name: "ClarisS97",
      weight: 1,
      color: "#E74C3C",
      description: "",
    },
    { id: "80", name: "Shin", weight: 1, color: "#8D5524", description: "" },
    { id: "81", name: "La+simp", weight: 1, color: "#2ECC71", description: "" },
    { id: "82", name: "Swem", weight: 1, color: "#3498DB", description: "" },
    {
      id: "83",
      name: "kinema0109",
      weight: 1,
      color: "#E67E22",
      description: "",
    },
    { id: "84", name: ".lowns", weight: 1, color: "#1ABC9C", description: "" },
    {
      id: "85",
      name: "AmeBear Đỉnh Súng",
      weight: 1,
      color: "#9B59B6",
      description: "",
    },
    { id: "86", name: "Yuki", weight: 1, color: "#34495E", description: "" },
    {
      id: "87",
      name: "greed101101",
      weight: 1,
      color: "#F39C12",
      description: "",
    },
    {
      id: "88",
      name: "Noble Usagi",
      weight: 1,
      color: "#D35400",
      description: "",
    },
    { id: "89", name: "Pine", weight: 1, color: "#7D3C98", description: "" },
    {
      id: "90",
      name: "hungchika_dct_300d",
      weight: 1,
      color: "#148F77",
      description: "",
    },
    { id: "91", name: "Tsuki", weight: 1, color: "#7A1F1F", description: "" },
    {
      id: "92",
      name: "Ông tổ nghề rèn",
      weight: 1,
      color: "#B47D35",
      description: "",
    },
    {
      id: "93",
      name: "Hoàng Tuyền Không Trấn",
      weight: 1,
      color: "#C2B678",
      description: "",
    },
    { id: "94", name: "Snorlax", weight: 1, color: "#3D6B3D", description: "" },
    {
      id: "95",
      name: "NguyenHung-swe",
      weight: 1,
      color: "#AAAAAA",
      description: "",
    },
    { id: "96", name: "Hamster", weight: 1, color: "#4F772D", description: "" },
    { id: "97", name: "Nasume", weight: 1, color: "#38761D", description: "" },
    {
      id: "98",
      name: "kaywai81",
      weight: 1,
      color: "#228B22",
      description: "",
    },
    { id: "99", name: "Anh Mèo", weight: 1, color: "#2F7EBB", description: "" },
    {
      id: "100",
      name: "ksepack",
      weight: 1,
      color: "#7F7FFF",
      description: "",
    },
    {
      id: "101",
      name: "sybaukam1",
      weight: 1,
      color: "#9B1D64",
      description: "",
    },
    { id: "102", name: "AnhSay", weight: 1, color: "#D97706", description: "" },
    { id: "103", name: "Ánh", weight: 1, color: "#16A085", description: "" },
    {
      id: "104",
      name: "Thắng ko chấm nước mắm",
      weight: 1,
      color: "#8E44AD",
      description: "",
    },
    {
      id: "105",
      name: "Bánh Mì",
      weight: 1,
      color: "#C0392B",
      description: "",
    },
    { id: "106", name: "4k_iIl", weight: 1, color: "#2980B9", description: "" },
    {
      id: "107",
      name: "lock485",
      weight: 1,
      color: "#27AE60",
      description: "",
    },
    {
      id: "108",
      name: "Trapcon",
      weight: 1,
      color: "#F1C40F",
      description: "",
    },
    { id: "109", name: "Nega", weight: 1, color: "#E74C3C", description: "" },
    {
      id: "110",
      name: "Anh Bảo",
      weight: 1,
      color: "#8D5524",
      description: "",
    },
    {
      id: "111",
      name: "huntervu",
      weight: 1,
      color: "#2ECC71",
      description: "",
    },
    { id: "112", name: "Juan", weight: 1, color: "#3498DB", description: "" },
    {
      id: "113",
      name: "uchihahahaha5296",
      weight: 1,
      color: "#E67E22",
      description: "",
    },
    { id: "114", name: "Hero X", weight: 1, color: "#1ABC9C", description: "" },
    {
      id: "115",
      name: "Lệch rate Jingliu 2 lần",
      weight: 1,
      color: "#9B59B6",
      description: "",
    },
    {
      id: "116",
      name: "người việt gốc cây",
      weight: 1,
      color: "#34495E",
      description: "",
    },
    { id: "117", name: "Solus", weight: 1, color: "#F39C12", description: "" },
    {
      id: "118",
      name: "ngọn cỏ ven sông",
      weight: 1,
      color: "#D35400",
      description: "",
    },
    { id: "119", name: "Taiyo", weight: 1, color: "#7D3C98", description: "" },
    { id: "120", name: "Морк", weight: 1, color: "#148F77", description: "" },
    {
      id: "121",
      name: "Kingyuan",
      weight: 1,
      color: "#7A1F1F",
      description: "",
    },
    {
      id: "122",
      name: "⭐⭐⭐⭐⭐",
      weight: 1,
      color: "#B47D35",
      description: "",
    },
    {
      id: "123",
      name: "Vinh Vander Bek",
      weight: 1,
      color: "#C2B678",
      description: "",
    },
    { id: "124", name: "Roku", weight: 1, color: "#3D6B3D", description: "" },
    {
      id: "125",
      name: "Warmbunny",
      weight: 1,
      color: "#AAAAAA",
      description: "",
    },
    { id: "126", name: "yodayo", weight: 1, color: "#4F772D", description: "" },
    {
      id: "127",
      name: "0chjnchjn",
      weight: 1,
      color: "#38761D",
      description: "",
    },
    {
      id: "128",
      name: "KaTsumi420",
      weight: 1,
      color: "#228B22",
      description: "",
    },
  ],
};
