import { COLOR_PALETTE } from "../Constants/ConstantsConfig";
import { WheelStep } from "../Types/Types";

// Power theo hệ Martial Arts (5 hệ)
const POWER_CONFIG: Record<string, number[]> = {
  Goblin: [35, 30, 20, 10, 5],
  Gnome: [30, 30, 25, 10, 5],
  Human: [25, 25, 28, 15, 7],
  Dwarf: [30, 35, 20, 10, 5],
  Skeleton: [10, 10, 10, 10, 10],
  Troll: [30, 35, 20, 10, 5],
  Orc: [30, 35, 20, 10, 5],
  Dryad: [50, 5, 20, 5, 20],
  Elf: [10, 35, 25, 20, 10],
  Spirit: [20, 35, 30, 10, 5],
  Uma: [20, 25, 35, 15, 5],
  Werebeast: [20, 35, 25, 15, 5],
  Vampire: [20, 35, 25, 15, 5],
  Giant: [45, 5, 10, 5, 35],
  Dragon: [5, 15, 50, 20, 10],
  Angel: [15, 20, 30, 25, 10],
  "Demi-God": [20, 10, 35, 15, 20],
  "Primordial Being": [15, 5, 25, 35, 20],
  Demon: [20, 5, 15, 35, 25],
  God: [20, 5, 15, 35, 25],
};

export const powerCountWheel = (race: string): WheelStep => {
  const values = POWER_CONFIG[race] || Array(5).fill(10);
  return {
    key: "power-count",
    title: "Power count",
    sections: values.map((val, idx) => ({
      id: `pw${idx + 1}`,
      name: `${idx + 1}`,
      weight: val,
      color: COLOR_PALETTE[idx % COLOR_PALETTE.length],
      description: `Power level: ${val}`,
    })),
  };
};

export const PowerWheel: WheelStep = {
  key: "power",
  title: "Power",
  sections: [
    {
      id: "1",
      name: "Artist",
      effect:
        "Khi xuống nhánh thua, Stat lẻ của bạn được +1. (Tính theo chỉ số quay được từ đầu - Base Stats)",
      weight: 0.9,
      color: COLOR_PALETTE[0],
    },
    {
      id: "2",
      name: "Writer",
      effect:
        "Khi xuống nhánh thua, Stat chẵn của bạn được +1. (Tính theo chỉ số quay được từ đầu - Base Stats)",
      weight: 0.9,
      color: "",
    },
    {
      id: "3",
      name: "Critical Strike",
      effect:
        "Với mỗi round thắng, bạn có 20% nhận thêm 1 điểm. Thứ tự ưu tiên: Ashina Skill - Crit - Gambler",
      weight: 0.9,
      color: "",
    },
    {
      id: "4",
      name: "Red Shift/LP1211-M",
      effect:
        "Trong combat: Nếu bạn thắng ít nhất 1 trong 3 round đầu tiên (Strength/Speed/Durability), nhận +1 IQ, +1 BIQ và +2 MA.",
      weight: 0.9,
      color: "",
    },
    {
      id: "5",
      name: "Shooting for Victory",
      effect:
        "Trong combat: Nếu bạn thắng ít nhất 1 và thua ít nhất 1 trong 3 round đầu tiên (Strength/Speed/Durability), nhận +1 IQ, +1 BIQ và +2 MA.",
      weight: 0.9,
      color: "",
    },
    {
      id: "6",
      name: "Let's Pump Some Iron!",
      effect:
        "Trong combat: Nếu bạn thắng chính xác 1 trong 3 round đầu tiên (Strength/Speed/Durability), nhận +2 IQ, +2 BIQ và +2 MA.",
      weight: 0.9,
      color: "",
    },
    {
      id: "7",
      name: "U=ma2",
      effect: "Trong combat: Nhận +5 Durability nếu bạn thua round Speed.",
      weight: 0.9,
      color: "",
    },
    {
      id: "8",
      name: "Ice Liquefactors",
      effect: "Hóa lỏng băng 💀???",
      weight: 0.9,
      color: "",
    },
    {
      id: "9",
      name: "Crimson Poison",
      effect: "Đối thủ -1 Durability, giảm thêm 1 với mỗi 2 Power sở hữu.",
      weight: 0.9,
      color: "",
    },
    {
      id: "10",
      name: "Bloody Strike",
      effect:
        "Nhận -1 All Stats. Với mỗi Round thắng,+1 vào Stat đó (Áp dụng sau combat)",
      weight: 0.9,
      color: "",
    },
    {
      id: "11",
      name: "Divine Smite",
      effect:
        "Nhận +1 Điểm nếu thắng ở Round MA. Xảy ra sau cùng, sau khi 'Kiếm Phái Ashina'.",
      weight: 0.9,
      color: "",
    },
    {
      id: "12",
      name: "Fire Control",
      effect:
        "Có thể điều khiển được một ngọn lửa bật hoặc tắt. Ngoài ra không tác dụng 💀",
      weight: 0.9,
      color: "",
    },
    {
      id: "13",
      name: "Thunder Orb",
      effect: "Đối thủ giảm 2 Durability.",
      weight: 0.9,
      color: "",
    },
    {
      id: "14",
      name: "Water Breathing",
      effect: "Thở dưới nước.",
      weight: 0.9,
      color: "",
    },
    {
      id: "15",
      name: "Golden Vow",
      effect: "Bản thân khởi đầu trận đấu với +1 điểm.",
      weight: 0.9,
      color: "",
    },
    {
      id: "16",
      name: "Mind Control",
      effect: "Nhận +1 all stats khi đối đầu với kẻ địch có IQ từ 5 trở xuống.",
      weight: 0.9,
      color: "",
    },
    {
      id: "17",
      name: "Blood Manipulation",
      effect:
        "Nhận +1 strength khi đối đầu với tất cả kẻ địch trừ 'Skeleton' và 'Spirit'.",
      weight: 0.9,
      color: "",
    },
    {
      id: "18",
      name: "Sonic Scream",
      effect: "Đối thủ nhận -1 Durability.",
      weight: 0.9,
      color: "",
    },
    {
      id: "19",
      name: "Drunken Boxing",
      effect: "Nhận -1 IQ, -1 Speed và +3 MA.",
      weight: 0.9,
      color: "",
    },
    {
      id: "20",
      name: "Time Travel",
      effect: "Re-spin lại chỉ số thấp nhất 1 lần.",
      weight: 0.9,
      color: "",
    },
    {
      id: "21",
      name: "Cursed",
      effect: "Re-spin lại chỉ số cao nhất 1 lần.",
      weight: 0.9,
      color: "",
    },
    {
      id: "22",
      name: "Divine Lightning",
      effect:
        "Nhận +1 Strength, +1 Speed và +1 MA, tăng lên +2 nếu chiến đấu với Demon/Evil God.",
      weight: 0.9,
      color: "",
    },
    {
      id: "23",
      name: "Fist Fighting",
      effect: "Nếu sở hữu vũ khí, mất đi nó. Nhận +2 MA.",
      weight: 0.9,
      color: "",
    },
    {
      id: "24",
      name: "Evasion",
      effect:
        "Mỗi round thua trong combat, có khả năng nhận được 1 điểm (Wheel 20%)",
      weight: 0.9,
      color: "",
    },
    {
      id: "25",
      name: "Enhanced Hearing",
      effect:
        "Nhận +2 MA, -1 all stats nếu đối thủ dùng nhạc cụ và -2 nếu đối thủ có Power liên quan tới âm thanh.",
      weight: 0.9,
      color: "",
    },
    {
      id: "26",
      name: "Rampage",
      effect: "Sau mỗi trận thắng, có 25% khả năng nhận +1 all stats.",
      weight: 0.9,
      color: "",
    },
    {
      id: "27",
      name: "Bloodlust",
      effect:
        "Sau mỗi trận thắng, nhận -1 IQ, -1 MA và +1 Strength, +1 Speed, +1 Durability.",
      weight: 0.9,
      color: "",
    },
    {
      id: "28",
      name: "Rickrolling",
      effect: "Chắc không cần giải thích đâu nhỉ 💀",
      weight: 0.9,
      color: "",
    },
    {
      id: "29",
      name: "Power Absorption",
      effect: "Sau mỗi trận thắng, hấp thụ 1 Power ngẫu nhiên của đối thủ.",
      weight: 0.9,
      color: "",
    },
    {
      id: "30",
      name: "Hand Washing",
      effect: "Tay sạch 💀",
      weight: 0.9,
      color: "",
    },
    {
      id: "31",
      name: "Power Negation",
      effect: "Vô hiệu hóa 1 Power ngẫu nhiên của đối thủ.",
      weight: 0.9,
      color: "",
    },
    {
      id: "32",
      name: "Stat Absorption",
      effect:
        "Sau mỗi trận thắng, +1 cho bản thân vào chỉ số mà đối thủ có cao nhất.",
      weight: 0.9,
      color: "",
    },
    {
      id: "33",
      name: "Invulnerability",
      effect: "Nhận +2 Durability.",
      weight: 0.9,
      color: "",
    },
    {
      id: "34",
      name: "Power Mimicry",
      effect:
        "Sao chép 1 Power ngẫu nhiên của đối thủ. (chỉ trong trận đấu đó)",
      weight: 0.9,
      color: "",
    },
    {
      id: "35",
      name: "Mewing",
      effect: "Bye bye 🤫🧏‍♂",
      weight: 0.9,
      color: "",
    },
    {
      id: "36",
      name: "Railroad Realm",
      effect:
        "Trong Combat: Bạn và đối thủ sẽ nghe tiếng xình xịch của những đoàn tàu xe lửa 🍀",
      weight: 0.9,
      color: "",
    },
    {
      id: "37",
      name: "Possession",
      effect:
        "Chọn một stat ngẫu nhiên (trừ IQ). Nếu IQ của bạn cao hơn đối thủ, hoán đổi stat được chọn với đối thủ nếu stat của bạn thấp hơn. Nếu IQ của bạn thấp hơn đối thủ thì ngược lại. (Hiệu lực vĩnh viễn)",
      weight: 0.9,
      color: "",
    },
    {
      id: "38",
      name: "Overdrive",
      effect: "Nhận +2 MA, -2 Durability.",
      weight: 0.9,
      color: "",
    },
    {
      id: "39",
      name: "Age Manipulation",
      effect: "Đối thủ +1 IQ, -1 mọi stat còn lại)",
      weight: 0.9,
      color: "",
    },
    {
      id: "40",
      name: "Enlarging",
      effect: "Nhận +2 Strength, +2 Durability, -4 Speed.",
      weight: 0.9,
      color: "",
    },
    {
      id: "41",
      name: "Shrinking",
      effect: "Nhận +4 Speed, -2 Strength, -2 Durability.",
      weight: 0.9,
      color: "",
    },
    {
      id: "42",
      name: "Garlic Breath",
      effect: "Nhận +1 all stats nếu đối thủ là Vampire.",
      weight: 0.9,
      color: "",
    },
    {
      id: "43",
      name: "The Goat",
      effect: "Bạn là dê! 💀",
      weight: 0.9,
      color: "",
    },
    {
      id: "44",
      name: "Fancy Feet",
      effect: "Nhận -1 Durability nhưng vô hiệu hóa vũ khí của đối phương.",
      weight: 0.9,
      color: "",
    },
    {
      id: "45",
      name: "Weapon Enhancing",
      effect:
        "Thêm +1 vào mỗi buff tăng stat ở vũ khí, thêm -1 vào mỗi debuff giảm stat.",
      weight: 0.9,
      color: "",
    },
    {
      id: "46",
      name: "Body Enhancing",
      effect: "Nhận +1 Strength, +1 Speed, +1 Durability.",
      weight: 0.9,
      color: "",
    },
    {
      id: "47",
      name: "Clear Mind",
      effect: "Nhận +2 IQ.",
      weight: 0.9,
      color: "",
    },
    {
      id: "48",
      name: "Petrification",
      effect: "Đối thủ nhận -3 Speed.",
      weight: 0.9,
      color: "",
    },
    {
      id: "49",
      name: "Blowing Leaves",
      effect: "Thổi lá bay đi 💀",
      weight: 0.9,
      color: "",
    },
    {
      id: "50",
      name: "Force Field",
      effect: "Đối thủ nhận -1 Speed, -1 MA.",
      weight: 0.9,
      color: "",
    },
    {
      id: "51",
      name: "Anti-Magic Barrier",
      effect: "Vô hiệu hóa 2 Power của đối thủ, nhận -1 Durability.",
      weight: 0.9,
      color: "",
    },
    {
      id: "52",
      name: "Black Magic",
      effect: "Đối thủ nhận -2 vào một stat ngẫu nhiên.",
      weight: 0.9,
      color: "",
    },
    {
      id: "53",
      name: "The Great Storm",
      effect: "-2 Durability của Đối thủ",
      weight: 0.9,
      color: "",
    },
    {
      id: "54",
      name: "Continental Super Storm",
      effect: "Nhận +2 Speed",
      weight: 0.9,
      color: "",
    },
    {
      id: "55",
      name: "Sacred Fire",
      effect: "Nhận +1 all stats nếu đối thủ là Vampire hoặc Demon.",
      weight: 0.9,
      color: "",
    },
    {
      id: "56",
      name: "Capybara",
      effect: "Capybara",
      weight: 0.9,
      color: "",
    },
    {
      id: "57",
      name: "Tsunami Control",
      effect: "Nhận +2 Strength",
      weight: 0.9,
      color: "",
    },
    {
      id: "58",
      name: "Rising tide",
      effect: "Nhận +1 MA",
      weight: 0.9,
      color: "",
    },
    {
      id: "59",
      name: "Seismic",
      effect: "Đối thủ -1 MA",
      weight: 0.9,
      color: "",
    },
    {
      id: "60",
      name: "Earth-Shaking",
      effect: "Đất đá rung chuyển.",
      weight: 0.9,
      color: "",
    },
    {
      id: "61",
      name: "Disarmament",
      effect: "Trong combat: Vô hiệu hóa vũ khí đối thủ",
      weight: 0.9,
      color: "",
    },
    {
      id: "62",
      name: "Night Vision",
      effect: "Có thể nhìn trong bóng tối. 💀",
      weight: 0.9,
      color: "",
    },
    {
      id: "63",
      name: "Unstoppable",
      effect: "Miễn nhiễm với mọi debuff giảm stat từ đối thủ.",
      weight: 0.9,
      color: "",
    },
    {
      id: "64",
      name: "Gotta go Fast",
      effect: "Bạn là Sonic 💀",
      weight: 0.9,
      color: "",
    },
    {
      id: "65",
      name: "Fair Duel",
      effect: "Bạn và đối thủ miễn nhiễm với mọi hiệu ứng giảm stat từ nhau.",
      weight: 0.9,
      color: "",
    },
    {
      id: "66",
      name: "Uno Reverse Card",
      effect:
        "Mọi debuff giảm stat từ đối thủ sẽ chuyển sang áp dụng lên chính hắn.",
      weight: 0.9,
      color: "",
    },
    {
      id: "67",
      name: "Burning Hand",
      effect: "Nhận +1 Strength.",
      weight: 0.9,
      color: "",
    },
    {
      id: "68",
      name: "Tick-tock",
      effect: "Cơ thể bạn phát ra tiếng của đồng hồ. 💀",
      weight: 0.9,
      color: "",
    },
    {
      id: "69",
      name: "Frost Armor",
      effect: "Nhận +1 Durability.",
      weight: 0.9,
      color: "",
    },
    {
      id: "70",
      name: "Acid-Throated",
      effect:
        "Cổ họng đầy Axit, khi thua trận khiến -2 Durability cho đối thủ.",
      weight: 0.9,
      color: "",
    },
    {
      id: "71",
      name: "Lightning Enchant",
      effect: "Nhận +2 Speed",
      weight: 0.9,
      color: "",
    },
    {
      id: "72",
      name: "Acid Breath",
      effect: "-1 Durability đối thủ.",
      weight: 0.9,
      color: "",
    },
    {
      id: "73",
      name: "Poison Breath",
      effect: "-1 IQ của đối thủ.",
      weight: 0.9,
      color: "",
    },
    {
      id: "74",
      name: "The Honored One",
      effect: "Giảm 1/2 Durability (làm tròn xuống), Nhận +3 MA.",
      weight: 0.9,
      color: "",
    },
    {
      id: "75",
      name: "Chaos Enchantment",
      effect: "Nhận +1 Str và +1 MA khi trong nhánh thua.",
      weight: 0.9,
      color: "",
    },
    {
      id: "76",
      name: "Dream Manipulation",
      effect: "Khi combat, đối phương -2 IQ và -1 Speed.",
      weight: 0.9,
      color: "",
    },
    {
      id: "77",
      name: "Powerful Strike",
      effect: "Nếu có vũ khí, nhận +2 MA",
      weight: 0.9,
      color: "",
    },
    {
      id: "78",
      name: "Fragrant",
      effect: "Thơm tho dễ chịu.",
      weight: 0.9,
      color: "",
    },
    {
      id: "79",
      name: "Hidden Potential",
      effect: "Nhận thêm 1 'Character Development'.",
      weight: 0.9,
      color: "",
    },
    {
      id: "80",
      name: "Voidwalking",
      effect: "Nhận +2 Speed.",
      weight: 0.9,
      color: "",
    },
    {
      id: "81",
      name: "Odin Blessing",
      effect:
        "Nhận '+2 Strength'. Chuyển thành '+2 vào Stat cao nhất' khi thua trận.",
      weight: 0.9,
      color: "",
    },
    {
      id: "82",
      name: "Misty Step Ahead",
      effect: "Ở round PvE khởi đầu với 1 điểm.",
      weight: 0.9,
      color: "",
    },
    {
      id: "83",
      name: "Ballet Dancing",
      effect: "Múa dẻo 💃",
      weight: 0.9,
      color: "",
    },
    {
      id: "84",
      name: "Luck Manipulation",
      effect:
        "Trong Combat: Ở vòng 64, trước mỗi trận combat, có 15% khả năng nhận +1 all stats và 5% khả năng nhận +2 all stats.",
      weight: 0.9,
      color: "",
    },
    {
      id: "85",
      name: "Tree Bound",
      effect: "Bị -1 All Stat không phải Durability, +5 vào Durability",
      weight: 0.9,
      color: "",
    },
    {
      id: "86",
      name: "Scrying",
      effect: "Đối thủ có 10% bị -4 Stat mạnh nhất.",
      weight: 0.9,
      color: "",
    },
    {
      id: "87",
      name: "Baldening",
      effect: "Khiến đối thủ bị rụng hết tóc. 💀",
      weight: 0.9,
      color: "",
    },
    {
      id: "88",
      name: "Cold Breeze",
      effect: "Mát lạnh!",
      weight: 0.9,
      color: "",
    },
    {
      id: "89",
      name: "Return to Sender",
      effect: "Sau Combat thua, -2 stat cao nhất của đối thủ.",
      weight: 0.9,
      color: "",
    },
    {
      id: "90",
      name: "Bucking Bronco",
      effect:
        "Round Martial Arts thắng và thắng trận sẽ nhận +1 Martial Arts. (Stack)",
      weight: 0.9,
      color: "",
    },
    {
      id: "91",
      name: "Detect Thoughts",
      effect:
        "Trong Combat: Nếu bạn có IQ cao hơn đối thủ, BIQ của bạn sẽ được +2.",
      weight: 0.9,
      color: "",
    },
    {
      id: "92",
      name: "Ritual of Blood",
      effect: "Nhận -4 Durability. Trong Combat: Đối phương nhận -1 all stats.",
      weight: 0.9,
      color: "",
    },
    {
      id: "93",
      name: "Quirkful",
      effect: "Nhận Thêm 1 Power với mỗi Quirk bạn có khi quay ra Power này.",
      weight: 0.9,
      color: "",
    },
    {
      id: "94",
      name: "Quirkless",
      effect: "Mất hết tất cả Quirk.",
      weight: 0.9,
      color: "",
    },
    {
      id: "95",
      name: "Sybaurafarming",
      effect:
        "Tất cả Base Stat trên 5 sẽ biến thành 5. Với mỗi Base Stat bị biến đối, nhận thêm 1 Quirk",
      weight: 0.9,
      color: "",
    },
    {
      id: "96",
      name: "Arcana Blast",
      effect: "Đối thủ nhận -3 Durability.",
      weight: 0.9,
      color: "",
    },
    {
      id: "97",
      name: "Blood Frenzy",
      effect: "Nhận -3 IQ và -3 BIQ, +2 all stat còn lại.",
      weight: 0.9,
      color: "",
    },
    {
      id: "98",
      name: "Analysis Sins",
      effect:
        "Trong Combat: Khi đối đầu với Demon, Vampire, Spirit, Orc, Skeleton và Goblin, nhận +1 IQ và +1 Strength",
      weight: 0.9,
      color: "",
    },
    {
      id: "99",
      name: "Cleaning Sins",
      effect:
        "Trong Combat: Khi đối đầu với Demon, Vampire, Spirit, Orc, Skeleton và Goblin, nhận +1 BIQ và +1 Dura",
      weight: 0.9,
      color: "",
    },
    {
      id: "100",
      name: "Hydrate",
      effect: "Cơ thể bạn được cung cấp đủ nước. 💦💦💦",
      weight: 0.9,
      color: "",
    },
    {
      id: "101",
      name: "Gourmand",
      effect: "Trong Combat: Nhận +4 Durability.",
      weight: 0.9,
      color: "",
    },
    {
      id: "102",
      name: "Lone Wolf",
      effect:
        "Nhận +3 Speed, khi gặp người chơi cũng có Power này, bạn sẽ mất Power này vĩnh viễn.",
      weight: 0.9,
      color: "",
    },
    {
      id: "103",
      name: "Swinging Maestro",
      effect: "Trong Combat: Nhận +4 Durability.",
      weight: 0.9,
      color: "",
    },
    {
      id: "104",
      name: "The Coast is Clear!",
      effect: "Bạn nhìn rõ đối thủ!",
      weight: 0.9,
      color: "",
    },
    {
      id: "105",
      name: "Prideful King",
      effect:
        "Trong Combat: Nếu bạn thua 3 round đầu tiên với khoảng cách dưới 3 điểm, bạn sẽ nhận +2 all stats trong phần còn lại của combat.",
      weight: 0.9,
      color: "",
    },
    {
      id: "106",
      name: "Groundwork",
      effect:
        "Trong Combat: Nếu bạn có ít nhất 3 Power khác, nhận +2 Strength và +1 Speed.",
      weight: 0.9,
      color: "",
    },
    {
      id: "107",
      name: "Dominator",
      effect:
        "Trong Combat: Nếu bạn thua ít nhất 2/3 round đầu tiên, đối phương nhận -1 all stats trong phần còn lại của combat.",
      weight: 0.9,
      color: "",
    },
    {
      id: "108",
      name: "Quay tay ra bài",
      effect:
        "Sau khi combat với người có Char Dev 'Nghe Bài thú tội', đối thủ nhận -2 IQ (Áp dụng sau combat)",
      weight: 0.9,
      color: "",
    },
    {
      id: "109",
      name: "Ice Spike",
      effect: "Đối thủ nhận -2 Durability.",
      weight: 0.9,
      color: "",
    },
    {
      id: "110",
      name: "Bash",
      effect:
        "Trong combat: Sau mỗi round thắng, đối thủ có 35% bị -3 vào chỉ số ở round kế tiếp.",
      weight: 0.9,
      color: "",
    },
    {
      id: "111",
      name: "Devour",
      effect:
        "Sau khi chiến thắng 1 trận PvP ở NHÁNH THUA, cướp 1 Power từ người thua cuộc.",
      weight: 0.9,
      color: "",
    },
  ],
};
