import { Section } from "../Types/Types.js";

export const quirkCountOptions: Section[] = [
  {
    id: "qc1",
    name: "1 Quirk",
    weight: 54.9,
    color: "#FFBABA",
    description: "Nhận 1 Quirk",
  },
  {
    id: "qc2",
    name: "2 Quirk",
    weight: 25,
    color: "#FFCC99",
    description: "Nhận 2 Quirk",
  },
  {
    id: "qc3",
    name: "3 Quirk",
    weight: 15,
    color: "#FFD700",
    description: "Nhận 3 Quirk",
  },
  {
    id: "qc4",
    name: "4 Quirk",
    weight: 5,
    color: "#87CEEB",
    description: "Nhận 4 Quirk",
  },
  {
    id: "qc10",
    name: "10 Quirk",
    weight: 0.1,
    color: "#9370DB",
    description: "Nhận 10 Quirk",
  },
];

export const quirkList: Section[] = [
  {
    id: "q1",
    name: "Sợ Nắng",
    weight: 1.79,
    color: "#FFBABA",
    description: "Nhận -1 Dura",
  },
  {
    id: "q2",
    name: "Sợ Chết",
    weight: 1.79,
    color: "#FF6666",
    description: "Sau khi combat, đối thủ bạn bị 'Sợ Chết'.",
  },
  {
    id: "q3",
    name: "Fear the Powerless",
    weight: 1.79,
    color: "#FF9999",
    description: "Nếu bạn không có Power, bạn sẽ bị -1 All Stats.",
  },
  {
    id: "q4",
    name: "Fearless",
    weight: 1.79,
    color: "#FFCC99",
    description:
      "Trong combat: Khi đối đầu với Spirit và Demon, Nhận +1 vào BIQ",
  },
  {
    id: "q5",
    name: "Anemic",
    weight: 1.79,
    color: "#FFC0CB",
    description: "Nhận -1 Strength.",
  },
  {
    id: "q6",
    name: "High Finger Skill",
    weight: 1.79,
    color: "#FFD700",
    description: 'Quay 1 player để làm "Lover". Nhận +1 Speed.',
  },
  {
    id: "q7",
    name: "Calm",
    weight: 1.79,
    color: "#87CEEB",
    description: "Nhận +1 BIQ",
  },
  {
    id: "q8",
    name: "Cay/Tri",
    weight: 1.79,
    color: "#9370DB",
    description: "Nhận -1 IQ và 1 BIQ. Khi thua trận, -1 IQ và -1 BIQ",
  },
  {
    id: "q9",
    name: "Cute",
    weight: 1.79,
    color: "#FF69B4",
    description: 'Quay 1 player để làm "Lover". Nhận +1 IQ',
  },
  {
    id: "q10",
    name: "Hào Phóng",
    weight: 1.79,
    color: "#FFA500",
    description:
      "Cho đối thủ nhận +1 Điểm khi vào trận chiến. (Không kích Crit và Gambler hay 'Ashina Skill')",
  },
  {
    id: "q11",
    name: "Heavy Handed",
    weight: 1.79,
    color: "#CD5C5C",
    description: "Nhận +1 Str",
  },
  {
    id: "q12",
    name: "Iron Stance",
    weight: 1.79,
    color: "#A9A9A9",
    description: "Nhận +1 Dura",
  },
  {
    id: "q13",
    name: "Lurker",
    weight: 1.79,
    color: "#20B2AA",
    description:
      "(1).Nhận +1 Speed (2).Nhận +1 Speed nếu có Archetype là 'Spy' (3).Nhận +1 Speed nếu có Quirk là 'Tracker'",
  },
  {
    id: "q14",
    name: "Peacemaker",
    weight: 1.79,
    color: "#00CED1",
    description:
      "Khi đẩy tỉ số trận đấu đến Hòa phải quyết định bằng Tiebreak, nhận +1 All Stats sau trận đấu đó.",
  },
  {
    id: "q15",
    name: "Nói nhiều",
    weight: 1.79,
    color: "#FF6347",
    description:
      'Lèm bà lèm bèm. Nếu bạn có cả "Nói ít". Nhận Quirk "Tâm thần"',
  },
  {
    id: "q16",
    name: "Nói ít",
    weight: 1.79,
    color: "#FF4500",
    description:
      'Nhận +1 Dura sau trận đấu với người "Nói nhiều". Nếu bạn có cả "Nói nhiều". Nhận Quirk "Tâm thần"',
  },
  {
    id: "q17",
    name: "Tâm Thần",
    weight: 1.79,
    color: "#8B0000",
    description: 'Nhận -5 IQ, biến thành +5 IQ nếu có Archetype "Devotee"',
  },
  {
    id: "q18",
    name: "Quan Trọng 1",
    weight: 1.79,
    color: "#F4A460",
    description:
      'Nhận +1 Str, +1 Spd. Nếu bạn đủ "Quan trọng", nhận thêm "Quote Nerd"',
  },
  {
    id: "q19",
    name: "Quan Trọng 2",
    weight: 1.79,
    color: "#D2691E",
    description:
      'Nhận +1 IQ, +1 BIQ. Nếu bạn đủ "Quan trọng", nhận thêm "Quote Nerd"',
  },
  {
    id: "q20",
    name: "Quan Trọng 3",
    weight: 1.79,
    color: "#8B4513",
    description:
      'Nhận +1 Dura, +1 MA. Nếu bạn đủ "Quan trọng", nhận thêm "Quote Nerd"',
  },
  {
    id: "q21",
    name: "Quote Nerd",
    weight: 1.79,
    color: "#4682B4",
    description: "Với mỗi 5 điểm base IQ, nhận thêm 1 Power.",
  },
  {
    id: "q22",
    name: "Ác Ý",
    weight: 1.79,
    color: "#A52A2A",
    description:
      '(1).Trong combat: Đối thủ nhận -2 Dura trong trận đấu và nhận +2 IQ sau trận đấu. (2).Nếu đối thủ thua trận đấu và sắp sửa bị loại, họ nhận 1 gear "Văn Tế" rồi mới bị loại.',
  },
  {
    id: "q23",
    name: "Focus",
    weight: 1.79,
    color: "#7FFF00",
    description: "Nhận +1 IQ, +1 Dura",
  },
  {
    id: "q24",
    name: "Grudgebearer",
    weight: 1.79,
    color: "#FF1493",
    description: "Khi xuống nhánh thua, Nhận +1 all stats",
  },
  {
    id: "q25",
    name: "Weak-Kneed",
    weight: 1.79,
    color: "#DB7093",
    description:
      "Trong combat: Round chiến thắng đầu tiên sẽ không nhận được điểm.",
  },
  {
    id: "q26",
    name: "Training Restricted",
    weight: 1.79,
    color: "#FFE4B5",
    description: "Nhận +1 all stats nhưng sẽ không có vòng đấu PvE.",
  },
  {
    id: "q27",
    name: "Night owl",
    weight: 1.79,
    color: "#4B0082",
    description: "Bạn có 20% nhận -1 all Stat sau mỗi trận chiến.",
  },
  {
    id: "q28",
    name: "Erudite",
    weight: 1.79,
    color: "#7B68EE",
    description: "Nhận +3 IQ",
  },
  {
    id: "q29",
    name: "Tracker",
    weight: 1.79,
    color: "#20B2AA",
    description:
      '(1).Nhận +1 IQ (2).Nhận +1 IQ nếu có Archetype là "Spy" (3).Nhận +1 IQ nếu có Quirk là "Lurker"',
  },
  {
    id: "q30",
    name: "Kleptomaniac",
    weight: 1.79,
    color: "#FF8C00",
    description:
      "Trộm lấy 1 món Legacy Gear từ vòng quay (50%) hoặc player (50%)",
  },
  {
    id: "q31",
    name: "Lazy",
    weight: 1.79,
    color: "#B0C4DE",
    description: "-1 Dura sau khi thắng trận.",
  },
  {
    id: "q32",
    name: "Meta Gaming",
    weight: 1.79,
    color: "#3CB371",
    description: "3 Stat Cao nhất sẽ được +1, 3 Stat thấp nhất sẽ bị -1",
  },
  {
    id: "q33",
    name: "Martyr",
    weight: 1.79,
    color: "#FF4500",
    description:
      "Khi bị loại, Quay 3 người chơi ngẫu nhiên để nhận +2 vào Stat thấp nhất.",
  },
  {
    id: "q34",
    name: "Curmudgeon",
    weight: 1.79,
    color: "#8B008B",
    description: "Không thể nhận Gear hay Weapon, nhận 3 Power.",
  },
  {
    id: "q35",
    name: "Fact Speaker",
    weight: 1.79,
    color: "#00FF7F",
    description: "Khi thắng Round IQ, nhận +1 vào 2 stat bất kì sau trận đấu.",
  },
  {
    id: "q36",
    name: "Thích ăn Rau",
    weight: 1.79,
    color: "#ADFF2F",
    description: "Good 🍀",
  },
  {
    id: "q37",
    name: "Không thích ăn Rau",
    weight: 1.79,
    color: "#9ACD32",
    description: "Nhận -1 Str",
  },
  {
    id: "q38",
    name: "Doomsayer",
    weight: 1.79,
    color: "#8B0000",
    description: "Đối thủ nhận -1 All stats trong trận đấu.",
  },
  {
    id: "q39",
    name: "Trash Talk",
    weight: 1.79,
    color: "#FF69B4",
    description: "Nếu BIQ của đối thủ dưới 4, nhận +5 vào IQ khi chiến đấu.",
  },
  {
    id: "q40",
    name: "Fragile",
    weight: 1.79,
    color: "#FFE4E1",
    description: "Nhận -4 Dura",
  },
  {
    id: "q41",
    name: "Raconteur",
    weight: 1.79,
    color: "#F08080",
    description:
      "Trong combat: Round chiến thắng đầu tiên của bản thân sẽ không được nhận điểm mà khiến đối thủ bị -1 điểm.",
  },
  {
    id: "q42",
    name: "Robust",
    weight: 1.79,
    color: "#FF6347",
    description: "Nhận +2 Str",
  },
  {
    id: "q43",
    name: "Resilient",
    weight: 1.79,
    color: "#00CED1",
    description: "Nhận +2 Dura",
  },
  {
    id: "q44",
    name: "Sanguine",
    weight: 1.79,
    color: "#FFD700",
    description: "Biến tất cả các Base Stat dưới 4 thành 4.",
  },
  {
    id: "q45",
    name: "Steady",
    weight: 1.79,
    color: "#ADFF2F",
    description: "Nhận +2 MA",
  },
  {
    id: "q46",
    name: "Unyielding",
    weight: 1.79,
    color: "#32CD32",
    description:
      "Khi thua round, Có 30% +1 vào Stat bất kì (Áp dụng sau Combat)",
  },
  {
    id: "q47",
    name: "Soft",
    weight: 1.79,
    color: "#BA55D3",
    description:
      "Trong combat: Khi thắng round, có 5% nhường lại điểm cho đối thủ.",
  },
  {
    id: "q48",
    name: "Thực dụng",
    weight: 1.79,
    color: "#DAA520",
    description:
      "Khi thắng và loại 1 người chơi, lột hết Gear trên người họ để dùng.",
  },
  {
    id: "q49",
    name: "Thích Liên Hoan Xác Thịt",
    weight: 1.79,
    color: "#FF1493",
    description: "80% Sẽ Make love với đối thủ sau trận đấu nếu thắng cuộc.",
  },
  {
    id: "q50",
    name: "Vung tiền qua cửa",
    weight: 1.79,
    color: "#FF8C00",
    description: "Sau khi thắng cuộc, vứt Normal Gear cũ trong người đi.",
  },
  {
    id: "q51",
    name: "Nervous",
    weight: 1.79,
    color: "#1E90FF",
    description: "Nhận +1 Speed, -1 BIQ",
  },
  {
    id: "q52",
    name: "Bloodthirsty",
    weight: 1.79,
    color: "#B22222",
    description:
      "Nhận +1 MA. Trong combat: Mỗi Round thắng nhận thêm 1 điểm, Thua Round sẽ mất toàn bộ điểm đang có.",
  },
  {
    id: "q53",
    name: "Relentless",
    weight: 1.79,
    color: "#FF4500",
    description: "Sau khi chiến thắng, Đối thủ sẽ bị -3 vào 1 stat ngẫu nhiên.",
  },
  {
    id: "q54",
    name: "Tham ăn",
    weight: 1.79,
    color: "#8FBC8F",
    description: "Với mỗi 2 Base Dura, nhận -1 Speed",
  },
  {
    id: "q55",
    name: "Beauty",
    weight: 1.79,
    color: "#FF69B4",
    description: 'Quay 1 player để làm "Lover". Nhận +1 BIQ',
  },
  {
    id: "q56",
    name: "Cruelty",
    weight: 1.79,
    color: "#DC143C",
    description:
      "Trong combat: Khi 1 round hòa, quyết định người nhận được 1 điểm bằng vòng quay 50/50 thay vì cả 2 không nhận được điểm.",
  },
];
