import { Section } from "../Types/Types";

export const subraceMap: Record<string, Section[]> = {
  Uma: [
    {
      id: "u1",
      name: "Maruzensky",
      weight: 4,
      color: "#AA4444",
      description: `Power: "Red Shift/LP1211-M".`,
    },
    {
      id: "u2",
      name: "Mejiro Ryan",
      weight: 4,
      color: "#44AA44",
      description: `Power: "Let's Pump Some Iron!".`,
    },
    {
      id: "u3",
      name: "Taiki Shuttle",
      weight: 4,
      color: "#4444AA",
      description: `Power: "Shooting for Victory".`,
    },
    {
      id: "u4",
      name: "Haru Urara",
      weight: 4,
      color: "#FF8888",
      description: `-2 all stats → +2 all stats nếu sống tới vòng 32.`,
    },
    {
      id: "u5",
      name: "Oguri Cap",
      weight: 6,
      color: "#AAAA44",
      description: `+1 Strength, +2 Speed.`,
    },
    {
      id: "u6",
      name: "Gold Ship",
      weight: 6,
      color: "#8888AA",
      description: `Quirk "Traning Restricted": 50% +1 all, 50% -1 all (chỉ combat đó).`,
    },
    {
      id: "u7",
      name: "Symboli Rudolf",
      weight: 6,
      color: "#44AAAA",
      description: `Thắng 3 trận PvP đầu → +1 all stats.`,
    },
    {
      id: "u8",
      name: "Silence Suzuka",
      weight: 6,
      color: "#FF4444",
      description: `+3 Speed.`,
    },
    {
      id: "u9",
      name: "Mejiro McQueen",
      weight: 6,
      color: "#8844AA",
      description: `+3 Durability.`,
    },
    {
      id: "u10",
      name: "Mihono Bourbon",
      weight: 6,
      color: "#44FFAA",
      description: `+1 Strength, +2 Durability.`,
    },
    {
      id: "u11",
      name: "Tokai Teio",
      weight: 6,
      color: "#AA8844",
      description: `Gấp đôi Speed Base khi dùng nhạc cụ làm vũ khí.`,
    },
    {
      id: "u12",
      name: "Agnes Tachyon",
      weight: 6,
      color: "#448888",
      description: `Power: "U=ma2".`,
    },
    {
      id: "u13",
      name: "Nice Nature",
      weight: 6,
      color: "#66AA66",
      description: `Combat 3-3 → bỏ tie-break, thắng ngay.`,
    },
    {
      id: "u14",
      name: "Special Week",
      weight: 6,
      color: "#AA66AA",
      description: `50% "Gourmand", 50% "Hydrate".`,
    },
    {
      id: "u15",
      name: "Rice Shower",
      weight: 6,
      color: "#4466AA",
      description: `+1 all stats ở nhánh thua → hết khi vào chung kết.`,
    },
    {
      id: "u16",
      name: "Mayano Top Gun",
      weight: 6,
      color: "#FFAA44",
      description: `+2 Durability, +1 BIQ.`,
    },
    {
      id: "u17",
      name: "Biwa Hayahide",
      weight: 6,
      color: "#66AAAA",
      description: `+2 IQ, +1 BIQ.`,
    },
    {
      id: "u18",
      name: "El Condor Pasa",
      weight: 6,
      color: "#AA4466",
      description: `Nếu Durability > 7 → +1 các chỉ số còn lại.`,
    },
  ],
  Goblin: [
    {
      id: "g1",
      name: "Goblin (1)",
      weight: 2,
      color: "#228822",
      description: `Nhận Archetype "Him".`,
    },
    {
      id: "g2",
      name: "Goblin (36)",
      weight: 20,
      color: "#447744",
      description: `Nhận -1 All Stats.`,
    },
    {
      id: "g3",
      name: "Goblin (1001)",
      weight: 40,
      color: "#66AA66",
      description: `Bro là 1 con Goblin 💀.`,
    },
    {
      id: "g4",
      name: "Goblin (5000)",
      weight: 20,
      color: "#88CC88",
      description: `Nhận 1 Gear.`,
    },
    {
      id: "g5",
      name: "Goblin (10000)",
      weight: 10,
      color: "#44AA44",
      description: `Nhận +1 Strength, +1 Durability và +1 Martial Arts.`,
    },
    {
      id: "g6",
      name: "Goblin (50000)",
      weight: 5,
      color: "#559955",
      description: `Nhận +2 Strength, +2 Durability và +1 Martial Arts.`,
    },
    {
      id: "g7",
      name: "Goblin (50000+)",
      weight: 3,
      color: "#99FF99",
      description: `Nhận +1 all stats.`,
    },
  ],
  Human: [
    {
      id: "sc1",
      name: "Trắng",
      weight: 20,
      color: "#EEEEDD",
      description: `-1 IQ, +1 BIQ.`,
    },
    {
      id: "sc2",
      name: "Vàng",
      weight: 40,
      color: "#DDCC66",
      description: `+1 IQ.`,
    },
    {
      id: "sc3",
      name: "Đen",
      weight: 40,
      color: "#222222",
      description: `+1 Durability.`,
    },
  ],

  Dwarf: [
    {
      id: "dt1",
      name: "Lùn núi (Mountain)",
      weight: 25,
      color: "#444444",
      description: `+2 Strength.`,
    },
    {
      id: "dt2",
      name: "Lùn xám (Gray)",
      weight: 20,
      color: "#555577",
      description: `+2 Speed, +1 Durability.`,
    },
    {
      id: "dt3",
      name: "Cổ lùn (Ancient)",
      weight: 15,
      color: "#886633",
      description: `Chắc chắn sử dụng được vũ khí đang có.`,
    },
    {
      id: "dt4",
      name: "Lùn thường",
      weight: 40,
      color: "#AAAAAA",
      description: `Không có hiệu ứng đặc biệt.`,
    },
  ],

  Troll: [
    {
      id: "tt1",
      name: "Regular Troll",
      weight: 42,
      color: "#227722",
      description: `Một con Troll thường 💀.`,
    },
    {
      id: "tt2",
      name: "Ice Troll",
      weight: 30,
      color: "#66CCFF",
      description: `Combat: đối thủ -1 Speed.`,
    },
    {
      id: "tt3",
      name: "Mountain Troll",
      weight: 25,
      color: "#775533",
      description: `+1 Durability.`,
    },
    {
      id: "tt4",
      name: "Lich Troll",
      weight: 3,
      color: "#884488",
      description: `Nhận 1 Power của player đã chết sau mỗi trận.`,
    },
  ],

  Elf: [
    {
      id: "et1",
      name: "High Elf",
      weight: 9,
      color: "#CCCCFF",
      description: `+2 Base IQ.`,
    },
    {
      id: "et2",
      name: "Dark Elf",
      weight: 8,
      color: "#442244",
      description: `+2 Base BIQ.`,
    },
    {
      id: "et3",
      name: "Wood Elf",
      weight: 20,
      color: "#228844",
      description: `1 random Power, +1 BIQ.`,
    },
    {
      id: "et4",
      name: "Sea Elf",
      weight: 14,
      color: "#3366AA",
      description: `1 random Power, +1 Durability.`,
    },
    {
      id: "et5",
      name: "Moon Elf",
      weight: 14,
      color: "#9999FF",
      description: `1 random Power, quay 1 "Lover".`,
    },
    {
      id: "et6",
      name: "Sun Elf",
      weight: 14,
      color: "#FFCC44",
      description: `1 random Power, +1 Martial Arts.`,
    },
    {
      id: "et7",
      name: "Star Elf",
      weight: 14,
      color: "#FF88FF",
      description: `1 random Power, +1 Speed.`,
    },
    {
      id: "et8",
      name: "Lythari",
      weight: 7,
      color: "#66FFCC",
      description: `+3 Base Speed, Quirk "Raconteur".`,
    },
  ],

  Werebeast: [
    {
      id: "bt1",
      name: "Wereraven",
      weight: 12,
      color: "#555577",
      description: `+1 Base Speed, +1 Base BIQ.`,
    },
    {
      id: "bt2",
      name: "Werewolf",
      weight: 12,
      color: "#773333",
      description: `+1 Base Strength, +1 Base Martial Arts.`,
    },
    {
      id: "bt3",
      name: "Wererat",
      weight: 12,
      color: "#777755",
      description: `Power: "Crimson Poison".`,
    },
    {
      id: "bt4",
      name: "Wereboar",
      weight: 12,
      color: "#AA6644",
      description: `Quirk: "Relentless".`,
    },
    {
      id: "bt5",
      name: "Werebear",
      weight: 12,
      color: "#553311",
      description: `+1 Base Strength, +1 Base Durability.`,
    },
    {
      id: "bt6",
      name: "Werebat",
      weight: 12,
      color: "#663366",
      description: `Power: "Bloody Strike".`,
    },
    {
      id: "bt7",
      name: "Werecapybara",
      weight: 12,
      color: "#CC9966",
      description: `Quirk: "Cute".`,
    },
    {
      id: "bt8",
      name: "Weresheep",
      weight: 8,
      color: "#EEEEEE",
      description: `Nhận 1 Power.`,
    },
    {
      id: "bt9",
      name: "Wereseal",
      weight: 8,
      color: "#99CCCC",
      description: `Nhận 1 Char Dev.`,
    },
  ],

  Vampire: [
    {
      id: "vb1",
      name: "Body 1–2",
      weight: 2.5,
      color: "#FFCCCC",
      description: `-1 all stats.`,
    },
    {
      id: "vb2",
      name: "Body 10+",
      weight: 5,
      color: "#DD99AA",
      description: `Vampire mới nhú.`,
    },
    {
      id: "vb3",
      name: "Body 50+",
      weight: 20,
      color: "#BB6688",
      description: `Vampire nhóc.`,
    },
    {
      id: "vb4",
      name: "Body 500+",
      weight: 25,
      color: "#993366",
      description: `+1 Speed, +1 IQ.`,
    },
    {
      id: "vb5",
      name: "Body 2000+",
      weight: 25,
      color: "#772255",
      description: `+1 Speed, +1 IQ, +1 BIQ.`,
    },
    {
      id: "vb6",
      name: "Body 10000+",
      weight: 20,
      color: "#551144",
      description: `+1 Speed, +1 IQ, +1 BIQ, +1 Durability.`,
    },
    {
      id: "vb7",
      name: "Body 50000+",
      weight: 2.5,
      color: "#330022",
      description: `+1 all stats.`,
    },
  ],
  Dragon: [
    {
      id: "dr1",
      name: "Crimson Dragon",
      weight: 9,
      color: "#FF6666",
      description: `+1 Base IQ và +1 Base Durability.`,
    },
    {
      id: "dr2",
      name: "Stone Dragon",
      weight: 9,
      color: "#CC9966",
      description: `+2 Base Durability.`,
    },
    {
      id: "dr3",
      name: "Amethyst Dragon",
      weight: 9,
      color: "#9966CC",
      description: `-2 All Stats, nhận 5 Power.`,
    },
    {
      id: "dr4",
      name: "Ancient Dragon",
      weight: 9,
      color: "#666633",
      description: `Nhận Power "Divine Smite".`,
    },
    {
      id: "dr5",
      name: "Undead Dragon",
      weight: 9,
      color: "#666666",
      description: `+1 Summon và +1 Durability.`,
    },
    {
      id: "dr6",
      name: "Zephyrian Dragon",
      weight: 9,
      color: "#66CCCC",
      description: `Nhận 1 Power và 1 Quirk.`,
    },
    {
      id: "dr7",
      name: "Tideborn Dragon",
      weight: 9,
      color: "#3399FF",
      description: `+2 Strength.`,
    },
    {
      id: "dr8",
      name: "Thunder Dragon",
      weight: 10,
      color: "#FFCC00",
      description: `Nhận Power "Thunder Orb".`,
    },
    {
      id: "dr9",
      name: "Flame Dragon",
      weight: 12,
      color: "#FF3300",
      description: `Nhận 1 Power và +1 vào Stat thấp nhất.`,
    },
    {
      id: "dr10",
      name: "Ice Dragon",
      weight: 10,
      color: "#66CCFF",
      description: `+1 Char Dev và +1 vào Stat thấp nhất.`,
    },
    {
      id: "dr11",
      name: "Chaos Dragon",
      weight: 5,
      color: "#9900CC",
      description: `Nhận 3 Quirk.`,
    },
  ],
  Angel: [
    {
      id: "ar1",
      name: "Angels",
      weight: 49,
      color: "#FFFFFF",
      description: `Không có gì đặc biệt 💀`,
    },
    {
      id: "ar2",
      name: "Archangels",
      weight: 18,
      color: "#FFD700",
      description: `+1 Speed, +1 Martial Arts.`,
    },
    {
      id: "ar3",
      name: "Principalities",
      weight: 8,
      color: "#FFAA66",
      description: `Sau mỗi combat, +2 vào stat thấp nhất.`,
    },
    {
      id: "ar4",
      name: "Powers",
      weight: 7,
      color: "#FF6666",
      description: `Archetype "Paladin", +1 Martial Arts.`,
    },
    {
      id: "ar5",
      name: "Virtues",
      weight: 6,
      color: "#66DDFF",
      description: `3 stat cao nhất không thể bị Debuff.`,
    },
    {
      id: "ar6",
      name: "Dominions",
      weight: 5,
      color: "#AAAAFF",
      description: `Nhận 2 Power.`,
    },
    {
      id: "ar7",
      name: "Ophanim",
      weight: 4,
      color: "#FF77FF",
      description: `+1 all stats.`,
    },
    {
      id: "ar8",
      name: "Cherubim",
      weight: 3,
      color: "#FF4444",
      description: `+2 all stats.`,
    },
  ],

  "Demi-God": [
    {
      id: "gg1",
      name: "Cursed Sword",
      weight: 30,
      color: "#222222",
      description: `-1 All Stats.`,
    },
    {
      id: "gg2",
      name: "War",
      weight: 7,
      color: "#AA2222",
      description: `+2 Strength.`,
    },
    {
      id: "gg3",
      name: "Love",
      weight: 7,
      color: "#FF88AA",
      description: `Quirk "Beauty".`,
    },
    {
      id: "gg4",
      name: "Time",
      weight: 7,
      color: "#6666FF",
      description: `+2 Speed.`,
    },
    {
      id: "gg5",
      name: "Fortune",
      weight: 7,
      color: "#FFD700",
      description: `Giàu.`,
    },
    {
      id: "gg6",
      name: "Secret Evil",
      weight: 7,
      color: "#884444",
      description: `+1 Stat cao nhất và thấp nhất khi combat.`,
    },
    {
      id: "gg7",
      name: "Knowledge",
      weight: 7,
      color: "#33CCFF",
      description: `+2 IQ.`,
    },
    {
      id: "gg8",
      name: "Arts and Magic",
      weight: 7,
      color: "#9966FF",
      description: `1 Power, +1 IQ.`,
    },
    {
      id: "gg9",
      name: "Wilderness & Sea",
      weight: 7,
      color: "#229977",
      description: `1 lần Summon Wheel.`,
    },
    {
      id: "gg10",
      name: "Creation",
      weight: 7,
      color: "#CCCCCC",
      description: `1 Creator's Favor.`,
    },
    {
      id: "gg11",
      name: "Moon",
      weight: 7,
      color: "#9999FF",
      description: `Archetype "Pacifist" từ đầu (sẽ nhận thêm 1 Archetype nữa).`,
    },
  ],

  Demon: [
    {
      id: "ds1",
      name: "Lucifer",
      weight: 14,
      color: "#550000",
      description: `-2 stat cao nhất khi thắng.`,
    },
    {
      id: "ds2",
      name: "Beelzebub",
      weight: 14,
      color: "#773333",
      description: `Quirk "Tham Ăn", -2 Speed.`,
    },
    {
      id: "ds3",
      name: "Leviathan",
      weight: 14,
      color: "#225577",
      description: `Quay 1 "Gia tộc", -1 all stats sau khi combat với người từ Gia tộc đó.`,
    },
    {
      id: "ds4",
      name: "Behemoth",
      weight: 14,
      color: "#885522",
      description: `Quirk "Cay/Tri", -2 IQ.`,
    },
    {
      id: "ds5",
      name: "Mammon",
      weight: 14,
      color: "#AAAA33",
      description: `Archetype "Gambler Bloodline".`,
    },
    {
      id: "ds6",
      name: "Belphegor",
      weight: 14,
      color: "#444466",
      description: `Quirk "Lazy", -2 Durability.`,
    },
    {
      id: "ds7",
      name: "Asmodeus",
      weight: 14,
      color: "#BB2266",
      description: `(1) Quirk "High Finger Skill", "Cute", "Beauty", "Thích Liên Hoan Xác Thịt" + quay thêm 1 "Lover". (2) Với mỗi Lover: -1 Dura, -1 BIQ.`,
    },
    {
      id: "ds8",
      name: "Sinful King",
      weight: 2,
      color: "#000000",
      description: `Cả 7 tội lỗi ập vào.`,
    },
  ],

  God: [
    {
      id: "g1",
      name: "Zeus",
      weight: 8.33,
      color: "#FFFFAA",
      description: `3 random Power. Sau mỗi combat, Char Dev "Make Love".`,
    },
    {
      id: "g2",
      name: "Hera",
      weight: 8.33,
      color: "#FFAAAA",
      description: `(1) Combat: +2 all stats nếu đối thủ thuộc race mà Zeus đã "Make Love". (2) Nếu còn ≤32 người mà Zeus không có hoặc đã chết → Char Dev "No more family".`,
    },
    {
      id: "g3",
      name: "Poseidon",
      weight: 8.33,
      color: "#77CCFF",
      description: `2 random Power, +2 Speed.`,
    },
    {
      id: "g4",
      name: "Demeter",
      weight: 8.33,
      color: "#99DD77",
      description: `3 random Power, 1 Char Dev.`,
    },
    {
      id: "g5",
      name: "Apollo",
      weight: 8.33,
      color: "#FFDD55",
      description: `Power "Divine Smite", "Healing Factor".`,
    },
    {
      id: "g6",
      name: "Artemis",
      weight: 8.33,
      color: "#99CC99",
      description: `Power "Hunter's Rewards".`,
    },
    {
      id: "g7",
      name: "Ares",
      weight: 8.33,
      color: "#DD4444",
      description: `2 random Power. Sau mỗi combat thắng: +1 random Power.`,
    },
    {
      id: "g8",
      name: "Athena",
      weight: 8.33,
      color: "#88AAFF",
      description: `+3 IQ, +4 BIQ.`,
    },
    {
      id: "g9",
      name: "Hephaestus",
      weight: 8.33,
      color: "#AA7744",
      description: `(1) Chắc chắn dùng được vũ khí. (2) Chắc chắn có Unique Weapon ở Vòng Quay. Nếu không còn: +2 all stats, +1 random Normal Weapon.`,
    },
    {
      id: "g10",
      name: "Aphrodite",
      weight: 8.33,
      color: "#FF77AA",
      description: `Mỗi combat: Hút 2 điểm ở stat cao nhất của đối thủ.`,
    },
    {
      id: "g11",
      name: "Hermes",
      weight: 8.33,
      color: "#77FFDD",
      description: `Mặc định thắng Round Speed.`,
    },
    {
      id: "g12",
      name: "Hestia",
      weight: 8.33,
      color: "#FFBB77",
      description: `1 Power. Sau mỗi combat (PvP/PvE): +1 Power, +1 random stat.`,
    },
  ],
  "Primordial Being": [
    {
      id: "el1",
      name: "Air",
      weight: 25,
      color: "#99CCFF",
      description: `Power "Blowing Leaves", +2 Speed.`,
    },
    {
      id: "el2",
      name: "Water",
      weight: 25,
      color: "#3366FF",
      description: `Power "Water Breathing", +2 BIQ.`,
    },
    {
      id: "el3",
      name: "Fire",
      weight: 25,
      color: "#FF6633",
      description: `Power "Fire Control", +2 Martial Arts.`,
    },
    {
      id: "el4",
      name: "Earth",
      weight: 25,
      color: "#996633",
      description: `Power "Earth-Shaking", +2 Strength.`,
    },
  ],
  Skeleton: [
    {
      id: "01",
      name: "Goblin",
      weight: 6.5,
      color: "#7A1F1F",
      description: "",
    },
    {
      id: "02",
      name: "Gnome",
      weight: 6.5,
      color: "#B47D35",
      description: "",
    },
    {
      id: "03",
      name: "Human",
      weight: 6.5,
      color: "#C2B678",
      description: "",
    },
    {
      id: "04",
      name: "Dwarf",
      weight: 6.5,
      color: "#3D6B3D",
      description: "",
    },
    {
      id: "06",
      name: "Troll",
      weight: 5,
      color: "#4F772D",
      description: "",
    },
    {
      id: "07",
      name: "Orc",
      weight: 5,
      color: "#38761D",
      description: "",
    },
    {
      id: "08",
      name: "Dryad",
      weight: 5,
      color: "#228B22",
      description: "",
    },
    {
      id: "09",
      name: "Elf",
      weight: 6,
      color: "#2F7EBB",
      description: "",
    },
    {
      id: "10",
      name: "Spirit",
      weight: 5,
      color: "#7F7FFF",
      description: "",
    },
    {
      id: "11",
      name: "Uma",
      weight: 6,
      color: "#CC66CC",
      description: "",
    },
    {
      id: "12",
      name: "Werebeast",
      weight: 5,
      color: "#8B4513",
      description: "",
    },
    {
      id: "13",
      name: "Vampire",
      weight: 5,
      color: "#660000",
      description: "",
    },
    {
      id: "14",
      name: "Giant",
      weight: 5,
      color: "#999933",
      description: "",
    },
    {
      id: "15",
      name: "Dragon",
      weight: 5,
      color: "#990000",
      description: "",
    },
    {
      id: "16",
      name: "Angel",
      weight: 4,
      color: "#FFD700",
      description: "",
    },
    {
      id: "17",
      name: "Demi-God",
      weight: 3.5,
      color: "#FF8C00",
      description: "",
    },
    {
      id: "18",
      name: "Primordial Being",
      weight: 3.5,
      color: "#8A2BE2",
      description: "",
    },
    {
      id: "19",
      name: "Demon",
      weight: 3,
      color: "#8B0000",
      description: "",
    },
    {
      id: "20",
      name: "God",
      weight: 3,
      color: "#FFFFFF",
      description: "",
    },
  ],
};
